#!/usr/bin/env python3
"""postgen.py NN NM.c : generic post-processing of a pipelined em NN nm file (agent D)"""
import re,sys,os
NN=sys.argv[1]; p=sys.argv[2]
ROOT='/home/james/claude projects/MH XBOX/mh1-wt/D'
s=open(p).read()
W='EM%sW'%NN
# ---------- header
hp='%s/include/em%s.h'%(ROOT,NN)
if (not os.path.exists(hp)) or 'postgen' in open(hp).read():
    # nm struct
    m=re.search(r'typedef struct %s \{(.*?)\} %s;'%(W,W),s,re.S)
    nmfields={}
    if m:
        pos=0
        for l in m.group(1).split('\n'):
            mm=re.match(r'\s*(\w+) x([0-9A-F]+);',l)
            if mm: nmfields[int(mm.group(2),16)]=mm.group(1)
    # existing typedef in emNN.c
    ex={}
    c=open('%s/src/game/em/em%s.c'%(ROOT,NN)).read()
    mm=re.search(r'typedef struct EM%sW \{(.*?)\} EM%sW;'%(NN,NN),c,re.S)
    if mm:
        for l in mm.group(1).split('\n'):
            q=re.match(r'\s*(\w+)\s+(\w+)(\[\w+\])?;\s*/\*\s*0x([0-9A-F]+)\s*(.*?)\s*\*/',l)
            if q and not q.group(2).startswith('_pad'):
                ex[int(q.group(4),16)]=(q.group(1),q.group(2),q.group(3),q.group(5))
    # anim offset from ef_move_sub
    an=re.search(r'M2C_FIELD\(arg1, s16 \*, (\d+|0x[0-9A-F]+)\)',s)
    anim=int(an.group(1),0) if an else None
    fields={}
    for off,t in nmfields.items(): fields[off]=(t,'x%02X'%off,None,'')
    for off,(t,n,arr,cm) in ex.items(): fields[off]=(t,n,arr,cm)
    fields[0]=('u8','eff',None,'effect_move step') if 0 not in fields or fields[0][1]=='x00' else fields[0]
    if anim is not None: fields[anim]=('s16','anim',None,'animation the sound/effect script follows')
    out='#ifndef EM%s_H\n#define EM%s_H\n/* em%s work area at EMW+0x444 for src/game/em/em%s*.c (field names are guesses; em%s.c has its own copy of the first fields; generated by postgen from the code). */\n#include "em.h"\n\ntypedef struct %s {\n'%(NN,NN,NN,NN,NN,W)
    pos=0
    def sz(t,arr):
        b={'u8':1,'s8':1,'u16':2,'s16':2,'s32':4,'u32':4,'f32':4,'int':4}.get(t,4)
        return b*(int(arr.strip('[]')) if arr and arr.strip('[]').isdigit() else 1)
    for off in sorted(fields):
        t,n,arr,cm=fields[off]
        if off<pos: continue
        if off>pos: out+='    u8 _pad%02X[0x%X];\n'%(pos,off-pos)
        out+='    %s %s%s;%s/* 0x%02X %s */\n'%(t,n,arr or '',' '*max(1,20-len(t+n+(arr or ''))),off,cm)
        pos=off+sz(t,arr)
    out+='} %s;\n\n#endif\n'%W
    open('%s/include/em%s.h'%(ROOT,NN),'w').write(out)
    spdoff=[o for o,(t,n,a,c) in fields.items() if n=='spd']
    if spdoff:
        s=re.sub(r'\(s32 \*\) \(\(s32 \*\)\(\(u8 \*\)w \+ 0x%X\)\)'%spdoff[0],'w->spd',s)
        s=re.sub(r'\(s32 \*\)\(\(u8 \*\)w \+ 0x%X\)'%spdoff[0],'w->spd',s)
    # rename uses
    for off,(t,n,arr,cm) in fields.items():
        if n.startswith('x') and arr is None: continue
        if arr:
            cnt=int(arr.strip('[]')) if arr.strip('[]').isdigit() else 1
            for i in range(cnt):
                s=s.replace('w->x%02X'%(off+4*i),'w->%s[%d]'%(n,i))
        else:
            s=s.replace('w->x%02X'%off,'w->%s'%n)
s=re.sub(r'typedef struct %s \{.*?\} %s;\n'%(W,W),'',s,flags=re.S)
if '#include "em%s.h"'%NN not in s: s=s.replace('#include "quest.h"\n','#include "quest.h"\n#include "em%s.h"\n'%NN,1)
open(p,'w').write(s)
print('header done')
