#ifndef EM17_H
#define EM17_H
/* em17 work area at EMW+0x444 for src/game/em/em17*.c (field names are guesses; em17.c has its own copy of the first fields; generated by postgen from the code). */
#include "em.h"

typedef struct EM17W {
    u8 eff;               /* 0x00 effect_move step */
    u8 _pad01[0x1];
    s16 anim;             /* 0x02 animation the sound/effect script follows */
    u8 _pad04[0x2];
    s16 x06;              /* 0x06  */
    u8 _pad08[0x8];
    f32 dist;             /* 0x10 distance to the target (1000 with none) */
    u16 dang;             /* 0x14 angle left to turn */
    u8 _pad16[0x1];
    u8 has_tgt;           /* 0x17  */
    s8 x18;               /* 0x18  */
    u8 x19;               /* 0x19  */
    u8 x1A;               /* 0x1A attack variant (atk 4) */
    u8 x1B;               /* 0x1B  */
    s32 turn_left;        /* 0x1C  */
    s32 bank_max;         /* 0x20 bank limit for senkai_sub */
    u8 _pad24[0xC];
    s32 spd[3];           /* 0x30 passed to speed_add(_g) (angle in [1]) */
    s32 pitch_spd;        /* 0x3C ang[0] returns to 0 by this much */
    s32 turn;             /* 0x40 maximum turn per call */
    s32 bank_spd;         /* 0x44 ang[2] step */
    u8 x48;               /* 0x48  */
    u8 x49;               /* 0x49  */
    u8 x4A;               /* 0x4A  */
    u8 _pad4B[0x1];
    u8 adj_x;             /* 0x4C fly_adjy2 channels on/off */
    u8 adj_y;             /* 0x4D  */
    u8 adj_z;             /* 0x4E  */
    u8 adj_type;          /* 0x4F table row */
    s16 adj_tm;           /* 0x50 time into the table */
    u8 _pad52[0x51];
    u8 xA3;               /* 0xA3  */
} EM17W;

#endif
