#ifndef F_GAME_H
#define F_GAME_H
/* Declarations shared by the game-flow files (f_game*.c). Called functions are
 * declared without prototypes where the argument types are unknown. */
#include "flow.h"

void Copy_user_id();
void Disp_NowLoading2();
void Load_overlay();
void Tsk_Execute();
void all_reset();
void Quest_init();
void net_send_sys();
void flInitPhaseStarted();
void Info_Initialization();
void Quest_start();
void Start_item_init();
void Disp_load_start();
void EvDemoInitialize();
void stage_init();
void stage_load();
void smell_init();
void smoke_init();
void senko_init();
void ear_init();
void em_yobi_init();
void round_init();
void flInitPhaseFinished();
void move();
int Online_ck();
int net_start_ck();
void swset();
void Quest_timer_reset();
void stage_fog_set();
void stage_set_set();
void stage_bgm_set();
void flCompact();
void view_reset();
void CameraMove();
void fade_set();
void flSndPortStop();
void FlushCache();
void load_bin_req();
int load_busy_ck();
void flSndPackLoadBG();
void flSndPackLoadBG2();
int flSndPackLoadStatus();
void snd_joint_load_init();
int snd_joint_load_pl();
int snd_joint_load();
extern u8 *pl_area_top;
extern s16 Snd_steft_tbl[];
void net_receive_pl_pos_set();
void EvDemoMove();
int game_core();
void Info_control();
int Quest_condition_judging();
int Game_clear_ck();
void se_stop_all();
void Zero_rev_set();
void str_pause();
void str_stop();
void vib_stop_all();
void flFlip();
void stage_free();
void Quest_next_em_clr();
void Ext_pick_point_st_clr();
void DispWholeMap();
void st_model_load();
void clr_move_work();
void light_move();
void ot_init();
void prim_init();
void init_light_work();
void stage_w_init();
void em_effect_pull();
void Quest_next_em_set();
void pl_init();
void flfntSetSize();
void flfntLocate();
void font_set_palette();
void font_print();
void font_draw();
void SpritePut();
void trans();
void result_prog();
void hit_check();
extern char lit_778_00358160[];
extern char lit_779_00358180[];
extern char lit_780_003581A0[];
extern char lit_824_003581C0[];
extern char lit_825_003581F0[];
extern char lit_826_003581F8[];
extern char lit_827_00358200[];
extern u16 System_timer;
typedef struct TSK { u8 _pad00[8]; u8 step; } TSK;
typedef struct INETSYS { u8 x0; u8 x1; u8 x2; u8 _pad3; s16 x4; s16 x6; s16 x8; } INETSYS;
typedef struct USERDATA { u8 _pad00[0x374]; u32 x374; } USERDATA;
extern INETSYS InetSys;
extern USERDATA User_data;
extern struct { u8 _pad00[0x534]; s32 x534; } mem_tex;
extern struct { u8 _pad00[0x2C]; s32 x2C; } net_common_w;
extern u8 D_6DD7E0[];
extern u8 *cw;
extern u8 COM_R_No_0, COM_R_No_1, COM_R_No_2, COM_R_No_3, COM_R_No_4, COM_R_No_5, COM_RET;
extern s16 Vs_Cnt_0;
void game_init();
void func_5D58C0();
void AQ_init();
void network_work_init();
int softdip_ck();
void func_5C4D40();
int ms_network_sub();
int server_connect();
void func_5C0680();
int func_5B70D0();
void fade_reset();
int func_5B69E0();
int connect_error();
void AQ_session_exit();
void Tsk_Exit();
void Select_Tsk_Execute();
int session_connect();
int return_mc_save();
void Ncm_spr_kill_all_ex_BG();
int Ncm_mmbb_spr_load();
int Ncm_mmbb_spr_create();
void Ncm_spr_BG_set();
void Ncm_spr_set_diarog_b();
void Ncm_err_mssage_disp_req();
int net_shot_ok_ck();
void Ncm_spr_kill_all();
void Net_all_reset();
void Net_trans_set();
int func_5D8680();
void AQ_exec();
void Quest_error_set2();
int AQSession_wait();
int AQ_join_num_get();
void AQ_recv_flag_set();
int func_5B7020();
void AQ_session_exit_online();
void AQ_send();
extern s32 ss_time;
extern s32 ss_flag;


#endif
