/* lbnpc_proto.h - extern data and unprototyped declarations (generated by tools/lbmerge.py). */
#ifndef LBNPC_PROTO_H
#define LBNPC_PROTO_H
#include "lbnpc.h"



void Lb_npc_move_sub();
void npcMvFOOTWORK();
void npcMvWALK();
void npcMvENJOY();
void npcMvTALK();
void npcMvWARP();
void npcMvDOWN();
void npcMvTOPL();
void npcMvBOARD();
void npcMvSHOP();
void npcMvBEER();
void npcMvDRUNKDOWN();
void npcMvTOPL2();
void npcMvRANDWAIT();
void npcMvWALL();
void npcMvKEGA();
void npc_move_common();
void lb_npc_bar_move();
void lb_npc_mother_move();
void lb_npc_father_move();

#endif
