/* lbshop2_proto.h - extern data and unprototyped declarations (generated by tools/lbmerge.py). */
#ifndef LBSHOP2_PROTO_H
#define LBSHOP2_PROTO_H
#include "lbshop2.h"

extern s32 *material_shop_tbl[];
extern s32 *tool_shop_tbl[];
extern s32 *foods_shop_tbl[];
extern s32 goods_shop_local[];
extern s32 goods_shop_tbl[];
extern s32 goods_shop_local2[];
extern u8 *npc_dialog_table[];
extern u8 *D_3E4FA0[];
extern void NPCZoomInCameraCancel();
extern void flMemset();
extern s8 Lb_talk_check_default();
extern int Lb_shop_move();
extern void lb_shop_init();
extern void Lb_shop_talk();
extern void Lbc_set_prim();
extern void cnWrap_SoundRequest();
extern s32 shop_default_help[];
extern void lb_shop_put_shopHelp();
extern int lb_monster_list_check();
extern int Monster_list_chk();
extern void Lb_put_set01();
extern void Lb_draw_square();
extern void Lb_put_button();
extern void Lb_put_itemIcon();
extern void Lb_put_itemRare();
extern void Lb_put_msg_type2();
extern void flfntLocate();
extern void flfntSetSize();
extern void font_print_ex();
extern void font_print_sp();
extern void font_set_palette();
extern int Equip_moji_color_rare();
extern u8 lb_shop_msg[];
extern char lit_324_0065E1D0[];
extern char lit_325_0065E1D8[];
extern short Ud_item_num_ck3();
extern short Ud_item_num_ck();
extern int Ud_item_search_space();
extern void Gold_add();
extern void Ud_item_stack();
extern void Ud_item_erase();
extern void Add_to_Monster_list();
extern char *item_str[];
extern int Online_ck();
extern char *strcpy();
extern void *memset();

void Lb_shop_init_member();
void Lb_shop();
int lb_shop_select();
void lb_shop_put_itemDetail();
void lb_shop_listIcon(int x, int y, int z, s16 n);
void lb_shop_tag_decide();
int lb_shop_item_select();
int Lb_shop_item_checkMax();
void lb_shop_decide();
int CheckItemPrice_005AFEE0();

#endif
