/* lbui_proto.h - extern data and unprototyped declarations (generated by tools/lbmerge.py). */
#ifndef LBUI_PROTO_H
#define LBUI_PROTO_H
#include "lbui.h"



void Lb_eat_to_bell();
void Lb_eat_to_rcpt();
void Lb_eat_to_eat();
void Lb_eat_to_end();
void event_eat_trans_ot1();
void SetDialogData_HTML();
void SetDialogYesNo();
void SetSceneTitle();
void SetSceneSubTitle();
void SetSceneSubTitleColor();
void SetHelpLineMsg();
void tl_menu_cursor_up();
void tl_menu_cursor_down();
int getUserInfo();
int Lb_get_comment();
int Lb_checkChatID();
void Lb_clearChatID();
void Lb_clearChatList();
void plaza_ReibunEdit();
void plaza_checkChatLog();
void tl_exit_sub_menu();
void put_plaza_menu();
void put_titles();
void put_titles2();
void put_mainWindow();
void put_mainWindowTex();
int Lb_get_cursor_col();
void plaza_trans_ot1();
void Get_PlazaName();
void Get_LobbyName();
void Lbs_load();
void Lbc_release();

#endif
