/* lbui_proto.h - extern data and unprototyped declarations (generated by tools/lbmerge.py). */
#ifndef LBUI_PROTO_H
#define LBUI_PROTO_H
#include "lbui.h"

extern s16 pfl_menu_449[];
extern s16 frame_matA_450[];
extern s16 frame_matB_451[];
extern u8 eat_command_452[];
extern char eat_data_name[][0x11];
extern char lit_473_0065B948[];
extern char lit_474_0065B950[];
extern char lit_475_0065B960[];
extern char lit_476_0065B970[];
extern char lit_477_0065B980[];
extern char lit_520_0065B990[], lit_521_0065B9B0[], lit_522_0065B9D0[], lit_523_0065B9F0[], lit_524_0065BA10[], lit_525_0065BA30[], lit_526_0065BA50[], lit_527_0065BA70[];
extern EATSTAT Status_add_tbl[];
extern EATRES *eat_result[];
extern s8 eat_data_type[];
extern s8 eatResult;
extern EATRES *pRes;
extern char lit_216_0065B900[];
extern EATENT *eat_data[];
extern char RoomRule[];

void Lb_eat();
void lb_eat_set();
void Lb_eat_to_bell();
void Lb_eat_to_rcpt();
void Lb_eat_to_eat();
void Lb_eat_to_end();
int event_eat_rcpt();
void event_eat_trans_ot0();
void event_eat_set_msg();
void event_eat_trans_ot1();
void SetDialogData_HTML();
void SetDialogYesNo();
void SetDialogData();
void set_dialog_square();
void SetSceneTitle();
void SetSceneSubTitle();
void SetSceneSubTitleColor();
void SetHelpLineMsg();
void DispSceneTitle();
void DispSceneSubTitle();
void LBDisp_NowLoading2();
int Lbs_plaza();
void plaza_selectMenu();
void plaza_backToServer();
int getUserInfo();
int Lb_get_comment();
int mail_input();
void get_friend_page_num();
int get_page_num();
int my_comment_input();
void plaza_checkMyStatus();
int plaza_setMyComment();
int plaza_req_input();
int getHandleFromID();
int lb_chatMemberCheck();
int Lb_checkChatID();
int Lb_addChatMember();
void Lb_clearChatMember();
void Lb_clearChatID();
void Lb_clearChatList();
void plaza_ReibunEdit();
void plaza_checkChatLog();
void plaza_logOut();
void plaza_chatMain();
void tl_exit_sub_menu();
void put_plaza_menu();
void put_titles();
void put_titles2();
void put_mainWindow();
void put_mainWindowTex();
int Lb_get_cursor_col();
void plaza_checkMyStatusTrans();
void plaza_chatTrans();
void plaza_trans_ot1();
void Get_PlazaName();
void Get_LobbyName();
void Lbs_load();
void Lbc_release();
char *GetRoomRule();
int Lbs_MatchStart();
void lb_npc_effect_move();

#endif
