#!/usr/bin/env python3
"""draft2c.py MODULE FILE [FILE...]: m2c drafts (tools/draft.py) for every function in
asm/MODULE/text/FILE.s turned into plain compilable C: K&R extern declarations, M2C_FIELD macros,
u8[] data externs, gp-relative globals named. The result is a first near-match to be cleaned by
hand (types are guesses); it goes to stdout.
Usage: python3 tools/draft2c.py yn f_yn > src/yn/foo_nm.c
       python3 tools/draft2c.py lobby -f Local_main,Lb_stage_load   (named functions only)"""
import bisect, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
module = sys.argv[1]
funcs = []
if sys.argv[2] == "-f":
    funcs = sys.argv[3].split(",")
else:
    for f in sys.argv[2:]:
        funcs += re.findall(r"^glabel (\S+)$", open(os.path.join(ROOT, "asm", module, "text", f + ".s")).read(), re.M)

LIBC = {"strcmp", "strcpy", "strlen", "memset", "sprintf", "strncmp", "memcpy"}
GP = 0x38EB70
SYMS = []
for sf in ("main.txt", module + ".txt"):
    for l in open(os.path.join(ROOT, "config/symbols", sf)):
        m = re.match(r"(\w+) = (0x[0-9A-Fa-f]+);(.*)", l)
        if m:
            SYMS.append((int(m.group(2), 16), m.group(1)))
SYMS.sort()
KEYS = [x[0] for x in SYMS]

protos, datas, bodies = set(), set(), []
gpdecl = {}
for fn in funcs:
    out = subprocess.run(["python3", os.path.join(ROOT, "tools/draft.py"), module, fn],
                         capture_output=True, text=True, cwd=ROOT).stdout
    if "Unable to determine jump table" in out and module == "lobby":   # tables read from lobby.bin
        import tempfile
        with tempfile.NamedTemporaryFile("r", suffix=".c") as tf:
            subprocess.run(["python3", os.path.join(ROOT, "tools/lbdraft_jt.py"), tf.name, fn],
                           capture_output=True, text=True, cwd=ROOT)
            jt = open(tf.name).read()
        if jt.strip() and "Decompilation failure" not in jt:
            out = jt
    body = []
    for l in out.split("\n"):
        m = re.match(r"^[\w \*]+?\**\s*(\w+)\(.*\);\s*/\* extern \*/", l)
        if m:
            protos.add(m.group(1))
            continue
        m = re.match(r"^extern [\w ]+? \**(\w+);", l)
        if m:
            datas.add(m.group(1))
            continue
        body.append(l)
    bodies.append((fn, "\n".join(body).strip()))
names = {fn for fn, _ in bodies}


def gpsym(mm):
    typ, off = mm.group(1), int(mm.group(2), 0)
    addr = GP + off
    i = bisect.bisect_right(KEYS, addr) - 1
    a, n = SYMS[i]
    if addr == a and typ.strip().endswith("*"):
        gpdecl[n] = typ.strip()[:-1].strip()
        return n
    datas.add(n)
    if addr == a:
        return "(*(%s)%s)" % (typ, n)
    return "(*(%s)((u8 *)%s + %d))" % (typ, n, addr - a)


outb = []
sigs = []
for fn, b in bodies:
    b = re.sub(r"M2C_FIELD\(saved_reg_gp, ([\w\* ]+?), (-?0x[0-9A-Fa-f]+|-?\d+)\)", gpsym, b)
    b = re.sub(r"&(sp[0-9A-F]+)\b", r"(u8 *)&\1", b)
    b = re.sub(r"^\s*\w+ = \*\(\(\w+ \* 4\) \+ &jtbl_\w+\);\n", "", b, flags=re.M)
    b = re.sub(r", &jtbl_\w+(, \w+)*\)", ")", b)
    for d in sorted(datas):
        b = re.sub(r"&%s\b" % re.escape(d), d, b)
    b = b.replace("void **", "u8 **").replace("void *", "u8 *").replace("M2C_UNK", "int")
    m = re.search(r"^([\w \*]+?\b)%s\([^)]*\) \{$" % re.escape(fn), b, re.M)
    if m:
        sigs.append(m.group(1) + fn + "();")
    outb.append(b)

_joined = "\n".join(outb)
ptrgp = {g for g in gpdecl if re.search(r"M2C_FIELD\(%s,|\b%s \+ |\(%s \+" % (g, g, g), _joined)}
for i, b in enumerate(outb):
    for g in sorted(ptrgp):   # temps that receive a gp pointer variable become u8 *
        for t in set(re.findall(r"\b(\w+) = %s;" % re.escape(g), b)):
            b = re.sub(r"^(\s*)(?:(?:s32|int|u32|s64) |(?:u8|int|s32) \*)%s;$" % re.escape(t), r"\1u8 *%s;" % t, b, flags=re.M)
    outb[i] = b

print("/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */")
print('#include "%s.h"\n' % module)
for p in sorted(protos - names - LIBC):
    print("int %s();" % p)
for d in sorted(datas - names - protos - set(gpdecl)):
    print("extern u8 %s[];" % d)
for d, t in sorted(gpdecl.items()):
    if d in ptrgp:
        t = "u8 *"
    print("extern %s %s;" % (t.replace("void", "u8").replace("int", "s32"), d))
print()
for s in sigs:
    print(s)
print()
for b in outb:
    print(b)
    print()
