#!/usr/bin/env python3
"""gen_rt_auto.py - definitions for the symbols the PC build still lacks.

The PC port links decompiled overlay C (the lobby/village code, src/lobby)
whose callees and data are not all ported. tools/build_pc.sh links once
with unresolved symbols allowed, collects the names the linker reports,
and this tool writes a C file that defines each one:

- data (a sized symbol of config/symbols/main.txt or lobby.txt, or an
  unnamed D_<addr> / lit_<n>_<addr>): an empty array of the symbol's size
  plus an entry in rt_gen_main_tables / rt_gen_lb_tables; rt_data.c fills
  it at start-up from the user's own SLPM_654.95 / lobby.bin (zeros for
  .bss) and turns its pointer words into host pointers;
- functions: a weak stand-in that returns 0 and, with RT_TRACE=1, says
  once that it ran ("rt: <name> not ported").

    python3 tools/gen_rt_auto.py undefined.txt out.c

Only names, addresses and sizes are involved; the output holds no game
data. Standard library only.
"""
import re
import sys

LINE = re.compile(r"^(\w+) = 0x([0-9A-Fa-f]+);(?:\s*//\s*(?:type:(\w+))?\s*(?:size:0x([0-9A-Fa-f]+))?)?")
OVL = 0x533980


def load(path):
    out = {}
    for line in open(path):
        m = LINE.match(line)
        if m and m.group(1) not in out:
            out[m.group(1)] = (int(m.group(2), 16), m.group(3) or "data", int(m.group(4) or "0", 16))
    return out


def gap_size(addrs, va, cap=0x1000):
    """bytes from va to the next symbol address (for unsized data)"""
    nxt = [a for a in addrs if a > va]
    n = (min(nxt) - va) if nxt else 4
    return max(4, min(n, cap))


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_rt_auto.py undefined.txt out.c")
    main_s = load("config/symbols/main.txt")
    lb_s = load("config/symbols/lobby.txt")
    main_addrs = sorted(v[0] for v in main_s.values())
    lb_addrs = sorted(v[0] for v in lb_s.values() if v[0] >= OVL)
    names = sorted(set(l.strip() for l in open(sys.argv[1]) if l.strip()))
    data, funcs = [], []
    for n in names:
        ent = None
        if n in main_s and main_s[n][0] < OVL:
            ent = ("main",) + main_s[n]
        elif n in lb_s:
            ent = ("lb",) + lb_s[n]
        else:
            m = re.match(r"^(?:D|lit_\d+)_([0-9A-Fa-f]{6,8})$", n)
            if m:
                va = int(m.group(1), 16)
                ent = ("main" if va < OVL else "lb", va, "data", 0)
        if ent is None or ent[2] == "func":
            funcs.append(n)
            continue
        img, va, _, size = ent
        if not size:
            size = gap_size(main_addrs if img == "main" else lb_addrs, va)
        data.append((img, n, va, size))
    out = ["/* Generated by tools/gen_rt_auto.py for the PC build. Do not edit. */",
           "#include <stddef.h>", "#include <stdint.h>", "#include <stdio.h>", "#include <stdlib.h>", "",
           "struct rt_table { const char *name; uint32_t va; void *dst; size_t size; };", ""]
    for img, n, va, size in data:
        out.append("uint8_t %s[0x%X] __attribute__((aligned(16)));   /* %s 0x%08X */" % (n, size, img, va))
    for img in ("main", "lb"):
        out += ["", "const struct rt_table rt_gen_%s_tables[] = {" % img]
        for i, n, va, size in data:
            if i == img:
                out.append("    { \"%s\", 0x%08X, %s, 0x%X }," % (n, va, n, size))
        out += ["    { NULL, 0, NULL, 0 }", "};"]
    out += ["", "static void note(const char *n)", "{",
            "    if (getenv(\"RT_TRACE\"))",
            "        fprintf(stderr, \"rt: %s not ported (stand-in returns 0)\\n\", n);", "}"]
    for n in funcs:
        out.append("__attribute__((weak)) int %s() { static int o; if (!o++) note(\"%s\"); return 0; }" % (n, n))
    open(sys.argv[2], "w").write("\n".join(out) + "\n")
    print("gen_rt_auto: %d data, %d function stand-ins" % (len(data), len(funcs)))


if __name__ == "__main__":
    main()
