#!/usr/bin/env python3
"""gen_rt_auto.py - definitions for the symbols the PC build still lacks.

The PC port links decompiled overlay C (the lobby/village code, src/lobby)
whose callees and data are not all ported. tools/build_pc.sh links once
with unresolved symbols allowed, collects the names the linker reports,
and this tool writes a C file that defines each one:

- main data (a sized symbol of config/symbols/main.txt, or an unnamed
  D_<addr>): an empty array of the symbol's size plus an entry in
  rt_gen_main_tables; rt_data.c fills it at start-up from the user's own
  SLPM_654.95 (zeros for .bss) and turns its pointer words into host
  pointers;
- lobby.bin data (lobby.txt symbols, D_ / lit_ names in its range): a
  linker alias into rt_lb_mem, the host copy of the whole overlay (image +
  .bss, filled from lobby.bin by rt_import_lobby), so tables the code reads
  past their symbol's end see the same neighbours as on the PS2;
- select.bin data (select.txt symbols): the same, into rt_sel_mem;
- functions: a weak stand-in that returns 0 and, with RT_TRACE=1, says
  once that it ran ("rt: <name> not ported").

An unnamed D_<addr> that lies inside a sized symbol (D_3E55F0 =
player_work + 0xA00) becomes a linker alias of that symbol instead
(out.defsym, one `--defsym` option per line), and that symbol is defined
here too when nothing else defines it.

    python3 tools/gen_rt_auto.py undefined.txt defined.txt out.c out.defsym

Only names, addresses and sizes are involved; the output holds no game
data. Standard library only.
"""
import re
import sys

LINE = re.compile(r"^(\w+) = 0x([0-9A-Fa-f]+);(?:\s*//\s*(?:type:(\w+))?\s*(?:size:0x([0-9A-Fa-f]+))?)?")
OVL = 0x533980


def load(path):
    out = {}
    for line in open(path):
        m = LINE.match(line)
        if m and m.group(1) not in out:
            out[m.group(1)] = (int(m.group(2), 16), m.group(3) or "data", int(m.group(4) or "0", 16))
    return out


def gap_size(addrs, va, cap=0x1000):
    """bytes from va to the next symbol address (for unsized data)"""
    nxt = [a for a in addrs if a > va]
    n = (min(nxt) - va) if nxt else 4
    return max(4, min(n, cap))


def main():
    if len(sys.argv) != 5:
        sys.exit("usage: gen_rt_auto.py undefined.txt defined.txt out.c out.defsym")
    defined = set(l.strip() for l in open(sys.argv[2]))
    main_s = load("config/symbols/main.txt")
    lb_s = load("config/symbols/lobby.txt")
    sel_s = load("config/symbols/select.txt")
    main_addrs = sorted(v[0] for v in main_s.values())
    lb_addrs = sorted(v[0] for v in lb_s.values() if v[0] >= OVL)
    names = set(l.strip() for l in open(sys.argv[1]) if l.strip())
    # D_<addr> inside a sized symbol: alias (defsym) to that symbol + offset
    sized = sorted((v[0], v[2], k, "main" if v[0] < OVL else "lb")
                   for src in (main_s, lb_s) for k, v in src.items() if v[1] != "func" and v[2])
    alias = {}
    for n in sorted(names):
        m = re.match(r"^D_([0-9A-Fa-f]{6,8})$", n)
        if not m:
            continue
        va = int(m.group(1), 16)
        if va >= OVL:
            continue        # lobby.bin: an alias into rt_lb_mem below
        for a, size, k, img in sized:
            if a <= va < a + size and k != n and (img == "main") == (va < OVL):
                alias[n] = (k, va - a)
                break
    for n, (k, off) in alias.items():
        names.discard(n)
        if k not in defined:
            names.add(k)
    names = sorted(names)
    data, funcs, lbalias, selalias = [], [], {}, {}
    for n in names:
        ent = None
        if n in sel_s and sel_s[n][1] != "func" and n not in lb_s and n not in main_s:
            selalias[n] = sel_s[n][0] - OVL     # select.bin data: alias into rt_sel_mem
            continue
        if n in main_s and main_s[n][0] < OVL:
            ent = ("main",) + main_s[n]
        elif n in lb_s:
            ent = ("lb",) + lb_s[n]
        else:
            m = re.match(r"^(?:D|lit_\d+)_([0-9A-Fa-f]{6,8})$", n)
            if m:
                va = int(m.group(1), 16)
                ent = ("main" if va < OVL else "lb", va, "data", 0)
        if ent is None or ent[2] == "func":
            funcs.append(n)
            continue
        img, va, _, size = ent
        if img == "lb":
            lbalias[n] = va - OVL
            continue
        if not size:
            size = gap_size(main_addrs if img == "main" else lb_addrs, va)
        data.append((img, n, va, size))
    out = ["/* Generated by tools/gen_rt_auto.py for the PC build. Do not edit. */",
           "#include <stddef.h>", "#include <stdint.h>", "#include <stdio.h>", "#include <stdlib.h>", "",
           "struct rt_table { const char *name; uint32_t va; void *dst; size_t size; };", ""]
    for img, n, va, size in data:
        out.append("uint8_t %s[0x%X] __attribute__((aligned(16)));   /* %s 0x%08X */" % (n, size, img, va))
    for img in ("main",):
        out += ["", "const struct rt_table rt_gen_%s_tables[] = {" % img]
        for i, n, va, size in data:
            if i == img:
                out.append("    { \"%s\", 0x%08X, %s, 0x%X }," % (n, va, n, size))
        out += ["    { NULL, 0, NULL, 0 }", "};"]
    out += ["", "static void note(const char *n)", "{",
            "    if (getenv(\"RT_TRACE\"))",
            "        fprintf(stderr, \"rt: %s not ported (stand-in returns 0)\\n\", n);", "}"]
    for n in funcs:
        out.append("__attribute__((weak)) int %s() { static int o; if (!o++) note(\"%s\"); return 0; }" % (n, n))
    open(sys.argv[3], "w").write("\n".join(out) + "\n")
    open(sys.argv[4], "w").write("".join("-Wl,--defsym,%s=%s+0x%X\n" % (n, k, off) for n, (k, off) in sorted(alias.items())) +
                                 "".join("-Wl,--defsym,%s=rt_lb_mem+0x%X\n" % (n, off) for n, off in sorted(lbalias.items())) +
                                 "".join("-Wl,--defsym,%s=rt_sel_mem+0x%X\n" % (n, off) for n, off in sorted(selalias.items())))
    print("gen_rt_auto: %d data, %d function stand-ins, %d aliases, %d lobby.bin symbols, %d select.bin symbols" % (len(data), len(funcs), len(alias), len(lbalias), len(selalias)))


if __name__ == "__main__":
    main()
