#!/usr/bin/env python3
"""gen_rt_tables.py - generate the port runtime's data-table file.

The decompiled game C reads many small Capcom data tables. The port never
copies their bytes into the repo: each table is defined empty and filled
at start-up from the user's own SLPM_654.95 / game.bin by address
(src/pc/rt/rt_data.c, rt_import_data).

This tool reads a list of symbol names (src/pc/rt/tables.txt), looks up
each one's address and size in config/symbols/main.txt / game.txt, and
writes a C file defining them plus the import list:

    python3 tools/gen_rt_tables.py src/pc/rt/tables.txt build/pc/rt_tables.c

tables.txt: one name per line; `#` starts a comment. A line
`NAME work` defines a zeroed work area of the symbol's size that is not
imported (RAM the game fills at run time, e.g. em_work).

Only names and addresses are involved here; the output holds no game data.
Standard library only.
"""
import re
import sys

SYMFILES = ("config/symbols/main.txt", "config/symbols/game.txt")
LINE = re.compile(r"^(\S+) = 0x([0-9A-Fa-f]+); // (?:type:\S+ )?size:0x([0-9A-Fa-f]+)")


def load_symbols():
    syms = {}
    for path in SYMFILES:
        with open(path) as f:
            for line in f:
                m = LINE.match(line)
                if m and m.group(1) not in syms:
                    syms[m.group(1)] = (int(m.group(2), 16), int(m.group(3), 16))
    return syms


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_rt_tables.py tables.txt out.c")
    syms = load_symbols()
    entries = []
    for raw in open(sys.argv[1]):
        line = raw.split("#", 1)[0].split()
        if not line:
            continue
        name, work = line[0], len(line) > 1 and line[1] == "work"
        if name not in syms:
            sys.exit("gen_rt_tables: %s not in %s" % (name, " / ".join(SYMFILES)))
        entries.append((name, syms[name][0], syms[name][1], work))
    out = ["/* Generated by tools/gen_rt_tables.py from src/pc/rt/tables.txt. Do not edit. */",
           "#include <stddef.h>", "#include <stdint.h>", "",
           "struct rt_table { const char *name; uint32_t va; void *dst; size_t size; };", ""]
    for name, va, size, work in entries:
        out.append("uint8_t %s[0x%X] __attribute__((aligned(16)));   /* 0x%08X%s */"
                   % (name, size, va, " work area" if work else ""))
    out += ["", "const struct rt_table rt_auto_tables[] = {"]
    for name, va, size, work in entries:
        if not work:
            out.append('    { "%s", 0x%X, %s, 0x%X },' % (name, va, name, size))
    out += ["    { NULL, 0, NULL, 0 }", "};", ""]
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
