#!/usr/bin/env python3
"""gen_symtab.py - the host symbol table rt_data.c looks names up in
(rt_host_sym), instead of dlsym on a -rdynamic binary (no dlsym on the Xbox).

    nm --defined-only -g FILE... | python3 tools/gen_symtab.py OUT.c [--prefix _]

Every defined global name (functions and data) becomes an entry
{ "name", address }, sorted for a binary search. --prefix strips the C
symbol prefix of the target (COFF i386: "_"). Standard library only.
"""
import re, sys

def main():
    out = sys.argv[1]
    pfx = sys.argv[sys.argv.index('--prefix') + 1] if '--prefix' in sys.argv else ''
    names = set()
    for l in sys.stdin:
        p = l.split()
        if len(p) < 3 or p[-2] not in 'TDBRWVGSCtdbr' or p[-2].islower():
            continue
        n = p[-1]
        if pfx:
            if not n.startswith(pfx):
                continue
            n = n[len(pfx):]
        if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', n) or n.startswith('__') or n in ('main', 'rt_symtab', 'rt_symtab_n', 'rt_host_sym', 'rt_host_symname'):
            continue
        names.add(n)
    names = sorted(names)
    with open(out, 'w') as f:
        f.write('/* generated by tools/gen_symtab.py: host symbols by name for rt_data.c */\n')
        f.write('#include <string.h>\n#include <stdlib.h>\n')
        for n in names:
            f.write('extern char %s[];\n' % n)
        f.write('static const struct { const char *n; void *p; } rt_symtab[] = {\n')
        for n in names:
            f.write('    { "%s", %s },\n' % (n, n))
        f.write('    { 0, 0 }\n};\n')
        f.write('''static int cmp(const void *k, const void *e) { return strcmp((const char *)k, *(const char *const *)e); }
void *rt_host_sym(const char *name)
{
    const void *e = bsearch(name, rt_symtab, %d, sizeof rt_symtab[0], cmp);
    return e ? ((void *const *)e)[1] : 0;
}
/* the symbol at or just before addr (the debug log's crash backtrace, rt_log.c); NULL when none within 8 KB */
const char *rt_host_symname(const void *addr, unsigned *off)
{
    size_t i, best = (size_t)-1;
    unsigned long long a = (unsigned long long)(size_t)addr, bv = 0;
    for (i = 0; i < %d; i++) {
        unsigned long long v = (unsigned long long)(size_t)rt_symtab[i].p;
        if (v <= a && v >= bv) { bv = v; best = i; }
    }
    if (best == (size_t)-1 || a - bv > 0x2000)
        return 0;
    if (off) *off = (unsigned)(a - bv);
    return rt_symtab[best].n;
}
''' % (len(names), len(names)))
    print('gen_symtab: %d names' % len(names))

if __name__ == '__main__':
    main()
