#!/usr/bin/env python3
"""lbctx.py OUT.h : write a C context file (for m2c --context, draft.py reads DRAFT_CTX) with an int-only prototype for every
function called from the lobby asm, with the largest argument count seen at any call site (registers a0-a3/t0-t3 written
in the straight-line window before the jal, plus argument stores at 0..0x30(sp)). m2c then prints every argument of a call
instead of dropping pass-through registers."""
import sys, os, re, glob, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = {'$4': 1, '$5': 2, '$6': 3, '$7': 4, '$8': 5, '$9': 6, '$10': 7, '$11': 8}
need = collections.defaultdict(int)
sites = collections.defaultdict(list)  # name -> list of (n_reg_args_a, n_with_t, t_near)
DEST = re.compile(r'^(addiu|daddiu|addu|daddu|subu|dsubu|andi|ori|xori|lui|lw|lwu|lh|lhu|lb|lbu|ld|sll|srl|sra|dsll|dsll32|dsra|dsra32|dsrl|or|and|xor|nor|negu|slt|sltu|slti|sltiu|move|mfc1|mflo|mfhi|li)\s+(\$\d+),')
for path in glob.glob(os.path.join(ROOT, 'asm/lobby/text/*.s')):
    lines = open(path).read().split('\n')
    win = []  # (kind, value)
    for l in lines:
        m = re.match(r'\s*/\* \w+ \w+ \w+ \*/\s+(\S+)\s*(.*)', l)
        if not m:
            if re.match(r'\s*(\.L\w+:|glabel )', l): win = []
            continue
        op, rest = m.group(1), m.group(2)
        rest = re.sub(r'/\*.*?\*/', '', rest).strip()
        if op in ('jal', 'jalr', 'j'):
            name = rest.split()[0] if op != 'jalr' else None
            if name and not name.startswith('.') and not name.startswith('$'):
                n = 0; offs = set()
                for kind, v in win[-24:]:
                    if kind == 'r': n = max(n, v)
                    elif kind == 's': offs.add(v)
                near = [v for kind, v in win[-8:] if kind == 'r']
                na = max([v for v in near if v <= 4] + [0])
                nt = max([v for v in near if v >= 5] + [0])
                sites[name].append((n if n <= 4 else min(n, 4), nt))
                need[name] = max(need[name], min(n, 4))
            # delay slot is the next line: handled by keeping window (do not reset)
            win = win[-0:] if op == 'j' else []
            continue
        if op.startswith('b') or op in ('j',):
            continue
        d = DEST.match(op + ' ' + rest)
        if d and d.group(2) in REG:
            win.append(('r', REG[d.group(2)]))
        s = re.match(r'(sd|sw|sq|sb|sh)\s+\$\d+,\s*(0x[0-9A-Fa-f]+|\d+)\(\$29\)', op + ' ' + rest)
        if s:
            off = int(s.group(2), 0)
            if off <= 0x30 and off % 8 == 0: win.append(('s', off))
FIXED = {'memcpy': 3, 'memset': 3, 'memcmp': 3, 'strcpy': 2, 'strcat': 2, 'strlen': 1, 'strncmp': 3, 'strncpy': 3, 'strcmp': 2, 'flMemcpy': 3, 'flMemset': 3, 'strchr': 2, 'strrchr': 2, 'strstr': 2, 'atoi': 1, 'abs': 1}
VARIADIC = {'sprintf': 2, 'printf': 1, 'snprintf': 3, 'sscanf': 2}
out = ['/* generated by tools/lbctx.py */']
for name, L in sites.items():
    big = [nt for na, nt in L if nt >= 5]
    if len(L) >= 2 and len(big) * 10 >= len(L) * 6:
        need[name] = max(need[name], min(max(big), 8))
for k, n in FIXED.items(): need[k] = n
for name, n in sorted(need.items()):
    if re.match(r'^(lit_|jtbl|D_)', name): continue
    if name in VARIADIC:
        out.append('int %s(%s, ...);' % (name, ', '.join('int arg%d' % i for i in range(VARIADIC[name]))))
        continue
    out.append('int %s(%s);' % (name, ', '.join('int arg%d' % i for i in range(n)) if n else 'void'))
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
print(len(out) - 1, 'prototypes')
