#!/usr/bin/env python3
"""pc_link_adapt.py - link adaptors for the PC (and Xbox) build without
GNU-only linker tricks.

The PC build used to weaken symbols with `objcopy --weaken-symbol` (so a
matched copy of a function wins over a near-match copy, or the host's
replacement wins) and to alias PS2 data addresses with `ld --defsym
D_xxxx=table+off`. Neither works with lld-link (COFF) for the Xbox. Instead
each affected object gets a generated header, force-included when it is
compiled again:
  - `#pragma weak NAME` for each symbol to weaken (gcc and clang, ELF and
    COFF: the definition becomes weak, references in the file go to the
    winner, as with objcopy);
  - for an alias D = TARGET + off, an assembler `.set` in the object that
    defines TARGET (an alias of an undefined symbol is not possible in COFF).

    python3 tools/pc_link_adapt.py REQUESTS [--lenient]
REQUESTS: lines "weak OBJ SYMBOL" and "alias SYMBOL TARGET OFFSET" (TARGET's
defining object is found with nm). Each object's compile command is in
build/pc/cmd/<obj>.sh (written by tools/build_pc.sh). An object is compiled
again when its header changed. Standard library only.
"""
import os, subprocess, sys

def nm_defs(objs, nm):
    """symbol -> object for strong global definitions (first wins)"""
    out = {}
    for o in objs:
        r = subprocess.run([nm, '--defined-only', '-g', o], capture_output=True, text=True).stdout
        for l in r.splitlines():
            p = l.split()
            if len(p) == 3 and p[1] in 'TDBRCGS':
                out.setdefault(p[2].lstrip('_') if nm_prefix else p[2], o)
    return out

nm_prefix = False

def main():
    global nm_prefix
    req = sys.argv[1]
    nm = os.environ.get('NM', 'nm')
    nm_prefix = os.environ.get('SYM_PREFIX', '') == '_'
    weak, alias = {}, []
    for l in open(req):
        p = l.split()
        if not p:
            continue
        if p[0] == 'weak':
            weak.setdefault(p[1], set()).add(p[2])
        elif p[0] == 'alias':
            a = (p[1], p[2], int(p[3], 0))
            if a not in alias:
                alias.append(a)
    objs = sorted(set(os.path.join('build/pc', f) for f in os.listdir('build/pc') if f.endswith('.o')))
    defs = nm_defs(objs, nm) if alias else {}
    hdr = {}
    for o, syms in weak.items():
        hdr.setdefault(o, []).extend('#pragma weak %s' % s for s in sorted(syms))
    missing = 0
    for s, t, off in alias:
        o = defs.get(t)
        if not o:
            if '--lenient' not in sys.argv:     # first pass: the generated tables may not exist yet
                print('pc_link_adapt: no definition of %s for alias %s' % (t, s), file=sys.stderr)
                missing += 1
            continue
        hdr.setdefault(o, []).append(
            '__asm__(".globl " RTLA_P "%s\\n.set " RTLA_P "%s, " RTLA_P "%s + %d");' % (s, s, t, off))
    os.makedirs('build/pc/adapt', exist_ok=True)
    redo = []
    for o in objs:
        b = os.path.basename(o)[:-2]
        h = 'build/pc/adapt/%s.h' % b
        lines = hdr.get(o)
        text = None
        if lines:
            text = ('/* generated by tools/pc_link_adapt.py */\n'
                    '#define RTLA_S_(x) #x\n#define RTLA_S(x) RTLA_S_(x)\n#define RTLA_P RTLA_S(__USER_LABEL_PREFIX__)\n'
                    + '\n'.join(lines) + '\n')
        old = open(h).read() if os.path.exists(h) else None
        if text != old:
            if text is None:
                os.remove(h)
            else:
                open(h, 'w').write(text)
            redo.append((o, b, text is not None))
    for o, b, has in redo:
        cmd = 'build/pc/cmd/%s.sh' % b
        if not os.path.exists(cmd):
            print('pc_link_adapt: no compile command for %s' % o, file=sys.stderr)
            sys.exit(1)
        c = open(cmd).read().strip()
        if has:
            c += ' -include build/pc/adapt/%s.h' % b
        if subprocess.run(c, shell=True).returncode != 0:
            print('pc_link_adapt: %s failed' % c, file=sys.stderr)
            sys.exit(1)
    if redo:
        print('pc_link_adapt: %d objects compiled again: %s' % (len(redo), ' '.join(r[1] for r in redo[:8])))
    sys.exit(1 if missing else 0)

if __name__ == '__main__':
    main()
