#!/usr/bin/env python3
"""
setup_split.py - generate the splat inputs for MH1's main executable and its
game overlays (select.bin, game.bin, yn.bin, lobby.bin).

Reads the user's own SLPM_654.95, AFS_DATA.AFS and the symbol CSV made by
elf_survey.py, and writes:

  disc/mh1/split/<module>.bin   the bytes to match (gitignored game data):
                                main = the ELF's 'main' section, overlays =
                                the MWo3 file (0x40 header + text + data)
  config/symbols/<module>.txt   FUNC/OBJECT symbols, names unique across all
                                modules (duplicate statics get _ADDRESS)
  config/<module>.yaml          splat config

The DNAS overlays (dnas_net, dnas_ins) are Sony network security code that
gets replaced, not ported, so they are not split.

Decompiled code is listed in config/c_files.txt as
    MODULE START END NAME        -> src/MODULE/NAME.c
and the asm around each range is cut so the C object drops in its place.

Nothing written to config/ contains game bytes, only names and addresses.

Usage:
    python3 tools/setup_split.py
    for m in main select game yn lobby; do
        .venv/bin/python -m splat split config/$m.yaml; done
"""
import csv
import hashlib
import os
import re
import struct
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ELF = os.path.join(ROOT, "disc/mh1/SLPM_654.95")
AFS = os.path.join(ROOT, "disc/mh1/AFS_DATA.AFS")
CSV = os.path.join(ROOT, "docs/survey/mh1_symbols.csv")
OUT = os.path.join(ROOT, "disc/mh1/split")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mwo_unpack import afs_entries, unpack, describe  # noqa: E402

GP = 0x0038EB70          # _gp, shared by main and the overlays
OVERLAYS = ["select", "game", "yn", "lobby"]

# Layout of 'main' as virtual addresses, worked out from SECTION symbols and
# the program header (docs/STATUS.md).
MAIN = dict(
    vram=0x00100000,
    text_end=0x293B80,       # after reward_itembox + padding; VU1 code follows
    data_start=0x2E5EA0,     # __data_start; VU1 microcode ends here
    sdata_start=0x386B80,    # _gp - 0x7FF0, first small-data object
    file_end=0x38A080,       # FileSiz of the first LOAD segment (_fbss)
    mem_end=0x533980,        # MemSiz of the first LOAD segment
)

YAML = """# Generated by tools/setup_split.py. Target: byte-identical rebuild of
# {what} from SLPM_654.95 (Japanese Monster Hunter).
name: Monster Hunter (JP) {module}
sha1: {sha1}
options:
  basename: {module}
  target_path: disc/mh1/split/{module}.bin
  elf_path: build/{module}.elf
  base_path: ..
  platform: ps2
  compiler: MWCCPS2
  symbol_addrs_path: [{symfiles}]
  undefined_funcs_auto_path: config/{module}_undefined_funcs_auto.txt
  undefined_syms_auto_path: config/{module}_undefined_syms_auto.txt
  asm_path: asm/{module}
  src_path: src/{module}
  asset_path: assets/{module}
  build_path: build
  ld_script_path: build/{module}.ld
  gp_value: 0x{gp:08X}
  find_file_boundaries: False
  emit_subalign: False
  mips_abi_gpr: numeric
  section_order: [".text", ".data", ".rodata", ".sdata", ".bss"]
  # ASCII only: spimdisasm writes guessed strings as UTF-8 text, so any
  # Shift-JIS (or floats that decode as half-width kana) would assemble to
  # different bytes. Japanese text stays as raw bytes for now.
  string_encoding: ASCII
  data_string_encoding: ASCII
  create_undefined_funcs_auto: True
  create_undefined_syms_auto: True
segments:
  - name: {module}
    type: code
    start: 0x000000
    vram: 0x{vram:08X}
    bss_size: 0x{bss:X}
    subsegments:
{sub}
  - [0x{end:X}]
"""


def clean(name):
    """Make a symbol name safe for GNU as. '@1234' are MWCC literal labels."""
    name = name.replace("@", "lit_")
    return re.sub(r"[^A-Za-z0-9_.$]", "_", name)


def elf_section(name):
    data = open(ELF, "rb").read()
    shoff, = struct.unpack_from("<I", data, 32)
    shnum, shstrndx = struct.unpack_from("<HH", data, 48)
    secs = [struct.unpack_from("<10I", data, shoff + i * 40) for i in range(shnum)]
    st = secs[shstrndx]
    names = data[st[4]:st[4] + st[5]]
    for s in secs:
        if names[s[0]:names.index(b"\0", s[0])] == name.encode():
            return s[3], data[s[4]:s[4] + s[5]]
    sys.exit("no %r section" % name)


def overlay_modules():
    """MWo3 modules from AFS_DATA.AFS, keyed by short name ('game')."""
    mods = {}
    for blob in afs_entries(AFS):
        if blob[:4] != b"MWo3" and blob[2:6] != b"MWo3":
            continue
        mod, _packed = unpack(blob)
        h = describe(mod)
        mods[h["name"].rsplit(".", 1)[0]] = (mod, h)
    return mods


def symbol_names(rows):
    """Unique, assembler-safe names for every (section, addr, name) row.
    Static functions and variables reuse names across files (sound_call x25)
    and overlays share a load address, so the same name can appear many
    times. Globals keep their name the first time; everything else that
    collides gets an _ADDRESS suffix."""
    counts = Counter(clean(r["name"]) for r in rows)
    seen, names = set(), {}
    order = sorted(rows, key=lambda r: (r["bind"] != "GLOBAL", r["section"] != "main",
                                        int(r["addr"], 16)))
    for r in order:
        name = clean(r["name"])
        addr = int(r["addr"], 16)
        if counts[name] > 1 and (r["bind"] == "LOCAL" or name in seen):
            name = "%s_%08X" % (name, addr)
        if name in seen:
            name = "%s_%s_%08X" % (clean(r["name"]), r["section"].split(".")[0], addr)
        seen.add(name)
        names[id(r)] = name
    return names


def write_symbols(module, rows, names):
    out = []
    for r in sorted(rows, key=lambda r: int(r["addr"], 16)):
        size = int(r["size"])
        line = "%s = 0x%08X;" % (names[id(r)], int(r["addr"], 16))
        attrs = ["type:func"] if r["type"] == "FUNC" else []
        if size:
            attrs.append("size:0x%X" % size)
        if attrs:
            line += " // " + " ".join(attrs)
        out.append(line)
    os.makedirs(os.path.join(ROOT, "config/symbols"), exist_ok=True)
    with open(os.path.join(ROOT, "config/symbols/%s.txt" % module), "w") as f:
        f.write("// Generated by tools/setup_split.py from SLPM_654.95's symbol table.\n")
        f.write("\n".join(out) + "\n")


def section_starts(all_rows, section, kind, lo, hi):
    return sorted({int(r["addr"], 16) for r in all_rows
                   if r["type"] == "SECTION" and r["section"] == section
                   and r["name"] == kind and lo <= int(r["addr"], 16) < hi})


def text_subsegments(module, section, all_rows, names_by_addr, vram, lo, hi, c_ranges):
    """asm subsegments cut at .text SECTION symbols and around C files."""
    cuts = {lo: ("asm", None)}
    for a in section_starts(all_rows, section, ".text", lo, hi):
        cuts[a] = ("asm", None)
    # Inferred object-file starts (tools/file_bounds.py). Only a hint: cutting
    # asm never changes bytes, so a wrong cut costs nothing but a file name.
    for a, label in inferred_files(module, lo, hi):
        cuts.setdefault(a, ("asm", label))
    for mod, start, end, name in c_ranges:
        if mod != module:
            continue
        # A C file owns its whole range: drop any other cut inside it.
        for a in [a for a in cuts if start < a < end]:
            del cuts[a]
        cuts[start] = ("c", name)
        if end not in cuts and end < hi:
            cuts[end] = ("asm", None)
    sub, used = [], set()
    for a in sorted(cuts):
        kind, name = cuts[a]
        if kind == "c":
            sub.append("      - [0x%06X, c, %s]" % (a - vram, name))
            continue
        first = min((f for f in names_by_addr if a <= f < hi), default=None)
        label = name or names_by_addr.get(first, "text")
        label = "%s_%06X" % (label, a) if label in used else label
        used.add(label)
        sub.append("      - [0x%06X, asm, text/%s]" % (a - vram, label))
    return sub


def inferred_files(module, lo, hi):
    """(start, label) for each inferred file in docs/survey/mh1_<module>_files.csv.
    Files are labelled by their most common function-name prefix (em15,
    eft06, set01...), gaps holding only global functions by their first
    function."""
    path = os.path.join(ROOT, "docs/survey/mh1_%s_files.csv" % module)
    if not os.path.exists(path):
        return []
    out = []
    for r in csv.DictReader(open(path)):
        a = int(r["start"], 16)
        if lo <= a < hi:
            label = clean(r.get("prefix") or r["example"])
            out.append((a, ("f_" if r["kind"] == "file" else "g_") + label))
    return out


def data_subsegments(section, all_rows, vram, lo, hi, prefix):
    """Data keeps the original order. Files are cut at .data/.rodata SECTION
    symbols, which exist for library objects only; Capcom's own data is one
    block before them, like its code. Typing follows those symbols and is
    not checked per object (MWCC also puts string literals in .data)."""
    sub = ["      - [0x%06X, data, data/%s]" % (lo - vram, prefix)]
    ro = section_starts(all_rows, section, ".rodata", lo, hi)
    ro_start = ro[0] if ro else hi
    for a in section_starts(all_rows, section, ".data", lo, ro_start):
        if a != lo:
            sub.append("      - [0x%06X, data, data/data_%06X]" % (a - vram, a))
    for a in ro:
        sub.append("      - [0x%06X, rodata, data/rodata_%06X]" % (a - vram, a))
    return sub


def read_c_ranges():
    """Text lines: MODULE START END NAME.
    Data lines: MODULE:SECTION START END NAME, e.g.
        game:rodata 0x0068A3F0 0x0068A410 shell/shell18
    places that C file's SECTION (its jump tables etc.) at START, replacing
    those bytes of the data asm."""
    ranges, slots = [], []
    cf = os.path.join(ROOT, "config/c_files.txt")
    if os.path.exists(cf):
        for line in open(cf):
            f = line.split("#", 1)[0].split()
            if not f:
                continue
            if ":" in f[0]:
                mod, sec = f[0].split(":")
                slots.append((mod, sec, int(f[1], 0), int(f[2], 0), f[3]))
            else:
                ranges.append((f[0], int(f[1], 0), int(f[2], 0), f[3]))
    return ranges, slots


SUB_RE = re.compile(r"^      - \[0x([0-9A-F]+), (\w+), (\S+)\]$")


def apply_data_slots(module, sub, vram, slots, renames):
    """Cut the data subsegments around each C data slot of `module`."""
    mine = sorted(s for s in slots if s[0] == module)
    if not mine:
        return sub
    parsed = [SUB_RE.match(l).groups() for l in sub]
    items = [(int(o, 16), t, n) for o, t, n in parsed]
    for _m, sec, start, end, name in mine:
        off, eoff = start - vram, end - vram
        k = max(i for i, it in enumerate(items) if it[0] <= off)
        base_off, typ, base_name = items[k]
        if typ not in ("data", "rodata", "sdata"):
            sys.exit("data slot 0x%X for %s is not in a data region" % (start, name))
        new = []
        if base_off < off:
            new.append((base_off, typ, base_name))
        new.append((off, "." + typ, name))
        nxt = items[k + 1][0] if k + 1 < len(items) else None
        if nxt is None or eoff < nxt:
            new.append((eoff, typ, "%s_%06X" % (base_name.rsplit("_", 1)[0]
                                                  if re.search(r"_[0-9A-F]{6}$", base_name)
                                                  else base_name, end)))
        items[k:k + 1] = new
        if sec != typ:
            renames.append("build/src/%s/%s.c.o .%s .%s" % (module, name, sec, typ))
    return ["      - [0x%06X, %s, %s]" % it for it in items]


def write_yaml(module, what, blob, symfiles, vram, bss, sub):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, module + ".bin"), "wb") as f:
        f.write(blob)
    text = YAML.format(what=what, module=module, sha1=hashlib.sha1(blob).hexdigest(),
                       symfiles=", ".join("config/symbols/%s.txt" % s for s in symfiles),
                       gp=GP, vram=vram, bss=bss, sub="\n".join(sub), end=len(blob))
    with open(os.path.join(ROOT, "config/%s.yaml" % module), "w") as f:
        f.write(text)


def main():
    all_rows = list(csv.DictReader(open(CSV, encoding="utf-8")))
    sections = ["main"] + ["%s.bin" % o for o in OVERLAYS]
    rows = [r for r in all_rows if r["type"] in ("FUNC", "OBJECT") and r["name"]
            and r["section"] in sections]
    names = symbol_names(rows)
    c_ranges, slots = read_c_ranges()
    renames = []

    def funcs_of(section):
        d = {}
        for r in rows:
            if r["type"] == "FUNC" and r["section"] == section:
                d.setdefault(int(r["addr"], 16), names[id(r)])
        return d

    # main
    m = MAIN
    vram, blob = elf_section("main")
    assert vram == m["vram"] and len(blob) == m["file_end"] - vram, "unexpected main layout"
    write_symbols("main", [r for r in rows if r["section"] == "main"
                           and vram <= int(r["addr"], 16) < m["mem_end"]], names)
    sub = text_subsegments("main", "main", all_rows, funcs_of("main"), vram,
                           vram, m["text_end"], c_ranges)
    sub.append("      - [0x%06X, bin, vu1_code]" % (m["text_end"] - vram))
    sub += data_subsegments("main", all_rows, vram, m["data_start"], m["sdata_start"],
                            "game_data")
    sub.append("      - [0x%06X, sdata, data/sdata]" % (m["sdata_start"] - vram))
    sub = apply_data_slots("main", sub, vram, slots, renames)
    write_yaml("main", "the 'main' section", blob, ["main"], vram,
               m["mem_end"] - m["file_end"], sub)
    print("main      %8d bytes" % len(blob))

    # overlays: 0x40-byte MWo3 header, text, data; bss after.
    mods = overlay_modules()
    for ov in OVERLAYS:
        blob, h = mods[ov]
        section = ov + ".bin"
        vram, text_lo = h["load"], h["load"] + 0x40
        data_lo = text_lo + h["text"]
        data_hi = data_lo + h["data"]
        assert len(blob) == 0x40 + h["text"] + h["data"], ov
        write_symbols(ov, [r for r in rows if r["section"] == section], names)
        sub = ["      - [0x000000, textbin, header]"]
        sub += text_subsegments(ov, section, all_rows, funcs_of(section), vram,
                                text_lo, data_lo, c_ranges)
        sub += data_subsegments(section, all_rows, vram, data_lo, data_hi, ov + "_data")
        sub = apply_data_slots(ov, sub, vram, slots, renames)
        write_yaml(ov, "overlay %s (from AFS_DATA.AFS)" % section, blob,
                   ["main", ov], vram, h["bss"], sub)
        print("%-9s %8d bytes" % (ov, len(blob)))
    with open(os.path.join(ROOT, "config/c_renames.txt"), "w") as f:
        f.write("# Generated by setup_split.py: section renames applied to C objects\n"
                "# whose data slot sits in a differently typed region.\n")
        f.write("".join(r + "\n" for r in renames))


if __name__ == "__main__":
    main()
