#!/usr/bin/env python3
"""
setup_split.py - generate the splat inputs for MH1's main executable.

Reads the user's own SLPM_654.95 and the symbol CSV made by elf_survey.py,
and writes:

  disc/mh1/main.bin            the loadable bytes of the 'main' section
                               (game data: stays in gitignored disc/)
  config/symbol_addrs.txt      every FUNC/OBJECT symbol in main, with sizes
  config/mh1_main.yaml         splat config, one asm subsegment per original
                               object file where the symbol table shows one

Nothing written to config/ contains game bytes, only names and addresses.

Usage:
    python3 tools/setup_split.py
    .venv/bin/python -m splat split config/mh1_main.yaml
"""
import csv
import hashlib
import os
import re
import struct
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ELF = os.path.join(ROOT, "disc/mh1/SLPM_654.95")
CSV = os.path.join(ROOT, "docs/survey/mh1_symbols.csv")

VRAM = 0x00100000
# Layout of 'main' as virtual addresses, worked out from SECTION symbols and
# the program header (docs/STATUS.md).
TEXT_END = 0x293B80     # after reward_itembox + padding; VU1 code follows
DATA_START = 0x306640   # first .data SECTION symbol
FILE_END = 0x38A080     # FileSiz of the first LOAD segment (_fbss)
MEM_END = 0x533980      # MemSiz of the first LOAD segment
GP = 0x0038EB70         # _gp


def read_main():
    data = open(ELF, "rb").read()
    shoff, = struct.unpack_from("<I", data, 32)
    shnum, shstrndx = struct.unpack_from("<HH", data, 48)
    secs = [struct.unpack_from("<10I", data, shoff + i * 40) for i in range(shnum)]
    st = secs[shstrndx]
    names = data[st[4]:st[4] + st[5]]
    for s in secs:
        if names[s[0]:names.index(b"\0", s[0])] == b"main":
            assert s[3] == VRAM and s[5] == FILE_END - VRAM, "unexpected main layout"
            return data[s[4]:s[4] + s[5]]
    sys.exit("no 'main' section")


def clean(name):
    """Make a symbol name safe for GNU as. '@1234' are MWCC literal labels."""
    name = name.replace("@", "lit_")
    return re.sub(r"[^A-Za-z0-9_.$]", "_", name)


def main():
    blob = read_main()
    with open(os.path.join(ROOT, "disc/mh1/main.bin"), "wb") as f:
        f.write(blob)
    sha1 = hashlib.sha1(blob).hexdigest()

    rows = [r for r in csv.DictReader(open(CSV, encoding="utf-8"))
            if r["section"] == "main" and r["type"] in ("FUNC", "OBJECT")
            and VRAM <= int(r["addr"], 16) < MEM_END and r["name"]]
    counts = Counter(clean(r["name"]) for r in rows)
    seen, out = set(), []
    for r in sorted(rows, key=lambda r: int(r["addr"], 16)):
        addr, size = int(r["addr"], 16), int(r["size"])
        name = clean(r["name"])
        # Static functions and variables reuse names across files (sound_call
        # x25). Keep globals as-is, suffix duplicate locals with the address.
        if counts[name] > 1 and (r["bind"] == "LOCAL" or name in seen):
            name = "%s_%08X" % (name, addr)
        if name in seen:
            continue
        seen.add(name)
        line = "%s = 0x%08X;" % (name, addr)
        attrs = ["type:func"] if r["type"] == "FUNC" else []
        if size:
            attrs.append("size:0x%X" % size)
        if attrs:
            line += " // " + " ".join(attrs)
        out.append(line)
    os.makedirs(os.path.join(ROOT, "config"), exist_ok=True)
    with open(os.path.join(ROOT, "config/symbol_addrs.txt"), "w") as f:
        f.write("// Generated by tools/setup_split.py from SLPM_654.95's symbol table.\n")
        f.write("\n".join(out) + "\n")

    # Original object boundaries inside .text, from STT_SECTION '.text' symbols.
    all_rows = list(csv.DictReader(open(CSV, encoding="utf-8")))
    starts = sorted({int(r["addr"], 16) for r in all_rows
                     if r["type"] == "SECTION" and r["section"] == "main"
                     and r["name"] == ".text"})
    starts = [a for a in starts if VRAM <= a < TEXT_END]
    funcs = {}
    for r in all_rows:
        if r["type"] == "FUNC" and r["section"] == "main":
            funcs.setdefault(int(r["addr"], 16), clean(r["name"]))
    # Decompiled ranges: config/c_files.txt lines "START END src_name", e.g.
    # "0x00152030 0x00152044 pl/pl_stg_ck_tw" -> src/pl/pl_stg_ck_tw.c.
    # The asm around each range is cut so the C object drops in its place.
    c_ranges = []
    cf = os.path.join(ROOT, "config/c_files.txt")
    if os.path.exists(cf):
        for line in open(cf):
            line = line.split("#", 1)[0].split()
            if line:
                c_ranges.append((int(line[0], 0), int(line[1], 0), line[2]))
    cuts = {}
    for a in starts:
        cuts[a] = ("asm", None)
    for lo, hi, name in c_ranges:
        cuts[lo] = ("c", name)
        if hi not in cuts and hi < TEXT_END:
            cuts[hi] = ("asm", None)
    sub = []
    used = set()
    for a in sorted(cuts):
        kind, name = cuts[a]
        if kind == "c":
            sub.append("      - [0x%06X, c, %s]" % (a - VRAM, name))
            continue
        first = min((f for f in funcs if f >= a), default=None)
        label = funcs.get(first, "text") if first is not None else "text"
        label = "%s_%06X" % (label, a) if label in used else label
        used.add(label)
        sub.append("      - [0x%06X, asm, text/%s]" % (a - VRAM, label))
    sub.append("      - [0x%06X, bin, vu1_code]" % (TEXT_END - VRAM))
    sub.append("      - [0x%06X, bin, data]" % (DATA_START - VRAM))

    yaml = """# Generated by tools/setup_split.py. First milestone: byte-identical rebuild
# of the 'main' section of SLPM_654.95 (Japanese Monster Hunter).
name: Monster Hunter (JP) SLPM_654.95 main
sha1: {sha1}
options:
  basename: mh1_main
  target_path: disc/mh1/main.bin
  elf_path: build/mh1_main.elf
  base_path: ..
  platform: ps2
  compiler: MWCCPS2
  symbol_addrs_path: [config/symbol_addrs.txt]
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  asm_path: asm
  src_path: src
  build_path: build
  ld_script_path: build/mh1_main.ld
  gp_value: 0x{gp:08X}
  find_file_boundaries: False
  emit_subalign: False
  mips_abi_gpr: numeric
  section_order: [".text", ".data", ".rodata", ".bss"]
  string_encoding: SHIFT-JIS
  data_string_encoding: SHIFT-JIS
  create_undefined_funcs_auto: True
  create_undefined_syms_auto: True
segments:
  - name: main
    type: code
    start: 0x000000
    vram: 0x{vram:08X}
    bss_size: 0x{bss:X}
    subsegments:
{sub}
  - [0x{end:X}]
""".format(sha1=sha1, gp=GP, vram=VRAM, bss=MEM_END - FILE_END,
           sub="\n".join(sub), end=FILE_END - VRAM)
    with open(os.path.join(ROOT, "config/mh1_main.yaml"), "w") as f:
        f.write(yaml)
    print("main.bin %d bytes sha1 %s" % (len(blob), sha1))
    print("%d symbols, %d text subsegments" % (len(out), len(starts)))


if __name__ == "__main__":
    main()
