/* nc07 - yn.bin 0x00534470-0x0053493C: yn_netcnf_pastproxy_check, yn_netcnf_ip_check, yn_netcnf_set_current, yn_netcnf_get_num, yn_netcnf_get_list, yn_netcnf_net_allload. Whole file in netcnf_nm.c. */
/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int DeviceLoadDriver();
int DeviceLoadDriver2();
int DeviceRollbackDriver();
int DeviceSelectInitialize();
int DeviceUpdateStatus();
int FlushCache();
int sceNetcnfifAllocWorkarea();
int sceNetcnfifCheck();
int sceNetcnfifDataInit();
int sceNetcnfifFreeWorkarea();
int sceNetcnfifGetCount();
int sceNetcnfifGetList();
int sceNetcnfifGetResult();
int sceNetcnfifInit();
int sceNetcnfifLoadEntry();
int sceNetcnfifSetFNoDecode();
int sceNetcnfifSetup();
int sceSifLoadModule();
int sceSifLoadStartModule();
int sceSifSearchModuleByName();
int sceSifStopModule();
int sceSifUnloadModule();
extern s32 CurDevice;
extern u8 DeviceWork[];
extern u8 lit_1349_0053E398[];
extern u8 lit_135_0053E300[];
extern u8 lit_136_0053E330[];
extern u8 lit_1846_0053E3A0[];
extern u8 lit_1847_0053E3B0[];
extern u8 lit_1903[];
extern u8 lit_203_0053E360[];
extern u8 lit_204_0053E380[];
extern u8 netcnf_arg[];
extern u8 netcnfif_arg[];

s32 yn_netcnf_init1();
s32 yn_netcnf_init2();
s32 yn_netcnf_exit();
u8 *yn_netcnf_search_usr_name();
void yn_netcnf_work_to_ifc();
void yn_netcnf_ifc_to_work();
void yn_netcnf_work_to_dev();
void yn_netcnf_dev_to_work();
void yn_netcnf_setup_devwork();
s32 yn_netcnf_pastdata_check();
s32 yn_netcnf_pastproxy_check();
typedef struct NCW {
    u8 _p0[0x197C0];
    s32 res;            /* 0x197C0 */
    u8 _p1[0x19AD0 - 0x197C4];
    s32 cnt0;           /* 0x19AD0 */
    s32 cnt1;           /* 0x19AD4 */
    s32 cnt2;           /* 0x19AD8 */
    u8 _p2[4];
    s32 type;           /* 0x19AE0 */
    s32 type2;          /* 0x19AE4 */
    u8 *list;           /* 0x19AE8 */
    u8 *list2;          /* 0x19AEC */
    s32 *pcnt;          /* 0x19AF0 */
    u8 buf[4];          /* 0x19AF4 */
} NCW;
s32 yn_netcnf_ip_check();
typedef struct NCDEV {
    s32 type;           /* 0x00 */
    s32 status;         /* 0x04 */
    u8 *a;              /* 0x08 */
    u8 *b;              /* 0x0C */
    u8 *c;              /* 0x10 */
} NCDEV;
void yn_netcnf_set_current();
s32 yn_netcnf_get_num();
s32 yn_netcnf_get_list();
void yn_netcnf_net_allload();
s32 yn_netcnf_magicno_check();
s32 yn_netcnf_magicno_check_sub();
void yn_netcnf_get_filename();
void yn_netcnf_ip_to_num();
void yn_netcnf_num_to_ip();
void yn_hard_init();
s32 yn_hard_status_check();
s32 yn_hard_type_check();
s32 yn_hard_select_set();
void yn_utf8_to_sjis();
void yn_sjis_to_utf8();
void module_unload_00535090(s32 id);
void module_load_00535140();

/* Returns the index of the past entry (0x14-byte records, ifc pointer at +0x10) that has the same
   settings as the work area, or -1. The two big locals are the ifc and dev structures built from it. */

typedef struct DEVW {
    s32 state;          /* 0x00 -1 = unused slot, 1 = ... (guess) */
    u8 _pad04[0x10];
    char *name;         /* 0x14 */
    char *vendor;       /* 0x18 */
} DEVW;                 /* 0x1C */

/* Stop and unload an IOP module (retries until the IOP accepts the request). */

/* Load an IOP module; with start != 0 also start it. retry = 0 means retry until it works,
   otherwise at most retry attempts. */

s32 yn_netcnf_pastproxy_check(u8 *arg0, u8 *arg1) {
    if (M2C_FIELD(arg0, s32 *, 0) != M2C_FIELD(arg1, s32 *, 0)) {
        return -1;
    }
    if (strcmp(arg0 + 8, arg1 + 8) != 0) {
        return -1;
    }
    if (M2C_FIELD(arg0, u16 *, 4) != M2C_FIELD(arg1, u16 *, 4)) {
        return -1;
    }
    if (strcmp(arg0 + 0x108, arg1 + 0x108) != 0) {
        return -1;
    }
    if (M2C_FIELD(arg0, u16 *, 6) != M2C_FIELD(arg1, u16 *, 6)) {
        return -1;
    }
    return 0;
}

s32 yn_netcnf_ip_check(u8 *p) {
    s32 i;

    for (i = 0; i < 4; i++, p++) {
        if (*p) {
            return 1;
        }
    }
    return 0;
}

void yn_netcnf_set_current(u8 *arg0, s32 arg1) {
    NCW *w = (NCW *)arg0;

    w->type = arg1;
    switch (arg1) {
    case 0:
        w->list = arg0;
        w->list2 = arg0 + 0x15E00;
        w->pcnt = &w->cnt0;
        break;
    case 1:
        w->list = arg0 + 0x1680;
        w->list2 = arg0 + 0x17140;
        w->pcnt = &w->cnt1;
        break;
    case 2:
        w->list = arg0 + 0x5A00;
        w->list2 = arg0 + 0x18480;
        w->pcnt = &w->cnt2;
        break;
    }
}

s32 yn_netcnf_get_num(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 t;

    sceNetcnfifGetCount(w->buf, w->type);
    do {
    } while (sceNetcnfifCheck() != 0);
    sceNetcnfifGetResult(&w->res);
    *w->pcnt = w->res;
    t = w->res;
    if (t <= 0) {
        return t;
    }
    return *w->pcnt;
}

s32 yn_netcnf_get_list(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 t;

    if (*w->pcnt == 0) {
        return 0;
    }
    FlushCache(0);
    sceNetcnfifGetList(w->buf, w->type, w->list, *w->pcnt);
    do {
    } while (sceNetcnfifCheck() != 0);
    sceNetcnfifGetResult(&w->res);
    t = w->res;
    if (t <= 0) {
        return t;
    }
    return *w->pcnt;
}

void yn_netcnf_net_allload(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 i;

    memset(arg0 + 0x9D80, 0, 0xC080);
    yn_netcnf_set_current(arg0, 0);
    yn_netcnf_get_num(arg0);
    yn_netcnf_get_list(arg0);
    for (i = 0; i < w->cnt0; i++) {
        sceNetcnfifDataInit(arg0 + i * 0x1340 + 0x9D80);
        FlushCache(0);
        sceNetcnfifLoadEntry(w->buf, w->type, w->list + i * 0x240 + 0x108, arg0 + i * 0x1340 + 0x9D80);
        do {
        } while (sceNetcnfifCheck() != 0);
    }
}
