/* nc09 - yn.bin 0x00534B20-0x00534B88: yn_netcnf_ip_to_num. Whole file in netcnf_nm.c. */
/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int DeviceLoadDriver();
int DeviceLoadDriver2();
int DeviceRollbackDriver();
int DeviceSelectInitialize();
int DeviceUpdateStatus();
int FlushCache();
int sceNetcnfifAllocWorkarea();
int sceNetcnfifCheck();
int sceNetcnfifDataInit();
int sceNetcnfifFreeWorkarea();
int sceNetcnfifGetCount();
int sceNetcnfifGetList();
int sceNetcnfifGetResult();
int sceNetcnfifInit();
int sceNetcnfifLoadEntry();
int sceNetcnfifSetFNoDecode();
int sceNetcnfifSetup();
int sceSifLoadModule();
int sceSifLoadStartModule();
int sceSifSearchModuleByName();
int sceSifStopModule();
int sceSifUnloadModule();
extern s32 CurDevice;
extern u8 DeviceWork[];
extern u8 lit_1349_0053E398[];
extern u8 lit_135_0053E300[];
extern u8 lit_136_0053E330[];
extern u8 lit_1846_0053E3A0[];
extern u8 lit_1847_0053E3B0[];
extern u8 lit_1903[];
extern u8 lit_203_0053E360[];
extern u8 lit_204_0053E380[];
extern u8 netcnf_arg[];
extern u8 netcnfif_arg[];

s32 yn_netcnf_init1();
s32 yn_netcnf_init2();
s32 yn_netcnf_exit();
u8 *yn_netcnf_search_usr_name();
void yn_netcnf_work_to_ifc();
void yn_netcnf_ifc_to_work();
void yn_netcnf_work_to_dev();
void yn_netcnf_dev_to_work();
void yn_netcnf_setup_devwork();
s32 yn_netcnf_pastdata_check();
s32 yn_netcnf_pastproxy_check();
typedef struct NCW {
    u8 _p0[0x197C0];
    s32 res;            /* 0x197C0 */
    u8 _p1[0x19AD0 - 0x197C4];
    s32 cnt0;           /* 0x19AD0 */
    s32 cnt1;           /* 0x19AD4 */
    s32 cnt2;           /* 0x19AD8 */
    u8 _p2[4];
    s32 type;           /* 0x19AE0 */
    s32 type2;          /* 0x19AE4 */
    u8 *list;           /* 0x19AE8 */
    u8 *list2;          /* 0x19AEC */
    s32 *pcnt;          /* 0x19AF0 */
    u8 buf[4];          /* 0x19AF4 */
} NCW;
s32 yn_netcnf_ip_check();
typedef struct NCDEV {
    s32 type;           /* 0x00 */
    s32 status;         /* 0x04 */
    u8 *a;              /* 0x08 */
    u8 *b;              /* 0x0C */
    u8 *c;              /* 0x10 */
} NCDEV;
void yn_netcnf_set_current();
s32 yn_netcnf_get_num();
s32 yn_netcnf_get_list();
void yn_netcnf_net_allload();
s32 yn_netcnf_magicno_check();
s32 yn_netcnf_magicno_check_sub();
void yn_netcnf_get_filename();
void yn_netcnf_ip_to_num();
void yn_netcnf_num_to_ip();
void yn_hard_init();
s32 yn_hard_status_check();
s32 yn_hard_type_check();
s32 yn_hard_select_set();
void yn_utf8_to_sjis();
void yn_sjis_to_utf8();
void module_unload_00535090(s32 id);
void module_load_00535140();

/* Returns the index of the past entry (0x14-byte records, ifc pointer at +0x10) that has the same
   settings as the work area, or -1. The two big locals are the ifc and dev structures built from it. */

typedef struct DEVW {
    s32 state;          /* 0x00 -1 = unused slot, 1 = ... (guess) */
    u8 _pad04[0x10];
    char *name;         /* 0x14 */
    char *vendor;       /* 0x18 */
} DEVW;                 /* 0x1C */

/* Stop and unload an IOP module (retries until the IOP accepts the request). */

/* Load an IOP module; with start != 0 also start it. retry = 0 means retry until it works,
   otherwise at most retry attempts. */

void yn_netcnf_ip_to_num(u8 *arg0, u8 *arg1) {
    u8 *var_a1;
    u8 var_a2;
    u8 *var_a0;
    u8 var_v1;

    var_a0 = arg0;
    var_a1 = arg1;
    var_v1 = *var_a0;
    var_a2 = 0;
    if (var_v1 != 0) {
        do {
            if (var_v1 == 0x2E) {
                *var_a1 = var_a2;
                var_a1 += 1;
                var_a2 = 0;
            } else {
                {
                int m = ((var_a2 & 0xFF) * 10) & 0xFF;

                var_a2 = (m + ((var_v1 - 0x30) & 0xFF)) & 0xFF;
            }
            }
            var_a0 += 1;
            var_v1 = *var_a0;
        } while (var_v1 != 0);
    }
    *var_a1 = var_a2;
}
