/* nc14 - yn.bin 0x00534280-0x00534470: yn_netcnf_pastdata_check. Whole file in netcnf_nm.c. */
/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int DeviceLoadDriver();
int DeviceLoadDriver2();
int DeviceRollbackDriver();
int DeviceSelectInitialize();
int DeviceUpdateStatus();
int FlushCache();
int sceNetcnfifAllocWorkarea();
int sceNetcnfifCheck();
int sceNetcnfifDataInit();
int sceNetcnfifFreeWorkarea();
int sceNetcnfifGetCount();
int sceNetcnfifGetList();
int sceNetcnfifGetResult();
int sceNetcnfifInit();
int sceNetcnfifLoadEntry();
int sceNetcnfifSetFNoDecode();
int sceNetcnfifSetup();
int sceSifLoadModule();
int sceSifLoadStartModule();
int sceSifSearchModuleByName();
int sceSifStopModule();
int sceSifUnloadModule();
extern s32 CurDevice;
extern u8 DeviceWork[];
extern u8 lit_1349_0053E398[];
extern u8 lit_135_0053E300[];
extern u8 lit_136_0053E330[];
extern u8 lit_1846_0053E3A0[];
extern u8 lit_1847_0053E3B0[];
extern u8 lit_1903[];
extern u8 lit_203_0053E360[];
extern u8 lit_204_0053E380[];
extern u8 netcnf_arg[];
extern u8 netcnfif_arg[];

s32 yn_netcnf_init1();
s32 yn_netcnf_init2();
s32 yn_netcnf_exit();
u8 *yn_netcnf_search_usr_name();
void yn_netcnf_work_to_ifc();
void yn_netcnf_ifc_to_work();
void yn_netcnf_work_to_dev();
void yn_netcnf_dev_to_work();
void yn_netcnf_setup_devwork();
s32 yn_netcnf_pastdata_check();
s32 yn_netcnf_pastproxy_check();
typedef struct NCW {
    u8 _p0[0x197C0];
    s32 res;            /* 0x197C0 */
    u8 _p1[0x19AD0 - 0x197C4];
    s32 cnt0;           /* 0x19AD0 */
    s32 cnt1;           /* 0x19AD4 */
    s32 cnt2;           /* 0x19AD8 */
    u8 _p2[4];
    s32 type;           /* 0x19AE0 */
    s32 type2;          /* 0x19AE4 */
    u8 *list;           /* 0x19AE8 */
    u8 *list2;          /* 0x19AEC */
    s32 *pcnt;          /* 0x19AF0 */
    u8 buf[4];          /* 0x19AF4 */
} NCW;
s32 yn_netcnf_ip_check();
typedef struct NCDEV {
    s32 type;           /* 0x00 */
    s32 status;         /* 0x04 */
    u8 *a;              /* 0x08 */
    u8 *b;              /* 0x0C */
    u8 *c;              /* 0x10 */
} NCDEV;
void yn_netcnf_set_current();
s32 yn_netcnf_get_num();
s32 yn_netcnf_get_list();
void yn_netcnf_net_allload();
s32 yn_netcnf_magicno_check();
s32 yn_netcnf_magicno_check_sub();
void yn_netcnf_get_filename();
void yn_netcnf_ip_to_num();
void yn_netcnf_num_to_ip();
void yn_hard_init();
s32 yn_hard_status_check();
s32 yn_hard_type_check();
s32 yn_hard_select_set();
void yn_utf8_to_sjis();
void yn_sjis_to_utf8();
void module_unload_00535090(s32 id);
void module_load_00535140();

typedef struct IFCW {
    u8 _p0[0x200];
    s8 a200[0x100];
    s8 a300[0x100];
    s8 a400[0x100];
    s8 a500[0x100];
    s8 a600[0x100];
    s8 a700[0x100];
    u8 _p1[0x300];
    s8 b00[0x100];
    s8 c00[0x100];
    s8 d00[0x100];
    s8 aE00[0x100];
    s8 aF00[0x100];
    u8 _p2[0x300];
    s32 x1300;
    s32 x1304;
    s32 x1308;
    s32 x130C;
    s32 x1310;
    u8 _p3[0xC];
    u8 x1320;
    s8 x1321;
    s8 x1322;
    s8 x1323;
    s8 x1324;
    u8 x1325;
    s8 x1326;
    s8 x1327;
    s8 x1328;
    u8 _p4[0x17];
} IFCW;

typedef struct WRKW {
    u8 _p0[5];
    u8 x5;
    u8 x6;
    u8 x7;
    u8 _p1;
    u8 x9;
    u8 _p2[2];
    u8 a0C[0x200];
    u8 a20C[0x200];
    u8 a40C[0x200];
    u8 a60C[4];
    u8 a610[4];
    u8 a614[4];
    u8 a618[4];
    u8 a61C[4];
    u8 a620[4];
} WRKW;

/* Returns the index of the past entry (0x14-byte records, ifc pointer at +0x10) that has the same
   settings as the work area, or -1. The two big locals are the ifc and dev structures built from it. */

typedef struct DEVW {
    s32 state;          /* 0x00 -1 = unused slot, 1 = ... (guess) */
    u8 _pad04[0x10];
    char *name;         /* 0x14 */
    char *vendor;       /* 0x18 */
} DEVW;                 /* 0x1C */

/* Stop and unload an IOP module (retries until the IOP accepts the request). */

/* Load an IOP module; with start != 0 also start it. retry = 0 means retry until it works,
   otherwise at most retry attempts. */

s32 yn_netcnf_pastdata_check(WRKW *work, u8 *list, s32 num) {
    s8 name[0x200];
    struct { IFCW x; u8 pad[0x30]; } ifcx; /* the original frame leaves 0x30 more bytes after the ifc struct */
    IFCW dev;
    IFCW *e;
    s32 ip;
    s32 i;
    u8 *rec;

    name[0] = 0;
    yn_netcnf_work_to_ifc(work, &ifcx.x, name);
    yn_netcnf_work_to_dev((u8 *)work, (u8 *)&dev);
    rec = list;
    for (i = 0; i < num; i++, rec += 0x14) {
        e = M2C_FIELD(rec, IFCW **, 0x10);
        if (e != NULL && strcmp(e->aE00, dev.aE00) == 0 && strcmp(e->aF00, dev.aF00) == 0 && e->x1320 == ifcx.x.x1320 && strcmp(e->a200, ifcx.x.a200) == 0 && e->x1325 == ifcx.x.x1325 && strcmp(e->b00, ifcx.x.b00) == 0 && strcmp(e->c00, ifcx.x.c00) == 0) {
            ip = 0;
            yn_netcnf_ip_to_num(e->a300, &ip);
            if (ip == *(s32 *)work->a60C) {
                ip = 0;
                yn_netcnf_ip_to_num(e->a400, &ip);
                if (ip == *(s32 *)work->a610) {
                    ip = 0;
                    yn_netcnf_ip_to_num(e->a500, &ip);
                    if (ip == *(s32 *)work->a614) {
                        ip = 0;
                        yn_netcnf_ip_to_num(e->a600, &ip);
                        if (ip == *(s32 *)work->a618) {
                            ip = 0;
                            yn_netcnf_ip_to_num(e->a700, &ip);
                            if (ip == *(s32 *)work->a61C) {
                                return i;
                            }
                        }
                    }
                }
            }
        }
    }
    return -1;
}
