/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int DeviceLoadDriver();
int DeviceLoadDriver2();
int DeviceRollbackDriver();
int DeviceSelectInitialize();
int DeviceUpdateStatus();
int FlushCache();
int sceNetcnfifAllocWorkarea();
int sceNetcnfifCheck();
int sceNetcnfifDataInit();
int sceNetcnfifFreeWorkarea();
int sceNetcnfifGetCount();
int sceNetcnfifGetList();
int sceNetcnfifGetResult();
int sceNetcnfifInit();
int sceNetcnfifLoadEntry();
int sceNetcnfifSetFNoDecode();
int sceNetcnfifSetup();
int sceSifLoadModule();
int sceSifLoadStartModule();
int sceSifSearchModuleByName();
int sceSifStopModule();
int sceSifUnloadModule();
extern s32 CurDevice;
extern u8 DeviceWork[];
extern u8 lit_1349_0053E398[];
extern u8 lit_135_0053E300[];
extern u8 lit_136_0053E330[];
extern u8 lit_1846_0053E3A0[];
extern u8 lit_1847_0053E3B0[];
extern u8 lit_1903[];
extern u8 lit_203_0053E360[];
extern u8 lit_204_0053E380[];
extern u8 netcnf_arg[];
extern u8 netcnfif_arg[];

s32 yn_netcnf_init1();
s32 yn_netcnf_init2();
s32 yn_netcnf_exit();
u8 *yn_netcnf_search_usr_name();
void yn_netcnf_work_to_ifc();
void yn_netcnf_ifc_to_work();
void yn_netcnf_work_to_dev();
void yn_netcnf_dev_to_work();
void yn_netcnf_setup_devwork();
s32 yn_netcnf_pastdata_check();
s32 yn_netcnf_pastproxy_check();
typedef struct NCW {
    u8 _p0[0x197C0];
    s32 res;            /* 0x197C0 */
    u8 _p1[0x19AD0 - 0x197C4];
    s32 cnt0;           /* 0x19AD0 */
    s32 cnt1;           /* 0x19AD4 */
    s32 cnt2;           /* 0x19AD8 */
    u8 _p2[4];
    s32 type;           /* 0x19AE0 */
    s32 type2;          /* 0x19AE4 */
    u8 *list;           /* 0x19AE8 */
    u8 *list2;          /* 0x19AEC */
    s32 *pcnt;          /* 0x19AF0 */
    u8 buf[4];          /* 0x19AF4 */
} NCW;
s32 yn_netcnf_ip_check();
typedef struct NCDEV {
    s32 type;           /* 0x00 */
    s32 status;         /* 0x04 */
    u8 *a;              /* 0x08 */
    u8 *b;              /* 0x0C */
    u8 *c;              /* 0x10 */
} NCDEV;
void yn_netcnf_set_current();
s32 yn_netcnf_get_num();
s32 yn_netcnf_get_list();
void yn_netcnf_net_allload();
s32 yn_netcnf_magicno_check();
s32 yn_netcnf_magicno_check_sub();
void yn_netcnf_get_filename();
void yn_netcnf_ip_to_num();
void yn_netcnf_num_to_ip();
void yn_hard_init();
s32 yn_hard_status_check();
s32 yn_hard_type_check();
s32 yn_hard_select_set();
void yn_utf8_to_sjis();
void yn_sjis_to_utf8();
void module_unload_00535090(s32 id);
void module_load_00535140();

s32 yn_netcnf_init1(void) {
    module_load_00535140(lit_135_0053E300, 0x7F, netcnf_arg, 0, 0);
    module_load_00535140(lit_136_0053E330, 0x16, netcnfif_arg, 0, 0);
    sceNetcnfifInit();
    do {

    } while (sceNetcnfifSetup() < 0);
    return 0;
}

s32 yn_netcnf_init2(u8 *arg0) {
    do {

    } while (sceNetcnfifAllocWorkarea(0x1000) < 0);
    do {

    } while (sceNetcnfifCheck() != 0);
    do {

    } while (sceNetcnfifGetResult(arg0 + 0x197C0) < 0);
    if (M2C_FIELD(arg0, s32 *, 0x197C0) < 0) {
        return -1;
    }
    sceNetcnfifSetFNoDecode(0);
    return 0;
}

s32 yn_netcnf_exit(void) {
    s32 temp_v0;
    s32 temp_v0_2;

    do {

    } while (sceNetcnfifFreeWorkarea() < 0);
    do {

    } while (sceNetcnfifCheck() != 0);
    temp_v0 = sceSifSearchModuleByName(lit_203_0053E360);
    if (0 <= temp_v0) {
        module_unload_00535090(temp_v0);
    }
    temp_v0_2 = sceSifSearchModuleByName(lit_204_0053E380);
    if (0 <= temp_v0_2) {
        module_unload_00535090(temp_v0_2);
    }
    return 0;
}

u8 *yn_netcnf_search_usr_name(u8 *arg0, char *arg1) {
    NCW *w = (NCW *)arg0;
    s32 i;

    for (i = 0; i < w->cnt1; i++) {
        if (strcmp(arg0 + i * 0x240 + 0x1688, arg1) == 0) {
            return arg0 + i * 0x240 + 0x1788;
        }
    }
    return NULL;
}

void yn_netcnf_work_to_ifc(u8 *arg0, u8 *arg1, s8 *arg2) {
    sceNetcnfifDataInit(arg1);
    M2C_FIELD(arg1, s8 *, 0x1324) = 0;
    if (M2C_FIELD(arg0, u8 *, 9) == 1) {
        M2C_FIELD(arg1, s32 *, 0x1300) = 3;
    } else {
        M2C_FIELD(arg1, s32 *, 0x1300) = 1;
    }
    if (M2C_FIELD(arg0, u8 *, 5) == 0) {
        M2C_FIELD(arg1, s8 *, 0x1325) = 1;
        M2C_FIELD(arg1, u8 *, 0x1320) = 0U;
        strcpy(arg1 + 0xB00, arg0 + 0xC);
        strcpy(arg1 + 0xC00, arg0 + 0x20C);
        strcpy(arg1 + 0xD00, lit_1349_0053E398);
        M2C_FIELD(arg1, s8 *, 0x1323) = 1;
        M2C_FIELD(arg1, s8 *, 0x1324) = 4;
        M2C_FIELD(arg1, s8 *, 0x1326) = 0;
        M2C_FIELD(arg1, s8 *, 0x1327) = 0;
        M2C_FIELD(arg1, s8 *, 0x1328) = 0;
        M2C_FIELD(arg1, s32 *, 0x1304) = 0x5AE;
        M2C_FIELD(arg1, s32 *, 0x1300) = 2;
        M2C_FIELD(arg1, s32 *, 0x1308) = 0;
    } else {
        M2C_FIELD(arg1, s8 *, 0x1325) = 0xFF;
        if (M2C_FIELD(arg0, u8 *, 6) == 0) {
            M2C_FIELD(arg1, u8 *, 0x1320) = 1U;
            strcpy(arg1 + 0x200, arg0 + 0x40C);
        } else {
            M2C_FIELD(arg1, u8 *, 0x1320) = 0U;
            yn_netcnf_num_to_ip(arg1 + 0x300, arg0 + 0x60C);
            yn_netcnf_num_to_ip(arg1 + 0x400, arg0 + 0x610);
            yn_netcnf_num_to_ip(arg1 + 0x500, arg0 + 0x614);
        }
    }
    if (M2C_FIELD(arg0, u8 *, 7) != 0) {
        if (yn_netcnf_ip_check(arg0 + 0x618) != 0) {
            yn_netcnf_num_to_ip(arg1 + 0x600, arg0 + 0x618);
        }
        if (yn_netcnf_ip_check(arg0 + 0x61C) != 0) {
            yn_netcnf_num_to_ip(arg1 + 0x700, arg0 + 0x61C);
        }
        if (M2C_FIELD(arg1, s8 *, 0x600) == 0) {
            memset(arg1 + 0x600, 0, 0x100);
            memset(arg1 + 0x700, 0, 0x100);
            M2C_FIELD(arg1, s8 *, 0x1321) = 1;
            M2C_FIELD(arg1, s8 *, 0x1322) = 1;
        }
        if (M2C_FIELD(arg1, s8 *, 0x700) == 0) {
            memset(arg1 + 0x700, 0, 0x100);
        }
    } else if (M2C_FIELD(arg1, u8 *, 0x1320) != 1) {
        M2C_FIELD(arg1, s8 *, 0x1321) = 1;
        M2C_FIELD(arg1, s8 *, 0x1322) = 1;
    }
    yn_sjis_to_utf8(arg2, arg0 + 0x620);
}

void yn_netcnf_ifc_to_work(u8 *arg0, u8 *arg1, s8 *arg2) {
    u8 temp_v1;

    memset(arg0, 0, 0xA20);
    M2C_FIELD(arg0, s32 *, 0) = (s32) M2C_FIELD(arg1, s32 *, 0x1300);
    if (M2C_FIELD(arg1, u8 *, 0x1325) == 1) {
        strcpy(arg0 + 0xC, arg1 + 0xB00);
        strcpy(arg0 + 0x20C, arg1 + 0xC00);
    } else {
        M2C_FIELD(arg0, s8 *, 5) = 1;
        temp_v1 = M2C_FIELD(arg1, u8 *, 0x1320);
        if (temp_v1 != 0xFF) {
            if (temp_v1 == 1) {
                strcpy(arg0 + 0x40C, arg1 + 0x200);
            } else {
                M2C_FIELD(arg0, s8 *, 6) = 1;
                yn_netcnf_ip_to_num(arg1 + 0x300, arg0 + 0x60C);
                yn_netcnf_ip_to_num(arg1 + 0x400, arg0 + 0x610);
                yn_netcnf_ip_to_num(arg1 + 0x500, arg0 + 0x614);
            }
        }
    }
    if (M2C_FIELD(arg1, s8 *, 0x600) != 0) {
        M2C_FIELD(arg0, s8 *, 7) = 1;
        yn_netcnf_ip_to_num(arg1 + 0x600, arg0 + 0x618);
        yn_netcnf_ip_to_num(arg1 + 0x700, arg0 + 0x61C);
    }
    if (yn_netcnf_ip_check(arg0 + 0x618) == 0) {
        M2C_FIELD(arg0, s8 *, 7) = 0;
        M2C_FIELD(arg0, s8 *, 0x618) = 0;
        M2C_FIELD(arg0, s8 *, 0x61C) = 0;
        M2C_FIELD(arg0, s8 *, 0x619) = 0;
        M2C_FIELD(arg0, s8 *, 0x61D) = 0;
        M2C_FIELD(arg0, s8 *, 0x61A) = 0;
        M2C_FIELD(arg0, s8 *, 0x61E) = 0;
        M2C_FIELD(arg0, s8 *, 0x61B) = 0;
        M2C_FIELD(arg0, s8 *, 0x61F) = 0;
    }
    yn_utf8_to_sjis(arg0 + 0x620, arg2);
}

void yn_netcnf_work_to_dev(u8 *arg0, u8 *arg1) {
    sceNetcnfifDataInit(arg1);
    strcpy(arg1 + 0xE00, arg0 + 0x820);
    strcpy(arg1 + 0xF00, arg0 + 0x920);
    if (M2C_FIELD(arg0, u8 *, 9) == 1) {
        M2C_FIELD(arg1, s32 *, 0x130C) = 3;
    } else {
        M2C_FIELD(arg1, s32 *, 0x130C) = 1;
    }
    switch (M2C_FIELD(arg0, u8 *, 8)) {
    case 0:
    default:
        M2C_FIELD(arg1, s32 *, 0x1310) = 1;
        break;
    case 1:
        M2C_FIELD(arg1, s32 *, 0x1310) = 2;
        break;
    case 2:
        M2C_FIELD(arg1, s32 *, 0x1310) = 3;
        break;
    case 3:
        M2C_FIELD(arg1, s32 *, 0x1310) = 5;
        break;
    case 4:
        M2C_FIELD(arg1, s32 *, 0x1310) = 6;
        break;
    }
}

void yn_netcnf_dev_to_work(u8 *arg0, u8 *arg1) {
    s32 temp_a0;
    s8 var_v1;

    strcpy(arg0 + 0x820, arg1 + 0xE00);
    strcpy(arg0 + 0x920, arg1 + 0xF00);
    temp_a0 = M2C_FIELD(arg1, s32 *, 0x1310);
    switch (M2C_FIELD(arg1, s32 *, 0x1310)) {
    case 1:
    default:
        M2C_FIELD(arg0, s8 *, 8) = 0;
        break;
    case 2:
        M2C_FIELD(arg0, s8 *, 8) = 1;
        break;
    case 3:
        M2C_FIELD(arg0, s8 *, 8) = 2;
        break;
    case 5:
        M2C_FIELD(arg0, s8 *, 8) = 3;
        break;
    case 6:
        M2C_FIELD(arg0, s8 *, 8) = 4;
        break;
    }
}

void yn_netcnf_setup_devwork(u8 *arg0, u8 *arg1) {
    NCW *w = (NCW *)arg0;
    NCDEV *d;
    s32 i;

    yn_netcnf_set_current(arg0, 1);
    for (i = 0; i < w->cnt0; i++) {
        d = (NCDEV *)(arg1 + i * 0x14);
        d->a = arg0 + i * 0x1340 + 0xAB80;
        d->b = arg0 + i * 0x1340 + 0xAC80;
        d->c = arg0 + i * 0x1340 + 0x9D80;
        if (d->a == NULL || d->b == NULL) {
            d->type = 0;
            d->status = -1;
        } else {
            d->type = yn_hard_type_check(d->a, d->b);
            d->status = yn_hard_status_check(d->a, d->b);
        }
    }
}

/* Returns the index of the past entry (0x14-byte records, ifc pointer at +0x10) that has the same
   settings as the work area, or -1. The two big locals are the ifc and dev structures built from it. */
s32 yn_netcnf_pastdata_check(u8 *work, u8 *list, s32 num) {
    u8 dev[0x1320];
    u8 ifc[0x1330];
    s8 name[0x100];
    s32 ip;
    s32 i;
    u8 *e;
    u8 *rec = list;

    name[0] = 0;
    yn_netcnf_work_to_ifc(work, ifc, name);
    yn_netcnf_work_to_dev(work, dev);
    i = 0;
    if (num > 0) {
loop_2:
        e = M2C_FIELD(rec, u8 **, 0x10);
        if ((e != NULL) && (strcmp(e + 0xE00, dev + 0xE00) == 0) && (strcmp(e + 0xF00, dev + 0xF00) == 0) && (M2C_FIELD(e, u8 *, 0x1320) == ifc[0x1320]) && (strcmp(e + 0x200, ifc + 0x200) == 0) && (M2C_FIELD(e, u8 *, 0x1325) == ifc[0x1325]) && (strcmp(e + 0xB00, ifc + 0xB00) == 0) && (strcmp(e + 0xC00, ifc + 0xC00) == 0)) {
            ip = 0;
            yn_netcnf_ip_to_num(e + 0x300, (u8 *)&ip);
            if (ip == M2C_FIELD(work, s32 *, 0x60C)) {
                ip = 0;
                yn_netcnf_ip_to_num(e + 0x400, (u8 *)&ip);
                if (ip == M2C_FIELD(work, s32 *, 0x610)) {
                    ip = 0;
                    yn_netcnf_ip_to_num(e + 0x500, (u8 *)&ip);
                    if (ip == M2C_FIELD(work, s32 *, 0x614)) {
                        ip = 0;
                        yn_netcnf_ip_to_num(e + 0x600, (u8 *)&ip);
                        if (ip == M2C_FIELD(work, s32 *, 0x618)) {
                            ip = 0;
                            yn_netcnf_ip_to_num(e + 0x700, (u8 *)&ip);
                            if (ip == M2C_FIELD(work, s32 *, 0x61C)) {
                                return i;
                            }
                        }
                    }
                }
            }
        }
        i += 1;
        rec += 0x14;
        if (i >= num) {
            goto block_18;
        }
        goto loop_2;
    }
block_18:
    return -1;
}

s32 yn_netcnf_pastproxy_check(u8 *arg0, u8 *arg1) {
    if (M2C_FIELD(arg0, s32 *, 0) != M2C_FIELD(arg1, s32 *, 0)) {
        return -1;
    }
    if (strcmp(arg0 + 8, arg1 + 8) != 0) {
        return -1;
    }
    if (M2C_FIELD(arg0, u16 *, 4) != M2C_FIELD(arg1, u16 *, 4)) {
        return -1;
    }
    if (strcmp(arg0 + 0x108, arg1 + 0x108) != 0) {
        return -1;
    }
    if (M2C_FIELD(arg0, u16 *, 6) != M2C_FIELD(arg1, u16 *, 6)) {
        return -1;
    }
    return 0;
}

s32 yn_netcnf_ip_check(u8 *p) {
    s32 i;

    for (i = 0; i < 4; i++, p++) {
        if (*p) {
            return 1;
        }
    }
    return 0;
}

void yn_netcnf_set_current(u8 *arg0, s32 arg1) {
    NCW *w = (NCW *)arg0;

    w->type = arg1;
    switch (arg1) {
    case 0:
        w->list = arg0;
        w->list2 = arg0 + 0x15E00;
        w->pcnt = &w->cnt0;
        break;
    case 1:
        w->list = arg0 + 0x1680;
        w->list2 = arg0 + 0x17140;
        w->pcnt = &w->cnt1;
        break;
    case 2:
        w->list = arg0 + 0x5A00;
        w->list2 = arg0 + 0x18480;
        w->pcnt = &w->cnt2;
        break;
    }
}

s32 yn_netcnf_get_num(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 t;

    sceNetcnfifGetCount(w->buf, w->type);
    do {
    } while (sceNetcnfifCheck() != 0);
    sceNetcnfifGetResult(&w->res);
    *w->pcnt = w->res;
    t = w->res;
    if (t <= 0) {
        return t;
    }
    return *w->pcnt;
}

s32 yn_netcnf_get_list(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 t;

    if (*w->pcnt == 0) {
        return 0;
    }
    FlushCache(0);
    sceNetcnfifGetList(w->buf, w->type, w->list, *w->pcnt);
    do {
    } while (sceNetcnfifCheck() != 0);
    sceNetcnfifGetResult(&w->res);
    t = w->res;
    if (t <= 0) {
        return t;
    }
    return *w->pcnt;
}

void yn_netcnf_net_allload(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    s32 i;

    memset(arg0 + 0x9D80, 0, 0xC080);
    yn_netcnf_set_current(arg0, 0);
    yn_netcnf_get_num(arg0);
    yn_netcnf_get_list(arg0);
    for (i = 0; i < w->cnt0; i++) {
        sceNetcnfifDataInit(arg0 + i * 0x1340 + 0x9D80);
        FlushCache(0);
        sceNetcnfifLoadEntry(w->buf, w->type, w->list + i * 0x240 + 0x108, arg0 + i * 0x1340 + 0x9D80);
        do {
        } while (sceNetcnfifCheck() != 0);
    }
}

s32 yn_netcnf_magicno_check(u8 *arg0) {
    M2C_FIELD(arg0, s32 *, 0x19AE4) = (s32) M2C_FIELD(arg0, s32 *, 0x19AE0);
    yn_netcnf_set_current(arg0, 0);
    if (yn_netcnf_get_num(arg0) > 0) {
        yn_netcnf_get_list(arg0);
        return yn_netcnf_magicno_check_sub(arg0);
    }
    yn_netcnf_set_current(arg0, 1);
    if (yn_netcnf_get_num(arg0) > 0) {
        yn_netcnf_get_list(arg0);
        return yn_netcnf_magicno_check_sub(arg0);
    }
    yn_netcnf_set_current(arg0, 2);
    if (yn_netcnf_get_num(arg0) > 0) {
        yn_netcnf_get_list(arg0);
        return yn_netcnf_magicno_check_sub(arg0);
    }
    return 0;
}

s32 yn_netcnf_magicno_check_sub(u8 *arg0) {
    NCW *w = (NCW *)arg0;
    u8 sp20[0x1340];

    sceNetcnfifDataInit(sp20);
    FlushCache(0);
    do {

    } while (sceNetcnfifLoadEntry(w->buf, w->type, w->list + 0x108, sp20) < 0);
    do {

    } while (sceNetcnfifCheck() != 0);
    sceNetcnfifGetResult(&w->res);
    yn_netcnf_set_current(arg0, w->type2);
    if (w->res == -0xF) {
        return -1;
    }
    return 0;
}

void yn_netcnf_get_filename(u8 *arg0, int arg1) {
    sprintf(arg0 + 0x19AF4, lit_1846_0053E3A0, arg1, lit_1847_0053E3B0);
}

void yn_netcnf_ip_to_num(u8 *arg0, u8 *arg1) {
    u8 *var_a1;
    u8 var_a2;
    u8 *var_a0;
    u8 var_v1;

    var_a0 = arg0;
    var_a1 = arg1;
    var_v1 = *var_a0;
    var_a2 = 0;
    if (var_v1 != 0) {
        do {
            if (var_v1 == 0x2E) {
                *var_a1 = var_a2;
                var_a1 += 1;
                var_a2 = 0;
            } else {
                {
                int m = ((var_a2 & 0xFF) * 10) & 0xFF;

                var_a2 = (m + ((var_v1 - 0x30) & 0xFF)) & 0xFF;
            }
            }
            var_a0 += 1;
            var_v1 = *var_a0;
        } while (var_v1 != 0);
    }
    *var_a1 = var_a2;
}

void yn_netcnf_num_to_ip(char *dst, u8 *ip) {
    sprintf(dst, lit_1903, ip[0], ip[1], ip[2], ip[3]);
}

void yn_hard_init(void) {
    if (CurDevice != 0) {
        DeviceRollbackDriver();
    }
    DeviceSelectInitialize();
    DeviceUpdateStatus();
}

typedef struct DEVW {
    s32 state;          /* 0x00 -1 = unused slot, 1 = ... (guess) */
    u8 _pad04[0x10];
    char *name;         /* 0x14 */
    char *vendor;       /* 0x18 */
} DEVW;                 /* 0x1C */

s32 yn_hard_status_check(char *name, char *vendor) {
    s32 i;
    DEVW *d;

    i = 0;
    d = (DEVW *)DeviceWork;
    do {
        if (d->state != -1 && strcmp(d->name, name) == 0 && strcmp(d->vendor, vendor) == 0) {
            return i;
        }
        i++;
        d++;
    } while (i < 0x23);
    return -1;
}

s32 yn_hard_type_check(char *name, char *vendor) {
    s32 i;
    DEVW *d;

    i = 0;
    d = (DEVW *)DeviceWork;
    do {
        if (d->state != -1 && strcmp(d->name, name) == 0 && strcmp(d->vendor, vendor) == 0) {
            if (((DEVW *)DeviceWork)[i].state == 1) {
                return 1;
            }
            return 2;
        }
        i++;
        d++;
    } while (i < 0x23);
    return 0;
}

s32 yn_hard_select_set(s32 n) {
    s32 cur;
    DEVW *d;

    d = &((DEVW *)DeviceWork)[n];
    cur = CurDevice;
    if (cur != 0) {
        return -(cur != (s32)d);
    }
    if (d->state != 1) {
        return -2;
    }
    CurDevice = (s32)d;
    DeviceLoadDriver(cur, d);
    DeviceLoadDriver2();
    return 1;
}

void yn_utf8_to_sjis(s8 *arg0, u8 *arg1) {
    s32 temp_t4;
    s32 var_t4_2;
    s8 *var_a0;
    s8 temp_t4_2;
    u8 *var_a1;
    u8 var_t4;

    var_a0 = arg0;
    var_a1 = arg1;
    var_t4 = *var_a1;
    if (var_t4 != 0) {
        do {
            if ((s32) var_t4 >= 0x80) {
                temp_t4 = ((M2C_FIELD(var_a1, u8 *, 1) << 8) + M2C_FIELD(var_a1, u8 *, 2)) & 0xFFFF;
                var_a1 = var_a1 + 2 + 1;
                if ((temp_t4 >= 0x8181) && (temp_t4 < 0x81C0)) {
                    var_t4_2 = (temp_t4 + 0x11E) & 0xFFFF;
                } else if ((temp_t4 >= 0x8280) && (temp_t4 < 0x8294)) {
                    var_t4_2 = (temp_t4 + 0x5E) & 0xFFFF;
                } else if ((temp_t4 >= 0x82A1) && (temp_t4 < 0x82C0)) {
                    var_t4_2 = (temp_t4 + 0x9F) & 0xFFFF;
                } else if ((temp_t4 >= 0x8380) && (temp_t4 < 0x83A0)) {
                    var_t4_2 = (temp_t4 - 0x21) & 0xFFFF;
                } else if ((temp_t4 >= 0x83A0) && (temp_t4 < 0x83B7)) {
                    var_t4_2 = (temp_t4 - 0x20) & 0xFFFF;
                } else {
                    var_t4_2 = 0x815B & 0xFFFF;
                }
                temp_t4_2 = var_t4_2 & 0xFFFF;
                M2C_FIELD(var_a0, u8 *, 0) = (u8) (temp_t4_2 >> 8);
                M2C_FIELD(var_a0, s8 *, 1) = temp_t4_2;
                var_a0 += 2;
            } else {
                M2C_FIELD(var_a0, u8 *, 0) = var_t4;
                var_a1 += 1;
                var_a0 += 1;
            }
            var_t4 = *var_a1;
        } while (var_t4 != 0);
    }
    *var_a0 = 0;
}

void yn_sjis_to_utf8(s8 *arg0, u8 *arg1) {
    s32 temp_t6;
    s32 var_t6_2;
    s32 var_v1;
    s8 *var_a0;
    s8 temp_t6_2;
    u8 *var_a1;
    u8 var_t6;

    var_a0 = arg0;
    var_a1 = arg1;
    var_t6 = *var_a1;
    var_v1 = 0;
    if (var_t6 != 0) {
loop_2:
        if ((s32) var_t6 >= 0x80) {
            if (var_v1 < 0xFD) {
                temp_t6 = (((var_t6 & 0xFF) << 8) + M2C_FIELD(var_a1, u8 *, 1)) & 0xFFFF;
                var_a1 += 2;
                if ((temp_t6 >= 0x829F) && (temp_t6 < 0x82DE)) {
                    var_t6_2 = (temp_t6 - 0x11E) & 0xFFFF;
                } else if ((temp_t6 >= 0x82DE) && (temp_t6 < 0x82F2)) {
                    var_t6_2 = (temp_t6 - 0x5E) & 0xFFFF;
                } else if ((temp_t6 >= 0x8340) && (temp_t6 < 0x835F)) {
                    var_t6_2 = (temp_t6 - 0x9F) & 0xFFFF;
                } else if ((temp_t6 >= 0x835F) && (temp_t6 < 0x837F)) {
                    var_t6_2 = (temp_t6 + 0x21) & 0xFFFF;
                } else if ((temp_t6 >= 0x8380) && (temp_t6 < 0x8397)) {
                    var_t6_2 = (temp_t6 + 0x20) & 0xFFFF;
                } else {
                    var_t6_2 = 0x83BC & 0xFFFF;
                }
                temp_t6_2 = var_t6_2 & 0xFFFF;
                M2C_FIELD(var_a0, u8 *, 0) = 0xE3;
                M2C_FIELD(var_a0, s8 *, 1) = (s8) (temp_t6_2 >> 8);
                var_v1 += 3;
                M2C_FIELD(var_a0, s8 *, 2) = temp_t6_2;
                var_a0 = var_a0 + 2 + 1;
                goto block_25;
            }
        } else if (var_v1 < 0xFF) {
            M2C_FIELD(var_a0, u8 *, 0) = var_t6;
            var_a1 += 1;
            var_a0 += 1;
            var_v1 += 1;
block_25:
            var_t6 = *var_a1;
            if (var_t6 == 0) {

            } else {
                goto loop_2;
            }
        }
    }
    *var_a0 = 0;
}

/* Stop and unload an IOP module (retries until the IOP accepts the request). */
void module_unload_00535090(s32 id) {
    int result;
    s32 r;

    while ((r = sceSifStopModule(id, 0, 0, &result)) < 0) {
    }
    if (r >= 0) {
        while (sceSifUnloadModule(id) < 0) {
        }
    }
}

/* Load an IOP module; with start != 0 also start it. retry = 0 means retry until it works,
   otherwise at most retry attempts. */
void module_load_00535140(char *name, int len, char *args, int start, int retry) {
    int i;

    if (start == 0) {
        if (retry == 0) {
            while (sceSifLoadModule(name, len, args) < 0) {
            }
            return;
        }
        for (i = 0; i < retry; i++) {
            if (sceSifLoadModule(name, len, args) >= 0) {
                return;
            }
        }
        return;
    }
    if (retry == 0) {
        while (sceSifLoadStartModule(name, len, args, start) < 0) {
        }
        return;
    }
    for (i = 0; i < retry; i++) {
        if (sceSifLoadStartModule(name, len, args, start) >= 0) {
            return;
        }
    }
}
