/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int ADXM_ShutdownThrd();
int ADXPS2_LoadFcacheDvd();
int ADXT_Finish();
int DIntr();
int DisableDmac();
int DisableIntc();
int EIntr();
int InetIPAddrFromString();
int LoadExecPS2();
int Net_kb_input_init2();
int Net_kb_input_sub();
int RemoveDmacHandler();
int RemoveIntcHandler();
int SetFilterMode();
int SoftKey_Getstr();
int SoftKey_onoff();
int SoftKey_trans();
int YnFile_Data_load();
int flCreateTextureFromTim2_mem();
int flPADDestroy();
int flPS2DmaWait();
int flReleasePaletteHandle();
int flReleaseTextureHandle();
int flSetRenderState();
f32 flSin(f32 x);
int flfntDraw();
int flfntInit();
int flfntLocate();
int flfntPrintf();
int flfntSetHalftype();
int flfntSetPalette();
int flfntSetSize();
void flfntSetZ(f32 z);
int net_flps0008();
int printf();
int sceCdInit();
int sceGsSyncPath();
int sceGsSyncVCallback();
int sceNetcnfifConvAuthname();
int sceSifExitCmd();
int str_stop_all();
int yn_can_sd();
int yn_cur1_sd();
int yn_cur2_sd();
int yn_dec_sd();
int yn_hard_init();
int yn_hard_select_set();
int yn_log_sd();
int yn_mc_device_check_all();
int yn_mc_format();
int yn_mc_get_current();
int yn_mc_gmfile_check();
int yn_mc_gmfile_current_set();
int yn_mc_gmfile_save();
int yn_mc_init();
int yn_mc_set_current();
int yn_mc_ynfile_check();
int yn_netcnf_dev_to_work();
int yn_netcnf_exit();
int yn_netcnf_get_filename();
int yn_netcnf_get_list();
int yn_netcnf_get_num();
int yn_netcnf_ifc_to_work();
int yn_netcnf_init1();
int yn_netcnf_init2();
int yn_netcnf_magicno_check();
int yn_netcnf_net_allload();
int yn_netcnf_pastdata_check();
int yn_netcnf_pastproxy_check();
int yn_netcnf_search_usr_name();
int yn_netcnf_set_current();
int yn_netcnf_setup_devwork();
int yn_ng_sd();
int yn_set_init();
int yn_stop_bgm();
int yn_utf8_to_sjis();
extern u8 BsProxyUrlstr[];
extern u8 BsProxyUrlstr_S[];
extern u8 D_530394[];
extern u8 D_5306B0[];
extern u8 D_5310D0[];
extern u8 DeviceWork[];
extern u8 MyDialNumber[];
extern u8 MyDialOutline[];
extern u8 MyDomain[];
extern u8 MyPassword[];
extern u8 MyUserName[];
extern u8 Psw[];
extern u8 SrvDomain[];
extern u8 Yn_temp[];
extern u8 lit_160_0053EA40[];
extern u8 lit_4084[];
extern u8 lit_4085[];
extern u8 lit_4086[];
extern u8 lit_4087[];
extern u8 lit_4118[];
extern u8 lit_4217[];
extern u8 lit_4218[];
extern u8 lit_4358[];
extern u8 lit_4994[];
extern u8 lit_3947[];
extern u8 lit_3948[];
extern u8 lit_3949[];
extern u8 lit_3950[];
extern u8 lit_4372[];
extern u8 lit_4679[];
extern u8 lit_4680[];
extern u8 lit_4681[];
extern u8 lit_4682[];
extern u8 lit_4683[];
extern u8 lit_4684[];
extern u8 lit_4685[];
extern u8 lit_4686[];
extern u8 lit_4687[];
extern u8 lit_4688[];
extern u8 lit_4994[];
extern u8 lit_5208[];
extern u8 lit_5209[];
extern u8 lit_5387[];
extern u8 yn_dialog_cnt_tbl[];
extern char *yn_dialog_mes_tbl[];
extern char *yn_button_mes_tbl[];
extern char *yn_hard_more_mes_tbl[];
extern u8 yn_help_cnt_tbl[];
extern char *yn_help_mes_tbl[];
extern char *yn_memcard_mes_tbl[];
extern u8 yn_mess_cnt_tbl[];
extern char *yn_mess_mes_tbl[];
extern u8 yn_parts_data[];
typedef struct SPR { u8 b[12]; } SPR;
extern SPR yn_spr_data[];
extern char *yn_title_mes_tbl[];
extern u8 yn_uv_data[];
extern s8 BsProxyUseFlag;
extern s8 MyDialType;
extern s32 MyDns1;
extern s32 MyDns2;
extern s8 MyEtherInitMode;
extern s32 MyGateway;
extern s32 MyIPAddr;
extern s32 MyNetmask;
extern s8 NdgNegoMode;
extern s8 PppRecognize;
extern s32 SrvIPAddress;
extern s16 SrvPort;
extern s8 SrvType;
extern s32 flPs2GsHandler;
extern s32 yn_r_no;
extern s32 yn_type;
extern u8 * ynw;

s32 yn_set_main();
void yn_set_exit_sub();
s32 yn_file_search();
s32 yn_auto_connect();
s32 yn_select_provider();
void yn_common_shot_cancel();
s32 yn_common_memcard_out();
void yn_title_font();
void yn_message_font_sub();
void yn_connect_font_sub();
void yn_hard_font_sub();
void yn_hard_more_font_sub();
void yn_memcard_font_sub();
void yn_id_pw_font_sub();
void yn_ipadrs_font_sub();
void yn_port_font_sub();
void yn_prname_font_sub();
void yn_adname_font_sub();
void yn_dialog_draw();
void yn_dialog_font_sub();
void yn_dialog_font_without_yesno();
void yn_dialog_font_once();
void yn_dialog_font_memcard();
void yn_dialog_font_setting();
void yn_dialog_font_ip_sub();
void yn_help_font();
void yn_printf();
void yn_set_pal();
void yn_set_size();
void yn_set_z(f32 z);
void yn_set_halftype();
s32 yn_get_halftype();
int yn_center_x();
int yn_strlen();
void yn_strconv();
void yn_strconv2();
void yn_strcpy();
void yn_port_init();
void yn_key_repeat();
void yn_keyboard_init();
s32 yn_keyboard_sub();
void yn_keyboard_server();
void yn_draw();
void yn_view_set();
void yn_sprite_draw_sub();
void yn_sprite_draw_each();
void yn_setup_allwork();
void yn_backup_allwork();
void yn_proxy_wk_load();
void yn_proxy_wk_save();
int yn_load_texfile();
void yn_scecom_reboot();

#if 0 /* yn_auto_connect: m2c draft, does not compile yet */
#endif

#if 0 /* yn_common_shot_cancel: m2c draft, does not compile yet */
#endif

/*
Decompilation failure in function yn_sprite_draw:

Unable to determine jump table for jr instruction at tmpgya281qg.s line 18.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

/*
Decompilation failure in function yn_button_draw:

Unable to determine jump table for jr instruction at tmpfh_ao2x3.s line 18.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

/*
Decompilation failure in function yn_button_font:

Unable to determine jump table for jr instruction at tmpqoo3mo3s.s line 21.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

/*
Decompilation failure in function yn_message_font:

Unable to determine jump table for jr instruction at tmpwqzzu240.s line 21.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

#if 0 /* yn_message_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_hard_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_memcard_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_id_pw_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_ipadrs_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_port_font_sub: m2c draft, does not compile yet */
#endif

/*
Decompilation failure in function yn_dialog_font:

Unable to determine jump table for jr instruction at tmpujrimknu.s line 23.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

#if 0 /* yn_dialog_font_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_dialog_font_without_yesno: m2c draft, does not compile yet */
#endif

#if 0 /* yn_dialog_font_once: m2c draft, does not compile yet */
#endif

#if 0 /* yn_dialog_font_memcard: m2c draft, does not compile yet */
#endif

#if 0 /* yn_dialog_font_setting: m2c draft, does not compile yet */
#endif

#if 0 /* yn_dialog_font_ip_sub: m2c draft, does not compile yet */
#endif

#if 0 /* yn_help_font: m2c draft, does not compile yet */
#endif

/* matched as s16 in uc00.c */

typedef struct { s32 a; s32 b; } PR8;
typedef struct { s32 w[130]; } PR520;

/* Copy the 0x41 pairs of proxy settings (0x208 bytes) in the work area. */
#define PROXY_COPY(dst, src) \
    do { \
        PR8 *d_ = (PR8 *)(dst); \
        PR8 *s_ = (PR8 *)(src); \
        int n_ = 0x41; \
        s32 t_; \
        do { \
            n_--; \
            t_ = s_->b; \
            d_->a = s_->a; \
            s_++; \
            d_->b = t_; \
            d_++; \
        } while (n_ > 0); \
    } while (0)

typedef struct YNW_K { u8 _p[0x28]; s32 x28; u32 rep; } YNW_K;

/* Key repeat: x28 = pad bits to act on this frame, rep = frames held. */

#if 0 /* yn_keyboard_init: m2c draft, does not compile yet */
#endif

#if 0 /* yn_sprite_draw_each: m2c draft, does not compile yet */
#endif

extern s32 flPs2VIF1Control[];
extern char *args[2];

typedef struct YMSG {
    s16 x;              /* 0x00 -1 = centered */
    s16 y;              /* 0x02 */
    char *str;          /* 0x04 */
} YMSG;

void yn_button_draw(void) {
    s8 b;

    b = M2C_FIELD(ynw, s8 *, 0x43);
    switch (b) {
    case 1:
    case 2:
    case 3:
        yn_sprite_draw_sub(b - 1, 0, 0);
        break;
    case 4:
        yn_sprite_draw_sub(2, 0, 0);
        break;
    case 5:
        yn_sprite_draw_sub(3, 0, 0);
        break;
    case 0:
    default:
        break;
    }
}

void yn_common_shot_cancel(arg0)
s8 arg0;
{
    int t;

    M2C_FIELD(ynw, s8 *, 0x19) = M2C_FIELD(ynw, s8 *, 0x18);
    M2C_FIELD(ynw, s8 *, 0x18) = arg0;
    M2C_FIELD(ynw, s8 *, 0x17) = 0;
    if (yn_r_no == 6 && ((t = M2C_FIELD(ynw, s8 *, 0x19)) == 6 || t == 7)) {
        M2C_FIELD(ynw, s8 *, 0x46) = 0x38;
    } else {
        M2C_FIELD(ynw, s8 *, 0x46) = 1;
    }
    yn_can_sd();
}

void yn_dialog_font_once(s32 arg0) {
    YMSG *m;
    int x;
    m = (YMSG *)yn_dialog_mes_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    m += arg0;
    x = m->x;
    if (x == -1) {
        x = (s16)yn_center_x(m->str, 0x16);
    }
    yn_printf(x, m->y, m->str);
}

void yn_help_font(void) {
    int i;
    s8 n;
    int x;
    YMSG *m;

    n = yn_help_cnt_tbl[M2C_FIELD(ynw, s8 *, 0x47) + M2C_FIELD(ynw, s8 *, 0x48)];
    m = (YMSG *)yn_help_mes_tbl[M2C_FIELD(ynw, s8 *, 0x47) + M2C_FIELD(ynw, s8 *, 0x48)];
    for (i = 0; i < n; i = (s8)(i + 1), m++) {
        x = m->x;
        if (x == -1) {
            x = (s16)yn_center_x(m->str, 0x16);
        }
        yn_printf(x, m->y, m->str);
    }
}

void yn_message_font_sub(void) {
    int i;
    s8 n;
    int x;
    YMSG *m;

    n = yn_mess_cnt_tbl[M2C_FIELD(ynw, s8 *, 0x45)];
    m = (YMSG *)yn_mess_mes_tbl[M2C_FIELD(ynw, s8 *, 0x45)];
    for (i = 0; i < n; i = (s8)(i + 1), m++) {
        x = m->x;
        if (x == -1) {
            x = (s16)yn_center_x(m->str, 0x16);
        }
        yn_printf(x, m->y, m->str);
    }
}

void yn_dialog_font_sub(void) {
    int i;
    s8 n;
    int x;
    YMSG *m;

    n = yn_dialog_cnt_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    m = (YMSG *)yn_dialog_mes_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    for (i = 0; i < n; i = (s8)(i + 1), m++) {
        x = m->x;
        if (x == -1) {
            x = (s16)yn_center_x(m->str, 0x16);
        }
        yn_printf(x, m->y, m->str);
    }
}

void yn_dialog_font_without_yesno(void) {
    s8 n;
    YMSG *m;
    int i;
    int x;

    m = (YMSG *)yn_dialog_mes_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    n = ((s8 *)yn_dialog_cnt_tbl)[M2C_FIELD(ynw, u8 *, 0x46)] - 3;
    for (i = 0; i < n; i = (s8)(i + 1), m++) {
        x = m->x;
        if (x == -1) {
            x = (s16)yn_center_x(m->str, 0x16);
        }
        yn_printf(x, m->y, m->str);
    }
}

void yn_memcard_font_sub(void) {
    int i;
    char **p;
    int y;

    i = 0;
    p = yn_memcard_mes_tbl;
    y = 0xC4;
    do {
        if (M2C_FIELD(ynw, u8 *, 0x1D) & (1 << (s8)i)) {
            yn_set_pal(0);
        } else {
            yn_set_pal(9);
        }
        yn_printf(0xCF, (s16)y, p[1]);
        p++;
        i = (s8)(i + 1);
        y += 0x38;
    } while (i < 2);
    yn_set_pal(0);
}

void yn_button_font(void) {
    s8 b;
    char **tbl = yn_button_mes_tbl;

    b = M2C_FIELD(ynw, s8 *, 0x43);
    switch (b) {
    case 1:
        yn_printf(0x122, 0x18F, tbl[0]);
        break;
    case 2:
        yn_printf(0xF6, 0x18F, tbl[0]);
        yn_printf(0x17A, 0x18F, tbl[1]);
        break;
    case 3:
        yn_printf(0xB2, 0x18F, tbl[0]);
        yn_printf(0x122, 0x18F, tbl[1]);
        yn_printf(0x192, 0x18F, tbl[2]);
        break;
    case 4:
        yn_printf(0xB2, 0x18F, tbl[0]);
        yn_printf(0x122, 0x18F, tbl[1]);
        yn_printf(0x192, 0x18F, tbl[3]);
        break;
    case 5:
        yn_printf(0x122, 0x18F, tbl[4]);
        break;
    case 0:
    default:
        break;
    }
}

void yn_hard_font_sub(void) {
    u8 sp50[0x100];
    int j;
    int shown;
    u8 *p;
    int y;

    shown = 0;
    yn_set_pal(0);
    j = 0;
    p = DeviceWork;
    y = 0xC4;
    do {
        if (M2C_FIELD(p, s32 *, 0) != -1) {
            if (M2C_FIELD(p, s32 *, 0) == 1) {
                yn_set_pal(0);
            } else {
                yn_set_pal(9);
            }
            if (M2C_FIELD(p, s32 *, 0) == 1 && shown >= M2C_FIELD(ynw, s8 *, 0x15)) {
                sprintf(sp50, lit_4118, M2C_FIELD(p, s32 *, 0x14), M2C_FIELD(p, s32 *, 0x18));
                yn_printf(0x65, (s16)y, sp50);
                y += 0x1C;
            }
            shown++;
        }
        j++;
        p += 0x1C;
    } while (j < 0x23);
    yn_set_pal(0);
}

void yn_ipadrs_font_sub(u8 *arg0, int arg1, int arg2) {
    u8 buf[0x40];
    u8 o;
    int i;
    u8 *d;
    u8 h;
    u8 t;

    d = buf;
    i = 0;
    do {
        h = *arg0 / 100;
        t = (*arg0 / 10) % 10;
        o = *arg0 % 10;
        arg0++;
        if (h == 0) {
            *d++ = 0x20;
            if (t == 0) {
                *d++ = 0x20;
            } else {
                *d++ = t + 0x30;
            }
        } else {
            *d++ = h + 0x30;
            *d++ = t + 0x30;
        }
        *d++ = o + 0x30;
        i++;
        *d++ = 0x2E;
        *d++ = 0x20;
    } while (i < 4);
    d[-2] = 0;
    yn_printf(arg1, arg2, buf);
}

void yn_dialog_font_memcard(s32 arg0) {
    YMSG *m;
    int i;
    u8 sp60[0x100];
    s8 n;
    int x;

    n = yn_dialog_cnt_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    m = (YMSG *)yn_dialog_mes_tbl[M2C_FIELD(ynw, u8 *, 0x46)];
    for (i = 0; i < n; i = (s8)(i + 1), m++) {
        x = m->x;
        if (x == -1) {
            x = (s16)yn_center_x(m->str, 0x16);
        }
        if ((s8)i == arg0) {
            sprintf(sp60, m->str, yn_mc_get_current(ynw + 0x10D0) + 1);
            yn_printf(x, m->y, sp60);
        } else {
            yn_printf(x, m->y, m->str);
        }
    }
}

void yn_dialog_font_ip_sub(u8 *arg0, u8 *arg1) {
    int j;
    u8 buf[4];
    int k;
    int n;

    for (j = 0; j < 4; j++) {
        n = 0;
        while (*arg1 != 0x2E && *arg1 != 0) {
            buf[n] = *arg1;
            arg1++;
            n++;
        }
        for (k = n; k < 3; k++) {
            *arg0 = 0x20;
            arg0++;
        }
        for (k = 0; k < n; k++) {
            *arg0 = buf[k];
            arg0++;
        }
        *arg0 = *arg1;
        arg1++;
        arg0++;
    }
    *arg0 = 0;
}

void yn_id_pw_font_sub(void) {
    u8 sp50[0x40];
    u8 sp10[0x40];
    u8 *p;
    int n;
    int i;

    p = ynw + 0x4B4;
    if (*p == 0) {
        yn_printf(0x115, 0xC4, lit_4217);
    } else {
        sceNetcnfifConvAuthname(p, sp10, 0x20);
        yn_strconv(sp50, sp10, 0x18);
        yn_printf(0x115, 0xC4, sp50);
    }
    p = ynw + 0x6B4;
    if (*p == 0) {
        yn_printf(0x115, 0xFC, lit_4218);
        return;
    }
    n = yn_strlen(p);
    if (n > 0x18) {
        for (i = 0; i < 0x16; i++) {
            sp50[i] = 0x2A;
        }
        sp50[i++] = 0x2E;
        sp50[i++] = 0x2E;
        sp50[i] = 0;
    } else {
        for (i = 0; i < n; i++) {
            sp50[i] = 0x2A;
        }
        sp50[i] = 0;
    }
    yn_printf(0x115, 0xFC, sp50);
}

void yn_port_font_sub(u16 *arg0, int arg1, int arg2) {
    s8 d[8];
    u8 buf[0x48];
    int div;
    int i;
    int started;
    int cnt;
    int n;

    started = 0;
    cnt = 0;
    div = 10000;
    for (i = 0; i < 5; i++) {
        d[i] = (*arg0 / div) % 10;
        div = div / 10;
        if (d[i] != 0) {
            started = 1;
        }
        if (started != 0) {
            cnt++;
        }
    }
    if (cnt == 0) {
        cnt++;
    }
    if (M2C_FIELD(ynw, s8 *, 0x39) != 0 && M2C_FIELD(ynw, u16 **, 0x3C) == arg0) {
        for (i = 0; i < 13; i++) {
            buf[i] = 0x20;
        }
        buf[i] = 0x20;
        buf[i + 1] = d[0] + 0x30;
        buf[i + 2] = d[1] + 0x30;
        buf[i + 3] = d[2] + 0x30;
        buf[i + 4] = d[3] + 0x30;
        buf[i + 5] = d[4] + 0x30;
        buf[i + 6] = 0;
    } else {
        n = 0x12 - cnt;
        for (i = 0; i < n; i++) {
            buf[i] = 0x20;
        }
        sprintf(buf + n, lit_4358, *arg0);
    }
    yn_printf(arg1, arg2, buf);
}

void yn_dialog_font(void) {
    u8 id;

    yn_set_z(650.0f);
    id = M2C_FIELD(ynw, u8 *, 0x46);
    switch (id) {
    case 0x1:
    case 0x2:
    case 0x3:
    case 0x4:
    case 0x5:
    case 0x6:
    case 0x7:
    case 0xC:
    case 0xD:
    case 0xE:
    case 0xF:
    case 0x13:
    case 0x14:
    case 0x15:
    case 0x16:
    case 0x17:
    case 0x18:
    case 0x1A:
    case 0x1B:
    case 0x1E:
    case 0x23:
    case 0x2B:
    case 0x2C:
    case 0x2D:
    case 0x2F:
    case 0x30:
    case 0x31:
    case 0x32:
    case 0x35:
    case 0x36:
    case 0x37:
    case 0x38:
    case 0x39:
        yn_dialog_font_sub();
        break;
    case 0x8:
    case 0x1F:
    case 0x2E:
        yn_dialog_font_memcard(2);
        break;
    case 0x9:
    case 0xA:
        yn_dialog_font_memcard(0);
        break;
    case 0xB:
        yn_dialog_font_memcard(1);
        break;
    case 0x1C:
    case 0x33:
        yn_dialog_font_memcard(0);
        break;
    case 0x1D:
        yn_dialog_font_memcard(0);
        break;
    case 0x20:
        yn_dialog_font_memcard(0);
        break;
    case 0x21:
        yn_dialog_font_memcard(0);
        break;
    case 0x22:
        yn_dialog_font_memcard(0);
        break;
    case 0x34:
        yn_dialog_font_memcard(0);
        break;
    case 0x10:
    case 0x11:
    case 0x12:
    case 0x25:
    case 0x26:
    case 0x27:
    case 0x28:
    case 0x29:
        if (M2C_FIELD(ynw, s8 *, 0x1B) == 3) {
            yn_dialog_font_without_yesno();
        } else {
            yn_dialog_font_sub();
        }
        break;
    case 0x19:
        yn_dialog_font_sub();
        yn_dialog_font_setting();
        break;
    case 0x24:
    case 0x2A:
        yn_dialog_font_once(0);
        yn_dialog_font_once(1);
        if (M2C_FIELD(ynw, u8 *, 0x21) & 0x20) {
            yn_dialog_font_once(2);
        }
        break;
    }
    yn_set_z(850.0f);
}

void yn_message_font(void) {
    s8 id;
    int i;
    int y;
    int idx;

    id = M2C_FIELD(ynw, s8 *, 0x45);
    switch (id) {
    case 1:
        yn_connect_font_sub();
        yn_message_font_sub();
        return;
    case 3:
    case 4:
    case 5:
    case 6:
    case 21:
        yn_memcard_font_sub();
        yn_message_font_sub();
        return;
    case 7:
        yn_message_font_sub();
        yn_hard_font_sub();
        return;
    case 9:
        yn_message_font_sub();
        yn_id_pw_font_sub();
        return;
    case 11:
        yn_ipadrs_font_sub(ynw + 0xAB4, 0x157, 0xC4);
        yn_ipadrs_font_sub(ynw + 0xAB8, 0x157, 0xE0);
        yn_ipadrs_font_sub(ynw + 0xABC, 0x157, 0xFC);
        yn_message_font_sub();
        return;
    case 13:
        yn_ipadrs_font_sub(ynw + 0xAC0, 0x157, 0xC4);
        yn_ipadrs_font_sub(ynw + 0xAC4, 0x157, 0xFC);
        yn_message_font_sub();
        return;
    case 14:
        yn_adname_font_sub(ynw + 0x8B4, lit_3947, 0x115, 0xE0);
        yn_message_font_sub();
        return;
    case 15:
        yn_adname_font_sub(ynw + 0xAC8, lit_3948, 0x115, 0xE0);
        yn_message_font_sub();
        return;
    case 16:
    case 17:
    case 18:
        i = 0;
        y = 0xC4;
        do {
            idx = M2C_FIELD(ynw, s8 *, 0x16) + i;
            if (idx < M2C_FIELD(ynw, s8 *, 0x1C)) {
                yn_prname_font_sub(yn_netcnf_search_usr_name(ynw + 0x1180, ynw + idx * 0x1340 + 0xAF00), idx, 0x65, (s16)y);
            }
            i++;
            y += 0x1C;
        } while (i < 3);
        yn_message_font_sub();
        return;
    case 23:
        yn_adname_font_sub(ynw + 0xED0, lit_3949, 0x157, 0xBA);
        yn_adname_font_sub(ynw + 0xFD0, lit_3950, 0x157, 0xEA);
        yn_port_font_sub((u16 *)(ynw + 0xECC), 0x157, 0xD2);
        yn_port_font_sub((u16 *)(ynw + 0xECE), 0x157, 0x102);
        yn_message_font_sub();
        return;
    case 24:
        yn_hard_more_font_sub();
        yn_message_font_sub();
        return;
    default:
        yn_message_font_sub();
        return;
    }
}

void yn_keyboard_init(int arg0, u8 *arg1) {
    u8 *buf;

    flfntInit();
    buf = ynw + 0x50;
    memset(buf, 0, 0x200);
    M2C_FIELD(ynw, u8 **, 0x4C) = arg1;
    strcpy(buf, arg1);
    printf(lit_4994, strlen(arg1), arg1);
    printf(lit_4994, strlen(buf), buf);
    SoftKey_onoff(1);
    switch (arg0) {
    case 0:
        Net_kb_input_init2(0x60, 0x12A, buf, 0xFF, 3);
        break;
    case 1:
        Net_kb_input_init2(0x60, 0x12A, buf, 0xFF, 4);
        break;
    case 2:
        Net_kb_input_init2(0x60, 0x12A, buf, 0xFF, 5);
        break;
    }
}

void yn_dialog_font_setting(void) {
    u8 sp250[0x200];
    u8 sp50[0x200];
    u8 *e;
    u8 *d;
    int sel;
    int y;
    u8 *p;

    y = 0x82;
    e = ynw + M2C_FIELD(ynw, s8 *, 0xB) * 0x14;
    d = M2C_FIELD(e, u8 **, 0x260);
    p = e + 0x250;
    if (M2C_FIELD(e, s32 *, 0x250) == 1) {
        sprintf(sp250, lit_4679, M2C_FIELD(p, u8 **, 8), M2C_FIELD(p, s32 *, 0xC));
        yn_strconv(sp50, sp250, 0x2E);
    } else {
        yn_set_pal(2);
        strcpy(sp50, lit_4680);
    }
    yn_set_pal(0);
    yn_printf(0x44, y, sp50);
    y += 0x19;
    if (d != NULL && M2C_FIELD(e, s32 *, 0x250) == 1) {
        switch (M2C_FIELD(d, s32 *, 0x1310)) {
        case 1:
            sel = 0;
            break;
        case 2:
            sel = 1;
            break;
        case 3:
            sel = 2;
            break;
        case 5:
            sel = 3;
            break;
        case 6:
            sel = 4;
            break;
        }
        sprintf(sp250, lit_4681, yn_hard_more_mes_tbl[sel]);
        yn_strconv(sp50, sp250, 0x2C);
        yn_printf(0x44, (s16)y, sp50);
        y += 0x19;
        if (M2C_FIELD(d, u8 *, 0x1325) == 1) {
            yn_strconv(sp250, d + 0xB00, 0x1C);
            sceNetcnfifConvAuthname(sp250, sp50, 0x100);
            sprintf(sp250, lit_4682, sp50);
            yn_printf(0x44, (s16)y, sp250);
            y += 0x19;
        } else if (M2C_FIELD(d, u8 *, 0x1320) == 1) {
            if (M2C_FIELD(d, s8 *, 0x200) == 0) {
                strcpy(sp250, lit_160_0053EA40);
            } else {
                yn_strconv(sp250, d + 0x200, 0x1C);
            }
            sprintf(sp50, lit_4683, sp250);
            yn_printf(0x44, (s16)y, sp50);
            y += 0x19;
        } else if (M2C_FIELD(d, s8 *, 0x300) != 0) {
            yn_dialog_font_ip_sub(sp50, d + 0x300);
            sprintf(sp250, lit_4684, sp50);
            yn_printf(0x44, (s16)y, sp250);
            y += 0x19;
            yn_dialog_font_ip_sub(sp50, d + 0x400);
            sprintf(sp250, lit_4685, sp50);
            yn_printf(0x44, (s16)y, sp250);
            y += 0x19;
            yn_dialog_font_ip_sub(sp50, d + 0x500);
            sprintf(sp250, lit_4686, sp50);
            yn_printf(0x44, (s16)y, sp250);
            y += 0x19;
        }
        if (M2C_FIELD(d, s8 *, 0x600) == 0) {
            strcpy(sp250, lit_160_0053EA40);
        } else {
            yn_dialog_font_ip_sub(sp250, d + 0x600);
        }
        sprintf(sp50, lit_4687, sp250);
        yn_printf(0x44, (s16)y, sp50);
        if (M2C_FIELD(d, s8 *, 0x700) == 0) {
            if (*(s8 *)(d + 0x600) == 0) {
                strcpy(sp250, lit_160_0053EA40);
            } else {
                strcpy(sp250, lit_4372);
            }
        } else {
            yn_dialog_font_ip_sub(sp250, d + 0x700);
        }
        sprintf(sp50, lit_4688, sp250);
        yn_printf(0x44, (s16)(y + 0x19), sp50);
    }
}

void yn_sprite_draw_sub(int arg0, int arg1, int arg2) {
    int i;
    u8 sel;
    u32 t;
    f32 a;
    SPR *s;
    u8 cnt;
    i = arg0 * 4;
    cnt = yn_parts_data[i + 1];
    s = yn_spr_data + yn_parts_data[i];
    yn_sprite_draw_each(s, cnt, arg1, arg2, -1);
    sel = yn_parts_data[i + 3];
    if (sel != 0) {
        flSetRenderState(0x5E, 0x12);
        s = yn_spr_data + yn_parts_data[i + 2];
        t = M2C_FIELD(ynw, u8 *, 0x21);
        a = 128.0f + 127.0f * flSin(3.1415927f * (f32)t / 2.0f / 16.0f);
        yn_sprite_draw_each(s, sel, arg1, arg2, ((u8)(u32)a << 24) | 0xFFFFFF);
        flSetRenderState(0x5E, 0x32);
    }
}

#define YS8(o) M2C_FIELD(ynw, s8 *, o)
#define YU8(o) M2C_FIELD(ynw, u8 *, o)

/* Draw the dialog parts for the current screen (ynw+0x42). */
void yn_sprite_draw(void) {
    int v;

    switch (YS8(0x42)) {
    case 1:
        yn_sprite_draw_sub(5, 0, 0);
        if (YS8(0x1C) > 2) {
            yn_sprite_draw_sub(0x1F, 0, 0);
        }
        v = YS8(8);
        if (v < 2) {
            yn_sprite_draw_sub(7, 0, (s16)(v * 0x1A));
        } else {
            yn_sprite_draw_sub(7, 0, (s16)((YS8(0xB) - YS8(0xC)) * 0x1C + 0x3F));
        }
        break;
    case 2:
        yn_sprite_draw_sub(0x21, 0, 0);
        yn_sprite_draw_sub(8, 0, (s16)(YS8(8) * 0x28));
        break;
    case 3:
        yn_sprite_draw_sub(0xA, 0, 0);
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(9, 0, (s16)(YS8(9) * 0x38));
        break;
    case 4:
        yn_sprite_draw_sub(0xB, 0, 0);
        if (YU8(0x1F) >= 4) {
            yn_sprite_draw_sub(0xE, 0, 0);
            yn_sprite_draw_sub(0xF, 0, 0);
        }
        yn_sprite_draw_sub(0x12, 0, (s16)((YS8(0xA) - YS8(0x15)) * 0x1C));
        break;
    case 17:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0xE, 0, 0);
        yn_sprite_draw_sub(0xF, 0, 0);
        v = YU8(0x4B0) - YS8(0x14);
        if (v >= 0 && v < 3) {
            yn_sprite_draw_sub(0x10, 0, (s16)(v * 0x1C));
        }
        yn_sprite_draw_sub(0x11, 0, (s16)((YS8(0x12) - YS8(0x14)) * 0x1C));
        break;
    case 5:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0x13, 0, (s16)(YU8(0x4AD) * 0x38));
        yn_sprite_draw_sub(0x14, 0, (s16)(YS8(0xB) * 0x38));
        break;
    case 6:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        if (YU8(0x4B4) != 0 && YU8(0x6B4) != 0) {
            yn_sprite_draw_sub(0xD, 0, 0);
        }
        yn_sprite_draw_sub(0x12, 0, (s16)(YS8(0xC) * 0x38));
        break;
    case 7:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0x15, 0, (s16)(YU8(0x4AE) * 0x38));
        yn_sprite_draw_sub(0x16, 0, (s16)(YS8(0xD) * 0x38));
        break;
    case 8:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        if (yn_netcnf_ip_check(ynw + 0xAB4) != 0 && yn_netcnf_ip_check(ynw + 0xAB8) != 0 &&
            yn_netcnf_ip_check(ynw + 0xABC) != 0) {
            yn_sprite_draw_sub(0xD, 0, 0);
        }
        if (YS8(0x39) == 0) {
            yn_sprite_draw_sub(0x12, 0, (s16)(YS8(0xE) * 0x1C));
        } else {
            yn_sprite_draw_sub(0x17, (s16)(YS8(0x38) * 0x37), (s16)(YS8(0xE) * 0x1C));
        }
        break;
    case 9:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0x18, 0, (s16)(YU8(0x4AF) * 0x38));
        yn_sprite_draw_sub(0x19, 0, (s16)(YS8(0xF) * 0x38));
        break;
    case 10:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        if (yn_netcnf_ip_check(ynw + 0xAC0) != 0) {
            yn_sprite_draw_sub(0xD, 0, 0);
        }
        if (YS8(0x39) == 0) {
            yn_sprite_draw_sub(0x12, 0, (s16)(YS8(0x10) * 0x38));
        } else {
            yn_sprite_draw_sub(0x17, (s16)(YS8(0x38) * 0x37), (s16)(YS8(0x10) * 0x38));
        }
        break;
    case 11:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        if (YU8(0xAC8) != 0) {
            yn_sprite_draw_sub(0xD, 0, 0);
        }
        yn_sprite_draw_sub(0x12, 0, 0x1C);
        break;
    case 14:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0x12, 0, 0x1C);
        break;
    case 12:
        yn_sprite_draw_sub(0xA, 0, 0);
        break;
    case 13:
        yn_sprite_draw_sub(0xB, 0, 0);
        if (YS8(0x1C) > 3) {
            yn_sprite_draw_sub(0xE, 0, 0);
            yn_sprite_draw_sub(0xF, 0, 0);
        }
        v = YS8(0x11) - YS8(0x16);
        if (v < 2) {
            yn_sprite_draw_sub(0x12, 0, (s16)(v * 0x1C));
        } else {
            yn_sprite_draw_sub(0x12, 0, (s16)(v * 0x1C + 2));
        }
        break;
    case 15:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xD, 0, 0);
        yn_sprite_draw_sub(0x13, 0, (s16)((1 - M2C_FIELD(ynw, s32 *, 0xEC8)) * 0x38));
        yn_sprite_draw_sub(0x14, 0, (s16)(YS8(0xD) * 0x38));
        break;
    case 16:
        yn_sprite_draw_sub(0xB, 0, 0);
        yn_sprite_draw_sub(0xC, 0, 0);
        if (YU8(0xED0) != 0 && M2C_FIELD(ynw, u16 *, 0xECC) != 0) {
            yn_sprite_draw_sub(0xD, 0, 0);
        }
        switch (YS8(0x39)) {
        case 0:
        case 1:
            yn_sprite_draw_sub(0x12, 0, (s16)(YS8(0xE) * 0x18 - 0xA));
            break;
        case 2:
            yn_sprite_draw_sub(0x1C, 0x60, (s16)(YS8(0xE) * 0x18 - 0x18));
            v = YS8(0x38);
            yn_sprite_draw_sub(0x1D, (s16)(0x76 - v * 0xB), (s16)(YS8(0xE) * 0x18 - 0x18));
            break;
        }
        break;
    default:
        return;
    }
    yn_sprite_draw_sub(4, 0, 0);
    yn_sprite_draw_sub(6, 0, 0);
}

/* Draw count sprite cells (12 bytes each: x, y, w, h, uv index, rotation) at an offset with a color. */
void yn_sprite_draw_each(u8 *spr, int count, int ox, int oy, int col) {
    struct { s16 x, y, w, h; s32 col; s16 u0, v0, u1, v1; } rect;
    int i;
    u8 *t;
    s16 a;
    s16 b;
    s16 c;
    s16 d;
    s16 p;
    s16 q;

    for (i = 0; i < count; i++) {
        t = yn_uv_data + (s16)(M2C_FIELD(spr, s16 *, 8) * 4) * 2;
        a = M2C_FIELD(t, s16 *, 0);
        b = M2C_FIELD(t, s16 *, 2);
        c = M2C_FIELD(t, s16 *, 4);
        d = M2C_FIELD(t, s16 *, 6);
        switch (M2C_FIELD(spr, s16 *, 0xA)) {
        case 0:
            p = (s16)(a + c);
            q = (s16)(b + d);
            break;
        case 1:
            p = a;
            a = p + c;
            q = (s16)(b + d);
            break;
        case 2:
            p = (s16)(a + c);
            q = b;
            b = q + d;
            break;
        case 3:
            p = a;
            q = b;
            a = p + c;
            b = q + d;
            break;
        }
        rect.x = M2C_FIELD(spr, s16 *, 0) + (s16)ox;
        rect.y = M2C_FIELD(spr, s16 *, 2) + (s16)oy;
        rect.w = M2C_FIELD(spr, s16 *, 4);
        rect.h = M2C_FIELD(spr, s16 *, 6);
        rect.u0 = a;
        rect.v0 = b;
        rect.u1 = p;
        rect.v1 = q;
        rect.col = col;
        net_flps0008(&rect);
        spr += 12;
    }
}
