/* ui31 - yn.bin 0x00535DC0-0x005360D8: yn_auto_connect (state machine that picks a saved network setting from the memory cards). Draft in ui3_nm.c. */
/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int ADXM_ShutdownThrd();
int ADXPS2_LoadFcacheDvd();
int ADXT_Finish();
int DIntr();
int DisableDmac();
int DisableIntc();
int EIntr();
int InetIPAddrFromString();
int LoadExecPS2();
int Net_kb_input_init2();
int Net_kb_input_sub();
int RemoveDmacHandler();
int RemoveIntcHandler();
int SetFilterMode();
int SoftKey_Getstr();
int SoftKey_onoff();
int SoftKey_trans();
int YnFile_Data_load();
int flCreateTextureFromTim2_mem();
int flPADDestroy();
int flPS2DmaWait();
int flReleasePaletteHandle();
int flReleaseTextureHandle();
int flSetRenderState();
f32 flSin(f32 x);
int flfntDraw();
int flfntInit();
int flfntLocate();
int flfntPrintf();
int flfntSetHalftype();
int flfntSetPalette();
int flfntSetSize();
void flfntSetZ(f32 z);
int net_flps0008();
int printf();
int sceCdInit();
int sceGsSyncPath();
int sceGsSyncVCallback();
int sceNetcnfifConvAuthname();
int sceSifExitCmd();
int str_stop_all();
int yn_can_sd();
int yn_cur1_sd();
int yn_cur2_sd();
int yn_dec_sd();
int yn_hard_init();
int yn_hard_select_set();
int yn_log_sd();
int yn_mc_device_check_all();
int yn_mc_format();
int yn_mc_get_current();
int yn_mc_gmfile_check();
int yn_mc_gmfile_current_set();
int yn_mc_gmfile_save();
int yn_mc_init();
int yn_mc_set_current();
int yn_mc_ynfile_check();
int yn_netcnf_dev_to_work();
int yn_netcnf_exit();
int yn_netcnf_get_filename();
int yn_netcnf_get_list();
int yn_netcnf_get_num();
int yn_netcnf_ifc_to_work();
int yn_netcnf_init1();
int yn_netcnf_init2();
int yn_netcnf_magicno_check();
int yn_netcnf_net_allload();
int yn_netcnf_pastdata_check();
int yn_netcnf_pastproxy_check();
int yn_netcnf_search_usr_name();
int yn_netcnf_set_current();
int yn_netcnf_setup_devwork();
int yn_ng_sd();
int yn_set_init();
int yn_stop_bgm();
int yn_utf8_to_sjis();
extern u8 BsProxyUrlstr[];
extern u8 BsProxyUrlstr_S[];
extern u8 D_530394[];
extern u8 D_5306B0[];
extern u8 D_5310D0[];
extern u8 DeviceWork[];
extern u8 MyDialNumber[];
extern u8 MyDialOutline[];
extern u8 MyDomain[];
extern u8 MyPassword[];
extern u8 MyUserName[];
extern u8 Psw[];
extern u8 SrvDomain[];
extern u8 Yn_temp[];
extern u8 lit_160_0053EA40[];
extern u8 lit_4084[];
extern u8 lit_4085[];
extern u8 lit_4086[];
extern u8 lit_4087[];
extern u8 lit_4118[];
extern u8 lit_4217[];
extern u8 lit_4218[];
extern u8 lit_4358[];
extern u8 lit_4994[];
extern u8 lit_3947[];
extern u8 lit_3948[];
extern u8 lit_3949[];
extern u8 lit_3950[];
extern u8 lit_4372[];
extern u8 lit_4679[];
extern u8 lit_4680[];
extern u8 lit_4681[];
extern u8 lit_4682[];
extern u8 lit_4683[];
extern u8 lit_4684[];
extern u8 lit_4685[];
extern u8 lit_4686[];
extern u8 lit_4687[];
extern u8 lit_4688[];
extern u8 lit_4994[];
extern u8 lit_5208[];
extern u8 lit_5209[];
extern u8 lit_5387[];
extern u8 yn_dialog_cnt_tbl[];
extern char *yn_dialog_mes_tbl[];
extern char *yn_button_mes_tbl[];
extern char *yn_hard_more_mes_tbl[];
extern u8 yn_help_cnt_tbl[];
extern char *yn_help_mes_tbl[];
extern char *yn_memcard_mes_tbl[];
extern u8 yn_mess_cnt_tbl[];
extern char *yn_mess_mes_tbl[];
extern u8 yn_parts_data[];
typedef struct SPR { u8 b[12]; } SPR;
extern SPR yn_spr_data[];
extern char *yn_title_mes_tbl[];
extern u8 yn_uv_data[];
extern s8 BsProxyUseFlag;
extern s8 MyDialType;
extern s32 MyDns1;
extern s32 MyDns2;
extern s8 MyEtherInitMode;
extern s32 MyGateway;
extern s32 MyIPAddr;
extern s32 MyNetmask;
extern s8 NdgNegoMode;
extern s8 PppRecognize;
extern s32 SrvIPAddress;
extern s16 SrvPort;
extern s8 SrvType;
extern s32 flPs2GsHandler;
extern s32 yn_r_no;
extern s32 yn_type;
extern u8 * ynw;

s32 yn_set_main();
void yn_set_exit_sub();
s32 yn_file_search();
s32 yn_auto_connect();
s32 yn_select_provider();
void yn_common_shot_cancel();
s32 yn_common_memcard_out();
void yn_title_font();
void yn_message_font_sub();
void yn_connect_font_sub();
void yn_hard_font_sub();
void yn_hard_more_font_sub();
void yn_memcard_font_sub();
void yn_id_pw_font_sub();
void yn_ipadrs_font_sub();
void yn_port_font_sub();
void yn_prname_font_sub();
void yn_adname_font_sub();
void yn_dialog_draw();
void yn_dialog_font_sub();
void yn_dialog_font_without_yesno();
void yn_dialog_font_once();
void yn_dialog_font_memcard();
void yn_dialog_font_setting();
void yn_dialog_font_ip_sub();
void yn_help_font();
void yn_printf();
void yn_set_pal();
void yn_set_size();
void yn_set_z(f32 z);
void yn_set_halftype();
s32 yn_get_halftype();
int yn_center_x();
int yn_strlen();
void yn_strconv();
void yn_strconv2();
void yn_strcpy();
void yn_port_init();
void yn_key_repeat();
void yn_keyboard_init();
s32 yn_keyboard_sub();
void yn_keyboard_server();
void yn_draw();
void yn_view_set();
void yn_sprite_draw_sub();
void yn_sprite_draw_each();
void yn_setup_allwork();
void yn_backup_allwork();
void yn_proxy_wk_load();
void yn_proxy_wk_save();
int yn_load_texfile();
void yn_scecom_reboot();

#define YS8(o) M2C_FIELD(ynw, s8 *, o)
#define YU8(o) M2C_FIELD(ynw, u8 *, o)
#define PAD (*(u16 *)0x3F3714)

/* Auto connect: pick the saved network setting of the first memory card that has one. */
s32 yn_auto_connect(void) {
    s32 r;
    s32 n;
    int off;
    u8 f;

    switch (YS8(0x18)) {
    case 0:
        YS8(0x18) = YS8(0x18) + 1;
        YU8(0x1E) = 0;
        YU8(0x25) = 0;
    case 1:
        if (yn_netcnf_pastproxy_check(ynw + 0xEC8, D_5310D0) < 0) {
            return -4;
        }
        YS8(0x18) = YS8(0x18) + 1;
        YS8(0x24) = 0;
        break;
    case 2:
        r = yn_file_search();
        if (r == 1) {
            n = yn_netcnf_pastdata_check(D_5306B0, ynw + 0x250, YS8(0x1C));
            if (n >= 0) {
                off = n * 0x14;
                if (M2C_FIELD(off + (int)ynw, s32 *, 0x254) < 0) {
                    return -3;
                }
                if (yn_hard_select_set(M2C_FIELD(off + (int)ynw, s32 *, 0x254)) < 0) {
                    return -3;
                }
                yn_backup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
                yn_setup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
                YS8(0x18) = 5;
                YS8(0x46) = 0x34;
                yn_log_sd(5);
                break;
            }
        } else if (r == -2) {
            return -2;
        } else if (r == 0) {
            break;
        }
        f = YU8(0x25);
        if (f & 0x80) {
            if (f & (1 << YU8(0x1E))) {
                return -1;
            }
        } else {
            YU8(0x25) = f | 0x80;
        }
        YU8(0x25) = YU8(0x25) | ((1 << YU8(0x1E)) & 0xFF);
        if (yn_netcnf_magicno_check(ynw + 0x1180) != 0) {
            YS8(0x18) = 4;
            YS8(0x46) = 0x1D;
            yn_log_sd(4);
            yn_mc_init(ynw + 0x10D0);
        } else {
            YS8(0x18) = 3;
        }
        break;
    case 3:
        YS8(0x18) = 2;
        YS8(0x24) = 0;
        YU8(0x1E) = YU8(0x1E) + 1;
        YU8(0x1E) = YU8(0x1E) & 1;
        break;
    case 4:
        if (yn_common_memcard_out() != 0) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            return -6;
        }
        if (PAD & 0x20) {
            YS8(0x18) = 3;
            YS8(0x46) = 0;
            yn_dec_sd();
        }
        break;
    case 5:
        if (PAD & 0x20) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            yn_dec_sd();
            return 1;
        }
        break;
    }
    return 0;
}
