/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int ADXM_ShutdownThrd();
int ADXPS2_LoadFcacheDvd();
int ADXT_Finish();
int DIntr();
int DisableDmac();
int DisableIntc();
int EIntr();
int InetIPAddrFromString();
int LoadExecPS2();
int Net_kb_input_init2();
int Net_kb_input_sub();
int RemoveDmacHandler();
int RemoveIntcHandler();
int SetFilterMode();
int SoftKey_Getstr();
int SoftKey_onoff();
int SoftKey_trans();
int YnFile_Data_load();
int flCreateTextureFromTim2_mem();
int flPADDestroy();
int flPS2DmaWait();
int flReleasePaletteHandle();
int flReleaseTextureHandle();
int flSetRenderState();
f32 flSin(f32 x);
int flfntDraw();
int flfntInit();
int flfntLocate();
int flfntPrintf();
int flfntSetHalftype();
int flfntSetPalette();
int flfntSetSize();
void flfntSetZ(f32 z);
int net_flps0008();
int printf();
int sceCdInit();
int sceGsSyncPath();
int sceGsSyncVCallback();
int sceNetcnfifConvAuthname();
int sceSifExitCmd();
int str_stop_all();
int yn_can_sd();
int yn_cur1_sd();
int yn_cur2_sd();
int yn_dec_sd();
int yn_hard_init();
int yn_hard_select_set();
int yn_log_sd();
int yn_mc_device_check_all();
int yn_mc_format();
int yn_mc_get_current();
int yn_mc_gmfile_check();
int yn_mc_gmfile_current_set();
int yn_mc_gmfile_save();
int yn_mc_init();
int yn_mc_set_current();
int yn_mc_ynfile_check();
int yn_netcnf_dev_to_work();
int yn_netcnf_exit();
int yn_netcnf_get_filename();
int yn_netcnf_get_list();
int yn_netcnf_get_num();
int yn_netcnf_ifc_to_work();
int yn_netcnf_init1();
int yn_netcnf_init2();
int yn_netcnf_magicno_check();
int yn_netcnf_net_allload();
int yn_netcnf_pastdata_check();
int yn_netcnf_pastproxy_check();
int yn_netcnf_search_usr_name();
int yn_netcnf_set_current();
int yn_netcnf_setup_devwork();
int yn_ng_sd();
int yn_set_init();
int yn_stop_bgm();
int yn_utf8_to_sjis();
extern u8 BsProxyUrlstr[];
extern u8 BsProxyUrlstr_S[];
extern u8 D_530394[];
extern u8 D_5306B0[];
extern u8 D_5310D0[];
extern u8 DeviceWork[];
extern u8 MyDialNumber[];
extern u8 MyDialOutline[];
extern u8 MyDomain[];
extern u8 MyPassword[];
extern u8 MyUserName[];
extern u8 Psw[];
extern u8 SrvDomain[];
extern u8 Yn_temp[];
extern u8 lit_160_0053EA40[];
extern u8 lit_4084[];
extern u8 lit_4085[];
extern u8 lit_4086[];
extern u8 lit_4087[];
extern u8 lit_4118[];
extern u8 lit_4217[];
extern u8 lit_4218[];
extern u8 lit_4358[];
extern u8 lit_4994[];
extern u8 lit_3947[];
extern u8 lit_3948[];
extern u8 lit_3949[];
extern u8 lit_3950[];
extern u8 lit_4372[];
extern u8 lit_4679[];
extern u8 lit_4680[];
extern u8 lit_4681[];
extern u8 lit_4682[];
extern u8 lit_4683[];
extern u8 lit_4684[];
extern u8 lit_4685[];
extern u8 lit_4686[];
extern u8 lit_4687[];
extern u8 lit_4688[];
extern u8 lit_4994[];
extern u8 lit_5208[];
extern u8 lit_5209[];
extern u8 lit_5387[];
extern u8 yn_dialog_cnt_tbl[];
extern char *yn_dialog_mes_tbl[];
extern char *yn_button_mes_tbl[];
extern char *yn_hard_more_mes_tbl[];
extern u8 yn_help_cnt_tbl[];
extern char *yn_help_mes_tbl[];
extern char *yn_memcard_mes_tbl[];
extern u8 yn_mess_cnt_tbl[];
extern char *yn_mess_mes_tbl[];
extern u8 yn_parts_data[];
typedef struct SPR { u8 b[12]; } SPR;
extern SPR yn_spr_data[];
extern char *yn_title_mes_tbl[];
extern u8 yn_uv_data[];
extern s8 BsProxyUseFlag;
extern s8 MyDialType;
extern s32 MyDns1;
extern s32 MyDns2;
extern s8 MyEtherInitMode;
extern s32 MyGateway;
extern s32 MyIPAddr;
extern s32 MyNetmask;
extern s8 NdgNegoMode;
extern s8 PppRecognize;
extern s32 SrvIPAddress;
extern s16 SrvPort;
extern s8 SrvType;
extern s32 flPs2GsHandler;
extern s32 yn_r_no;
extern s32 yn_type;
extern u8 * ynw;

s32 yn_set_main();
void yn_set_exit_sub();
s32 yn_file_search();
s32 yn_auto_connect();
s32 yn_select_provider();
void yn_common_shot_cancel();
s32 yn_common_memcard_out();
void yn_title_font();
void yn_message_font_sub();
void yn_connect_font_sub();
void yn_hard_font_sub();
void yn_hard_more_font_sub();
void yn_memcard_font_sub();
void yn_id_pw_font_sub();
void yn_ipadrs_font_sub();
void yn_port_font_sub();
void yn_prname_font_sub();
void yn_adname_font_sub();
void yn_dialog_draw();
void yn_dialog_font_sub();
void yn_dialog_font_without_yesno();
void yn_dialog_font_once();
void yn_dialog_font_memcard();
void yn_dialog_font_setting();
void yn_dialog_font_ip_sub();
void yn_help_font();
void yn_printf();
void yn_set_pal();
void yn_set_size();
void yn_set_z(f32 z);
void yn_set_halftype();
s32 yn_get_halftype();
int yn_center_x();
int yn_strlen();
void yn_strconv();
void yn_strconv2();
void yn_strcpy();
void yn_port_init();
void yn_key_repeat();
void yn_keyboard_init();
s32 yn_keyboard_sub();
void yn_keyboard_server();
void yn_draw();
void yn_view_set();
void yn_sprite_draw_sub();
void yn_sprite_draw_each();
void yn_setup_allwork();
void yn_backup_allwork();
void yn_proxy_wk_load();
void yn_proxy_wk_save();
int yn_load_texfile();
void yn_scecom_reboot();

#define YS8(o) M2C_FIELD(ynw, s8 *, o)
#define YU8(o) M2C_FIELD(ynw, u8 *, o)
#define PAD (*(u16 *)0x3F3714)

/* Auto connect: pick the saved network setting of the first memory card that has one. */
s32 yn_auto_connect(void) {
    s32 r;
    s32 n;
    int off;
    u8 f;

    switch (YS8(0x18)) {
    case 0:
        YS8(0x18) = YS8(0x18) + 1;
        YU8(0x1E) = 0;
        YU8(0x25) = 0;
    case 1:
        if (yn_netcnf_pastproxy_check(ynw + 0xEC8, D_5310D0) < 0) {
            return -4;
        }
        YS8(0x18) = YS8(0x18) + 1;
        YS8(0x24) = 0;
        break;
    case 2:
        r = yn_file_search();
        if (r == 1) {
            n = yn_netcnf_pastdata_check(D_5306B0, ynw + 0x250, YS8(0x1C));
            if (n >= 0) {
                off = n * 0x14;
                if (M2C_FIELD(off + (int)ynw, s32 *, 0x254) < 0) {
                    return -3;
                }
                if (yn_hard_select_set(M2C_FIELD(off + (int)ynw, s32 *, 0x254)) < 0) {
                    return -3;
                }
                yn_backup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
                yn_setup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
                YS8(0x18) = 5;
                YS8(0x46) = 0x34;
                yn_log_sd(5);
                break;
            }
        } else if (r == -2) {
            return -2;
        } else if (r == 0) {
            break;
        }
        f = YU8(0x25);
        if (f & 0x80) {
            if (f & (1 << YU8(0x1E))) {
                return -1;
            }
        } else {
            YU8(0x25) = f | 0x80;
        }
        YU8(0x25) = YU8(0x25) | ((1 << YU8(0x1E)) & 0xFF);
        if (yn_netcnf_magicno_check(ynw + 0x1180) != 0) {
            YS8(0x18) = 4;
            YS8(0x46) = 0x1D;
            yn_log_sd(4);
            yn_mc_init(ynw + 0x10D0);
        } else {
            YS8(0x18) = 3;
        }
        break;
    case 3:
        YS8(0x18) = 2;
        YS8(0x24) = 0;
        YU8(0x1E) = YU8(0x1E) + 1;
        YU8(0x1E) = YU8(0x1E) & 1;
        break;
    case 4:
        if (yn_common_memcard_out() != 0) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            return -6;
        }
        if (PAD & 0x20) {
            YS8(0x18) = 3;
            YS8(0x46) = 0;
            yn_dec_sd();
        }
        break;
    case 5:
        if (PAD & 0x20) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            yn_dec_sd();
            return 1;
        }
        break;
    }
    return 0;
}

#define YS32(o) M2C_FIELD(ynw, s32 *, o)
#define YU16(o) M2C_FIELD(ynw, u16 *, o)
#define CURSOR_UD(o, n) \
    do { \
        if (pad & 0x2000) { \
            YS8(o) = YS8(o) - 1; \
        } \
        if (PAD & 0x1000) { \
            YS8(o) = YS8(o) + 1; \
        } \
        t = ynw; \
        p = (s8 *)(t + (o)); \
        *p = (M2C_FIELD(t, s8 *, o) + (n)) % (n); \
        yn_cur2_sd(p); \
    } while (0)

/* Provider selection screens (memory card network setting list, proxy, port, id/password): one
   state per ynw+0x18 value. Returns 0 while running, 1 = chosen, 2 = back, negative = cancel/error. */
s32 yn_select_provider(void) {
    s8 st;
    s8 q;
    s8 q2;
    s8 *nm;
    s32 r2;
    u8 *t;
    s8 *p;
    s32 r;
    s32 n;
    int off;
    int v;
    int a;
    u16 *tp;
    u16 d;
    u16 d1;
    s32 old;
    s32 bits;
    s32 up;
    s32 dn;
    s32 dig;
    u32 nv;

    v = YS8(0x18);
    if ((v >= 6 && v <= 8) || (v >= 0xC && v < 0xE)) {
        if (yn_common_memcard_out() != 0) {
            YS8(0x18) = 0xF;
            YS8(0x46) = 7;
            yn_log_sd(0xF);
        }
    }
    st = YS8(0x18);
    switch (st) {
    case 0:
        YS8(0x18) = st + 1;
        v = 1;
        do {
            M2C_FIELD(ynw + v, s8 *, 8) = 0;
            M2C_FIELD(ynw + v, s8 *, 9) = 0;
            M2C_FIELD(ynw + v, s8 *, 0xA) = 0;
            M2C_FIELD(ynw + v, s8 *, 0xB) = 0;
            M2C_FIELD(ynw + v, s8 *, 0xC) = 0;
            v += 5;
        } while (v < 0x10);
        yn_mc_init(ynw + 0x10D0);
        yn_proxy_wk_load();
    case 1: {
        u16 pad;
        YS8(0x42) = 1;
        YS8(0x43) = (YS8(8) >= 2) ? 4 : 2;
        YS8(0x44) = 1;
        YS8(0x45) = 1;
        YS8(0x47) = 1;
        YS8(0x48) = (YS8(8) >= 2) ? 2 : YS8(8);
        if (yn_common_memcard_out() != 0) {
            return -2;
        }
        pad = PAD;
        if (pad & 0x40) {
            return -1;
        }
        if (pad & 0x20) {
            yn_dec_sd();
            switch (YS8(8)) {
            case 0:
                YS8(0x18) = 0x13;
                YS8(0x46) = 0x37;
                YS8(0x17) = 0;
                break;
            case 1:
                YS8(0x18) = 2;
                break;
            default:
                YS8(0x18) = 0x12;
                break;
            }
            break;
        }
        if (pad & 0x100) {
            if (YS8(8) >= 2) {
                YS8(0x19) = YS8(0x18);
                YS8(0x18) = 0xD;
                YS8(0x46) = 0x19;
                yn_dec_sd();
            }
            break;
        }
        if (pad & 8) {
            YU8(0x1E) = YU8(0x1E) + 1;
            YU8(0x1E) = YU8(0x1E) & 1;
            yn_cur1_sd();
            return -2;
        }
        if (pad & 0x3000) {
            if (YS8(8) >= 2) {
                v = YS8(0xB);
                if (v > 0 && (pad & 0x2000)) {
                    YS8(0xB) = v - 1;
                }
                v = YS8(0xB);
                if (v < YS8(0x1C) - 1 && (PAD & 0x1000)) {
                    YS8(0xB) = v + 1;
                }
                v = YS8(0xC);
                if (YS8(0xB) - v < 0 && v > 0 && (PAD & 0x2000)) {
                    YS8(0xC) = v - 1;
                }
                if (YS8(0xB) >= 2) {
                    v = YS8(0xC);
                    if (v < YS8(0x1C) - 2 && (PAD & 0x1000)) {
                        YS8(0xC) = v + 1;
                    }
                }
            }
            t = ynw;
            p = (s8 *)(t + 8);
            v = *p;
            if (v > 0 && (PAD & 0x2000)) {
                *p = v - 1;
                yn_cur2_sd(p);
            }
            t = ynw;
            p = (s8 *)(t + 8);
            v = *p;
            if (v < M2C_FIELD(t, s8 *, 0x1C) + 1 && (PAD & 0x1000)) {
                *p = v + 1;
                yn_cur2_sd(p);
            }
        }
        break;
    }
    case 2:
        YS8(0x18) = st + 1;
        a = 0;
        do {
            if (a != 0 && a != 3 && a != 4) {
                M2C_FIELD(ynw + a, s8 *, 8) = 0;
            }
            a += 1;
        } while (a < 0x10);
        YS8(0x18) = 0xD;
        YS8(0x19) = 6;
        YS8(0x46) = 0x17;
        yn_proxy_wk_load();
        break;
    case 3:
        YS8(0x42) = 3;
        YS8(0x43) = 2;
        YS8(0x44) = 0x13;
        YS8(0x45) = 0x15;
        YS8(0x47) = 0x1E;
        YS8(0x48) = 0;
        if (yn_mc_device_check_all(ynw + 0x10D0) >= 0) {
            YU8(0x1D) = YU8(0x1D) | (((YU8(0x10D2) | YU8(0x10D3)) >> 1) & 3);
            if (YU8(0x1D) != 0) {
                u8 *t3;
                a = 0;
                YS8(0x18) = YS8(0x18) + 1;
                t3 = ynw;
            loop69:
                if (!(M2C_FIELD(t3, u8 *, 0x1D) & (1 << a))) {
                    a += 1;
                    if (a < 2) {
                        goto loop69;
                    }
                }
                if (a == 2) {
                    a = 0;
                }
                M2C_FIELD(t3, s8 *, 9) = a;
            } else {
                YS8(0x18) = 0xF;
                YS8(0x46) = 6;
                yn_log_sd();
            }
        }
        break;
    case 4: {
        u16 pad;
        pad = PAD;
        if (pad & 0x40) {
            yn_common_shot_cancel(0xE);
        } else {
            if (pad & 0x20) {
                YS8(0x18) = st + 1;
                yn_dec_sd();
                yn_mc_set_current(ynw + 0x10D0, YS8(9));
                yn_mc_gmfile_current_set(ynw + 0x10D0);
            } else if (pad & 0x3000) {
                s8 cur = YS8(9);
                u8 f = YU8(0x1D);
                int s = cur;
                do {
                    if (pad & 0x2000) {
                        s -= 1;
                    }
                    if (pad & 0x1000) {
                        s += 1;
                    }
                    s = (s + 2) % 2;
                    if (f & (1 << s)) {
                        break;
                    }
                } while (s != YS8(9));
                if (cur != s) {
                    yn_cur2_sd();
                }
                YS8(9) = s;
            }
        }
        break;
    }
    case 5:
        r = yn_mc_gmfile_check(ynw + 0x10D0);
        if (r != -2) {
            r2 = r;
            yn_log_sd();
            switch (r2) {
            case -1:
                YS8(0x18) = 0xD;
                YS8(0x19) = 6;
                YS8(0x46) = 0x17;
                break;
            case -7:
                YS8(0x18) = 0xF;
                YS8(0x46) = 0x2C;
                break;
            case -5:
                YS8(0x18) = 0x10;
                YS8(0x46) = 0xA;
                YS8(0x17) = 0;
                yn_log_sd(0x10);
                break;
            default:
                YS8(0x18) = 0xF;
                YS8(0x46) = 0x22;
                break;
            }
        }
        break;
    case 6: {
        u16 pad;
        YS8(0x42) = 0xF;
        YS8(0x43) = 2;
        YS8(0x44) = 0x13;
        YS8(0x45) = 0x16;
        YS8(0x47) = 0x1F;
        YS8(0x48) = 0;
        pad = PAD;
        if (pad & 0x40) {
            yn_common_shot_cancel(0xE);
        } else if (pad & 0x20) {
            YS32(0xEC8) = 1 - YS8(0xD);
            yn_dec_sd();
        } else if (pad & 0x400) {
            yn_cur1_sd();
            if (YS32(0xEC8) != 0) {
                YS8(0x18) = 7;
                YS8(0x19) = YS8(0x18);
            } else {
                YS8(0x19) = YS8(0x18);
                YS8(0x18) = 8;
                YS8(0x46) = 0x18;
            }
        } else if (pad & 0x3000) {
            CURSOR_UD(0xD, 2);
        }
        break;
    }
    case 7: {
        u16 pad;
        YS8(0x42) = 0x10;
        YS8(0x43) = 2;
        YS8(0x44) = 0x13;
        YS8(0x45) = 0x17;
        YS8(0x47) = 0x20;
        YS8(0x48) = YS8(0xE);
        pad = PAD;
        if (pad & 0x40) {
            yn_common_shot_cancel(0xE);
        } else if (pad & 0x20) {
            yn_dec_sd();
            switch (YS8(0xE)) {
            case 0:
                YS8(0x18) = 0xB;
                yn_keyboard_init(1, ynw + 0xED0);
                break;
            case 1:
                YS8(0x18) = 0xC;
                yn_port_init(ynw + 0xECC);
                break;
            case 2:
                YS8(0x18) = 0xB;
                yn_keyboard_init(1, ynw + 0xFD0);
                break;
            case 3:
                YS8(0x18) = 0xC;
                yn_port_init(ynw + 0xECE);
                break;
            }
        } else if (pad & 0x800) {
            YS8(0x18) = 6;
            yn_cur1_sd();
        } else if (pad & 0x400) {
            if (YU8(0xED0) == 0 || YU16(0xECC) == 0) {
                yn_ng_sd();
            } else {
                YS8(0x18) = 8;
                YS8(0x46) = 0x18;
                yn_cur1_sd();
            }
        } else if (pad & 0x3000) {
            CURSOR_UD(0xE, 4);
        }
        break;
    }
    case 8: {
        u16 pad;
        pad = PAD;
        if (pad & 0x40) {
            YS8(0x18) = 6;
            YS8(0x46) = 0;
            yn_can_sd();
        } else {
            if (pad & 0x20) {
                if (YS8(0x17) != 0) {
                    YS8(0x18) = st + 1;
                    yn_dec_sd();
                    YS8(0x18) = 0xA;
                    YS8(0x46) = 0x32;
                    yn_proxy_wk_save();
                } else {
                    YS8(0x18) = 6;
                    YS8(0x46) = 0;
                    yn_can_sd();
                }
            } else if (pad & 0x3000) {
                CURSOR_UD(0x17, 2);
            }
        }
        break;
    }
    case 9:
        r = yn_mc_gmfile_save(ynw + 0x10D0);
        if (r != -2) {
            r2 = r;
            yn_log_sd();
            switch (r2) {
            case -1:
                YS8(0x18) = 0xA;
                YS8(0x46) = 0x13;
                break;
            case -7:
            case -3:
                YS8(0x18) = 0xD;
                YS8(0x46) = 0x14;
                break;
            case -6:
                YS8(0x18) = 0xD;
                YS8(0x46) = 0x1F;
                break;
            case -5:
                YS8(0x18) = 0xD;
                YS8(0x46) = 9;
                break;
            default:
                YS8(0x18) = 0xD;
                YS8(0x46) = 0x22;
                break;
            }
        }
        break;
    case 10:
        if (PAD & 0x20) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            yn_dec_sd();
            return -2;
        }
        break;
    case 11:
        if (yn_keyboard_sub() != 0) {
            YS8(0x18) = YS8(0x19);
        }
        break;
    case 12: {
        u16 pad;
        YS8(0x39) = 2;
        pad = PAD;
        if (pad & 0x40) {
            YS8(0x18) = YS8(0x19);
            *M2C_FIELD(ynw, u16 **, 0x3C) = YU16(0x3A);
            YS8(0x38) = 0;
            yn_can_sd();
        } else if (pad & 0x20) {
            YS8(0x18) = YS8(0x19);
            YS8(0x38) = 0;
            yn_dec_sd();
        } else if (pad & 0xC00) {
            if (pad & 0x800) {
                d = YU16(0x40);
                if (d != 0x2710) {
                    YU16(0x40) = d * 10;
                    YS8(0x38) = YS8(0x38) + 1;
                }
            }
            if (PAD & 0x400) {
                if (YU16(0x40) != 1) {
                    YU16(0x40) = (u32)YU16(0x40) / 10;
                    YS8(0x38) = YS8(0x38) - 1;
                }
            }
            yn_cur2_sd();
        } else {
            if ((pad | YS32(0x28)) & 0x3000) {
                tp = M2C_FIELD(ynw, u16 **, 0x3C);
                d1 = YU16(0x40);
                old = *tp;
                dig = (s32)(old / d1) % 10;
                bits = pad | YS32(0x28);
                d = YU16(0x40);
                up = bits & 0x2000;
                dn = bits & 0x1000;
                v = old - d1 * dig;
                do {
                    if (up != 0) {
                        dig = (u32)(dig + 9) % 10U;
                    }
                    if (dn != 0) {
                        dig = (u32)(dig + 0xB) % 10U;
                    }
                    nv = v + dig * d;
                } while (nv >= 0x10000U);
                *tp = nv;
                yn_cur2_sd();
            }
        }
        break;
    }
    case 13: {
        u16 pad;
        pad = PAD;
        if ((pad & 0x20) || (pad & 0x40)) {
            YS8(0x18) = YS8(0x19);
            YS8(0x46) = 0;
            yn_dec_sd();
        }
        break;
    }
    case 14: {
        u16 pad;
        pad = PAD;
        if (pad & 0x40) {
            YS8(0x18) = YS8(0x19);
            YS8(0x46) = 0;
            yn_can_sd();
            break;
        }
        if (pad & 0x20) {
            if (YS8(0x17) != 0) {
                YS8(0x18) = 0;
                yn_dec_sd();
                YS8(0x46) = 0;
                return -2;
            }
            YS8(0x18) = YS8(0x19);
            YS8(0x46) = 0;
            yn_can_sd();
            break;
        }
        if (pad & 0x3000) {
            CURSOR_UD(0x17, 2);
        }
        break;
    }
    case 15:
        if (PAD & 0x20) {
            YS8(0x18) = 0;
            YS8(0x46) = 0;
            yn_dec_sd();
            return -2;
        }
        break;
    case 16: {
        u16 pad;
        pad = PAD;
        if (pad & 0x40) {
            YS8(0x18) = 2;
            YS8(0x46) = 0;
            yn_can_sd();
        } else {
            if (pad & 0x20) {
                if (YS8(0x17) != 0) {
                    YS8(0x18) = 0x11;
                    YS8(0x46) = 0xB;
                    yn_dec_sd();
                    yn_mc_init(ynw + 0x10D0);
                } else {
                    YS8(0x18) = 2;
                    YS8(0x46) = 0;
                    yn_can_sd();
                }
            } else if (pad & 0x3000) {
                CURSOR_UD(0x17, 2);
            }
        }
        break;
    }
    case 17:
        r = yn_mc_format(ynw + 0x10D0);
        switch (r) {
        case -2:
            break;
        case -1:
            YS8(0x18) = 0xD;
            YS8(0x19) = 5;
            YS8(0x46) = 0xC;
            yn_mc_init(ynw + 0x10D0);
            yn_log_sd();
            break;
        default:
            YS8(0x18) = 0xD;
            YS8(0x19) = 2;
            YS8(0x46) = 0xD;
            yn_mc_init(ynw + 0x10D0);
            yn_log_sd();
            break;
        }
        break;
    case 18:
        yn_strcpy(ynw + 0x1ACB4, yn_netcnf_search_usr_name(ynw + 0x1180, ynw + YS8(0xB) * 0x1340 + 0xAF00));
        nm = (s8 *)(ynw + 0x1ACB4);
        if (nm == 0 || *nm == 0) {
            YS8(0x18) = 0xF;
            YS8(0x46) = 0x33;
            yn_log_sd();
            break;
        }
        if (yn_netcnf_magicno_check(ynw + 0x1180) != 0) {
            YS8(0x18) = 0xF;
            YS8(0x46) = 0x1D;
            yn_log_sd(0xF);
            break;
        }
        off = YS8(0xB) * 0x14;
        r = M2C_FIELD(off + (int)ynw, s32 *, 0x254);
        if (r < 0) {
            YS8(0x18) = 0xF;
            YS8(0x46) = 5;
            yn_log_sd();
            break;
        }
        if (yn_hard_select_set(r) < 0) {
            YS8(0x18) = 0xF;
            YS8(0x46) = 5;
            yn_log_sd(0xF);
            break;
        }
        if (yn_netcnf_pastproxy_check(ynw + 0xEC8, D_5310D0) < 0) {
            YS8(0x26) = 1;
        }
        if (yn_netcnf_pastdata_check(D_5306B0, ynw + YS8(0xB) * 0x14 + 0x250, 1) < 0) {
            YS8(0x26) = 1;
        }
        off = YS8(0xB) * 0x14;
        yn_backup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
        off = YS8(0xB) * 0x14;
        yn_setup_allwork(M2C_FIELD(off + (int)ynw, s32 *, 0x260));
        return 1;
    case 19: {
        u16 pad;
        pad = PAD;
        if (pad & 0x40) {
            YS8(0x18) = 1;
            YS8(0x46) = 0;
            yn_can_sd();
            break;
        }
        if (pad & 0x20) {
            if (YS8(0x17) != 0) {
                YS8(0x18) = 0;
                YS8(0x46) = 0;
                yn_dec_sd();
                return 2;
            }
            YS8(0x18) = 1;
            YS8(0x46) = 0;
            yn_can_sd();
            break;
        }
        if (pad & 0x3000) {
            CURSOR_UD(0x17, 2);
        }
        break;
    }
    }
    return 0;
}
