/* Near-match C generated by tools/draft2c.py from m2c output and cleaned up by hand. */
#include "yn.h"

int ADXM_ShutdownThrd();
int ADXPS2_LoadFcacheDvd();
int ADXT_Finish();
int DIntr();
int DisableDmac();
int DisableIntc();
int EIntr();
int InetIPAddrFromString();
int LoadExecPS2();
int Net_kb_input_init2();
int Net_kb_input_sub();
int RemoveDmacHandler();
int RemoveIntcHandler();
int SetFilterMode();
int SoftKey_Getstr();
int SoftKey_onoff();
int SoftKey_trans();
int YnFile_Data_load();
int flCreateTextureFromTim2_mem();
int flPADDestroy();
int flPS2DmaWait();
int flReleasePaletteHandle();
int flReleaseTextureHandle();
int flSetRenderState();
int flSin();
int flfntDraw();
int flfntInit();
int flfntLocate();
int flfntPrintf();
int flfntSetHalftype();
int flfntSetPalette();
int flfntSetSize();
void flfntSetZ(f32 z);
int net_flps0008();
int printf();
int sceCdInit();
int sceGsSyncPath();
int sceGsSyncVCallback();
int sceNetcnfifConvAuthname();
int sceSifExitCmd();
int str_stop_all();
int yn_can_sd();
int yn_cur1_sd();
int yn_cur2_sd();
int yn_dec_sd();
int yn_hard_init();
int yn_hard_select_set();
int yn_log_sd();
int yn_mc_device_check_all();
int yn_mc_format();
int yn_mc_get_current();
int yn_mc_gmfile_check();
int yn_mc_gmfile_current_set();
int yn_mc_gmfile_save();
int yn_mc_init();
int yn_mc_set_current();
int yn_mc_ynfile_check();
int yn_netcnf_dev_to_work();
int yn_netcnf_exit();
int yn_netcnf_get_filename();
int yn_netcnf_get_list();
int yn_netcnf_get_num();
int yn_netcnf_ifc_to_work();
int yn_netcnf_init1();
int yn_netcnf_init2();
int yn_netcnf_magicno_check();
int yn_netcnf_net_allload();
int yn_netcnf_pastdata_check();
int yn_netcnf_pastproxy_check();
int yn_netcnf_search_usr_name();
int yn_netcnf_set_current();
int yn_netcnf_setup_devwork();
int yn_ng_sd();
int yn_set_init();
int yn_stop_bgm();
int yn_utf8_to_sjis();
extern u8 BsProxyUrlstr[];
extern u8 BsProxyUrlstr_S[];
extern u8 D_530394[];
extern u8 D_5306B0[];
extern u8 D_5310D0[];
extern u8 DeviceWork[];
extern u8 MyDialNumber[];
extern u8 MyDialOutline[];
extern u8 MyDomain[];
extern u8 MyPassword[];
extern u8 MyUserName[];
extern u8 Psw[];
extern u8 SrvDomain[];
extern u8 Yn_temp[];
extern u8 lit_160_0053EA40[];
extern u8 lit_4084[];
extern u8 lit_4085[];
extern u8 lit_4086[];
extern u8 lit_4087[];
extern u8 lit_4118[];
extern u8 lit_4217[];
extern u8 lit_4218[];
extern u8 lit_4358[];
extern u8 lit_4372[];
extern u8 lit_4679[];
extern u8 lit_4680[];
extern u8 lit_4681[];
extern u8 lit_4682[];
extern u8 lit_4683[];
extern u8 lit_4684[];
extern u8 lit_4685[];
extern u8 lit_4686[];
extern u8 lit_4687[];
extern u8 lit_4688[];
extern u8 lit_4994[];
extern u8 lit_5208[];
extern u8 lit_5209[];
extern u8 lit_5387[];
extern u8 yn_dialog_cnt_tbl[];
extern char *yn_dialog_mes_tbl[];
extern char *yn_hard_more_mes_tbl[];
extern u8 yn_help_cnt_tbl[];
extern char *yn_help_mes_tbl[];
extern char *yn_memcard_mes_tbl[];
extern u8 yn_mess_cnt_tbl[];
extern char *yn_mess_mes_tbl[];
extern u8 yn_parts_data[];
extern u8 yn_spr_data[];
extern char *yn_title_mes_tbl[];
extern u8 yn_uv_data[];
extern s8 BsProxyUseFlag;
extern s8 MyDialType;
extern s32 MyDns1;
extern s32 MyDns2;
extern s8 MyEtherInitMode;
extern s32 MyGateway;
extern s32 MyIPAddr;
extern s32 MyNetmask;
extern s8 NdgNegoMode;
extern s8 PppRecognize;
extern s32 SrvIPAddress;
extern s16 SrvPort;
extern s8 SrvType;
extern s32 flPs2GsHandler;
extern s32 yn_r_no;
extern s32 yn_type;
extern u8 * ynw;

s32 yn_set_main();
void yn_set_exit_sub();
s32 yn_file_search();
s32 yn_auto_connect();
s32 yn_select_provider();
void yn_common_shot_cancel();
s32 yn_common_memcard_out();
void yn_title_font();
void yn_message_font_sub();
void yn_connect_font_sub();
void yn_hard_font_sub();
void yn_hard_more_font_sub();
void yn_memcard_font_sub();
void yn_id_pw_font_sub();
void yn_ipadrs_font_sub();
void yn_port_font_sub();
void yn_prname_font_sub();
void yn_adname_font_sub();
void yn_dialog_draw();
void yn_dialog_font_sub();
void yn_dialog_font_without_yesno();
void yn_dialog_font_once();
void yn_dialog_font_memcard();
void yn_dialog_font_setting();
void yn_dialog_font_ip_sub();
void yn_help_font();
void yn_printf();
void yn_set_pal();
void yn_set_size();
void yn_set_z(f32 z);
void yn_set_halftype();
s32 yn_get_halftype();
int yn_center_x();
int yn_strlen();
void yn_strconv();
void yn_strconv2();
void yn_strcpy();
void yn_port_init();
void yn_key_repeat();
void yn_keyboard_init();
s32 yn_keyboard_sub();
void yn_keyboard_server();
void yn_draw();
void yn_view_set();
void yn_sprite_draw_sub();
void yn_sprite_draw_each();
void yn_setup_allwork();
void yn_backup_allwork();
void yn_proxy_wk_load();
void yn_proxy_wk_save();
int yn_load_texfile();
void yn_scecom_reboot();

s32 yn_set_main(void) {
    u8 *w;
    s8 *q;
    s32 r;
    s32 t1;
    s32 t2;
    u16 pad;
    u32 rno;

    yn_keyboard_server();
    rno = yn_r_no;
    switch (rno) {
    case 0:
        yn_stop_bgm();
        t1 = yn_load_texfile(0, 0x10500);
        t2 = yn_load_texfile(1, 0x40500);
        ynw = Yn_temp;
        memset(ynw, 0, 0x1AEC0);
        M2C_FIELD(ynw, s32 *, 0) = t1;
        M2C_FIELD(ynw, s32 *, 4) = t2;
        yn_netcnf_init1(ynw + 0x1180);
        yn_r_no = 1;
        return 0;
    case 1:
        yn_netcnf_init2(ynw + 0x1180);
        yn_hard_init();
        yn_proxy_wk_load();
        if (yn_type == 0) {
            flSetRenderState(0x14, 0xFF000000);
            yn_r_no = 2;
        } else {
            yn_r_no = 3;
        }
    default:
        break;
    case 2:
        w = ynw;
        M2C_FIELD(w, u8 *, 0x21) = M2C_FIELD(w, u8 *, 0x21) + 1;
        r = yn_file_search();
        switch (r) {
        case 0:
            break;
        case 1:
            yn_r_no = 6;
            M2C_FIELD(ynw, s8 *, 0x24) = 0;
            M2C_FIELD(ynw, s8 *, 8) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            break;
        case -1:
            yn_r_no = 6;
            M2C_FIELD(ynw, s8 *, 0x24) = 0;
            M2C_FIELD(ynw, s8 *, 8) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            break;
        case -2:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 6;
            M2C_FIELD(ynw, s8 *, 0x17) = 0;
            yn_log_sd();
            break;
        case -3:
            yn_r_no = 0xA;
            M2C_FIELD(ynw, s8 *, 0x24) = 0;
            M2C_FIELD(ynw, s8 *, 8) = 0;
            M2C_FIELD(ynw, s8 *, 0x17) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x1D;
            yn_log_sd();
            M2C_FIELD(ynw, s8 *, 0x42) = 1;
            M2C_FIELD(ynw, s8 *, 0x43) = 4;
            M2C_FIELD(ynw, s8 *, 0x44) = 1;
            M2C_FIELD(ynw, s8 *, 0x45) = 1;
            M2C_FIELD(ynw, s8 *, 0x47) = 1;
            M2C_FIELD(ynw, s8 *, 0x48) = 0;
            break;
        }
        break;
    case 3:
        w = ynw;
        M2C_FIELD(w, u8 *, 0x21) = M2C_FIELD(w, u8 *, 0x21) + 1;
        r = yn_auto_connect();
        switch (r) {
        case 1:
            yn_r_no = 7;
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            break;
        case -1:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x2B;
            yn_log_sd();
            break;
        case -2:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 6;
            yn_log_sd();
            break;
        case -3:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 5;
            yn_log_sd();
            break;
        case -4:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x2B;
            yn_log_sd();
            break;
        case -6:
            yn_r_no = 9;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x39;
            yn_log_sd();
            break;
        }
        break;
    case 4:
        yn_scecom_reboot();
        break;
    case 6:
        w = ynw;
        M2C_FIELD(w, u8 *, 0x21) = M2C_FIELD(w, u8 *, 0x21) + 1;
        M2C_FIELD(ynw, s8 *, 0x39) = 0;
        yn_key_repeat(Psw);
        r = yn_select_provider();
        switch (r) {
        case 0:
            break;
        case 1:
            yn_r_no = 7;
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            break;
        case 2:
            yn_r_no = 4;
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            M2C_FIELD(ynw, s8 *, 8) = 0;
            break;
        case -1:
            yn_r_no = 8;
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x1A;
            M2C_FIELD(ynw, s8 *, 8) = 0;
            M2C_FIELD(ynw, s8 *, 0x17) = 0;
            yn_log_sd();
            break;
        case -2:
            yn_r_no = 2;
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            break;
        }
        break;
    case 7:
        yn_set_exit_sub();
        return M2C_FIELD(ynw, u8 *, 0x26) + 1;
    case 8:
        w = ynw;
        M2C_FIELD(w, u8 *, 0x21) = M2C_FIELD(w, u8 *, 0x21) + 1;
        pad = *(u16 *)0x3F3714;
        if (pad & 0x40) {
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            yn_can_sd();
            yn_r_no = 6;
            break;
        }
        if (pad & 0x20) {
            w = ynw;
            if (M2C_FIELD(w, s8 *, 0x17) != 0) {
                yn_dec_sd();
                yn_set_exit_sub();
                return -1;
            }
            M2C_FIELD(w, s8 *, 0x46) = 0;
            yn_can_sd();
            yn_r_no = 6;
            break;
        }
        if (pad & 0x3000) {
            if (pad & 0x2000) {
                w = ynw;
                M2C_FIELD(w, s8 *, 0x17) = M2C_FIELD(w, s8 *, 0x17) - 1;
            }
            if (*(u16 *)0x3F3714 & 0x1000) {
                w = ynw;
                M2C_FIELD(w, s8 *, 0x17) = M2C_FIELD(w, s8 *, 0x17) + 1;
            }
            w = ynw;
            q = (s8 *)(w + 0x17);
            *q = (*q + 2) % 2;
            yn_cur2_sd(q);
        }
        break;
    case 9:
        w = ynw;
        M2C_FIELD(w, u8 *, 0x21) = M2C_FIELD(w, u8 *, 0x21) + 1;
        pad = *(u16 *)0x3F3714;
        if ((pad & 0x20) || (pad & 0x40)) {
            yn_dec_sd();
            yn_set_exit_sub();
            return -1;
        }
        break;
    case 10:
        pad = *(u16 *)0x3F3714;
        if ((pad & 0x20) || (pad & 0x40)) {
            yn_r_no = 6;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            yn_dec_sd();
        }
        break;
    }
    if (yn_r_no == 4) {
        return 0;
    }
    M2C_FIELD(ynw, s8 *, 0x1A) = yn_get_halftype();
    yn_set_halftype(1);
    yn_set_pal(0);
    yn_set_size(0x16, 0x16);
    yn_set_z(850.0f);
    yn_title_font();
    yn_message_font();
    yn_button_font();
    yn_dialog_font();
    yn_help_font();
    yn_draw();
    yn_set_halftype(M2C_FIELD(ynw, s8 *, 0x1A));
    return 0;
}

void yn_set_exit_sub(void) {
    yn_set_init(0);
    flReleaseTextureHandle(M2C_FIELD(ynw, u16 *, 0));
    flReleasePaletteHandle((u32) (M2C_FIELD(ynw, s32 *, 0) & 0xFFFF0000) >> 0x10);
    flReleaseTextureHandle(M2C_FIELD(ynw, u16 *, 4));
    flReleasePaletteHandle((u32) (M2C_FIELD(ynw, s32 *, 4) & 0xFFFF0000) >> 0x10);
    yn_netcnf_exit(ynw + 0x1180);
}

s32 yn_file_search(void) {
    u8 st;
    u8 a;
    u8 *w;
    u8 *sp;
    s32 r;
    s32 none;
    s32 n;

    w = ynw;
    st = M2C_FIELD(w, u8 *, 0x24);
    sp = w + 0x24;
    switch (st) {
    case 0:
        *sp = st + 1;
        M2C_FIELD(ynw, u8 *, 0x1D) = 0;
        M2C_FIELD(ynw, s8 *, 0x1C) = 0;
        M2C_FIELD(ynw, s8 *, 0x1F) = 0;
        M2C_FIELD(ynw, u8 *, 0x27) = M2C_FIELD(ynw, u8 *, 0x1E);
        yn_mc_init(ynw + 0x10D0);
        memset(ynw + 0x1180, 0, 0x19D40);
        memset(ynw + 0x250, 0, 0x258);
    case 1:
        if (yn_mc_device_check_all(ynw + 0x10D0) >= 0) {
            M2C_FIELD(ynw, u8 *, 0x1D) = M2C_FIELD(ynw, u8 *, 0x1D) | (((M2C_FIELD(ynw, u8 *, 0x10D2) | M2C_FIELD(ynw, u8 *, 0x10D3)) >> 1) & 3);
            if (M2C_FIELD(ynw, u8 *, 0x1D) != 0) {
                M2C_FIELD(ynw, u8 *, 0x24) = 2;
                break;
            }
            M2C_FIELD(ynw, u8 *, 0x24) = 0;
            return -2;
        }
        break;
    default:
        break;
    case 2:
    case 3:
        for (;;) {
            a = M2C_FIELD(ynw, u8 *, 0x27);
            if (M2C_FIELD(ynw, u8 *, 0x1D) & (1 << a)) {
                break;
            }
            M2C_FIELD(ynw, u8 *, 0x27) = (a + 1) % 2;
            a = M2C_FIELD(ynw, u8 *, 0x27);
            if (a == M2C_FIELD(ynw, u8 *, 0x1E)) {
                break;
            }
        }
        if (M2C_FIELD(ynw, u8 *, 0x24) == 3 && a == M2C_FIELD(ynw, u8 *, 0x1E)) {
            M2C_FIELD(ynw, u8 *, 0x24) = 0;
            M2C_FIELD(ynw, u8 *, 0x1E) = M2C_FIELD(ynw, u8 *, 0x27);
            yn_mc_set_current(ynw + 0x10D0, M2C_FIELD(ynw, u8 *, 0x27));
            return -1;
        }
        M2C_FIELD(ynw, u8 *, 0x24) = 4;
        M2C_FIELD(ynw, u8 *, 0x1E) = M2C_FIELD(ynw, u8 *, 0x27);
        yn_mc_set_current(ynw + 0x10D0, M2C_FIELD(ynw, u8 *, 0x27));
        break;
    case 4:
        r = yn_mc_ynfile_check(ynw + 0x10D0);
        if (r != -2) {
            if (r != -1) {
                M2C_FIELD(ynw, u8 *, 0x24) = 3;
            } else {
                M2C_FIELD(ynw, u8 *, 0x24) = 5;
            }
        }
        break;
    case 5:
        yn_netcnf_get_filename(ynw + 0x1180, yn_mc_get_current(ynw + 0x10D0));
        M2C_FIELD(ynw, s8 *, 0x1C) = 0;
        if (yn_netcnf_magicno_check(ynw + 0x1180) != 0) {
            return -3;
        }
        none = 0;
        yn_netcnf_set_current(ynw + 0x1180, 0);
        n = yn_netcnf_get_num(ynw + 0x1180);
        M2C_FIELD(ynw, s8 *, 0x1C) = n;
        if ((s8)n == 0) {
            none = 1;
        }
        yn_netcnf_get_list(ynw + 0x1180);
        yn_netcnf_set_current(ynw + 0x1180, 2);
        if (yn_netcnf_get_num(ynw + 0x1180) == 0) {
            none = 1;
        }
        yn_netcnf_get_list(ynw + 0x1180);
        yn_netcnf_set_current(ynw + 0x1180, 1);
        if (yn_netcnf_get_num(ynw + 0x1180) == 0) {
            none = 1;
        }
        yn_netcnf_get_list(ynw + 0x1180);
        if (none == 0) {
            yn_netcnf_net_allload(ynw + 0x1180);
            yn_netcnf_setup_devwork(ynw + 0x1180, ynw + 0x250);
            M2C_FIELD(ynw, u8 *, 0x24) = 0;
            return 1;
        }
        M2C_FIELD(ynw, u8 *, 0x24) = 0;
        return -1;
    }
    return 0;
}

#if 0 /* yn_auto_connect: m2c draft, does not compile yet */
s32 yn_auto_connect(void) {
    s32 temp_a0_2;
    s32 temp_s0;
    s32 temp_v0_2;
    s32 temp_v0_4;
    s8 temp_a0;
    u8 temp_a0_3;
    u8 *temp_a1;
    u8 *temp_a1_2;
    u8 *temp_v0;
    u8 *temp_v0_3;
    u8 *temp_v1;
    u8 *temp_v1_2;
    u8 *temp_v1_3;
    u8 *temp_v1_4;

    temp_v0 = ynw;
    temp_a0 = M2C_FIELD(temp_v0, s8 *, 0x18);
    temp_a1 = temp_v0 + 0x18;
    switch (temp_a0) {                              /* switch 1 */
    case 0:                                         /* switch 1 */
        M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) (temp_a0 + 1);
        M2C_FIELD(ynw, u8 *, 0x1E) = 0U;
        M2C_FIELD(ynw, u8 *, 0x25) = 0U;
        /* fallthrough */
    case 1:                                         /* switch 1 */
        if (yn_netcnf_pastproxy_check(ynw + 0xEC8, D_5310D0) < 0) {
            return -4;
        }
        temp_v1 = ynw;
        M2C_FIELD(temp_v1, s8 *, 0x18) = (s8) (M2C_FIELD(temp_v1, s8 *, 0x18) + 1);
        M2C_FIELD(ynw, s8 *, 0x24) = 0;
    default:                                        /* switch 1 */
    case 0:                                         /* switch 2 */
block_41:
        return 0;
    case 2:                                         /* switch 1 */
        temp_v0_2 = yn_file_search();
        switch (temp_v0_2) {                        /* switch 2; irregular */
        case 1:                                     /* switch 2 */
            temp_v0_3 = ynw;
            temp_v0_4 = yn_netcnf_pastdata_check(D_5306B0, temp_v0_3 + 0x250, M2C_FIELD(temp_v0_3, s8 *, 0x1C));
            if (temp_v0_4 >= 0) {
                temp_s0 = temp_v0_4 * 0x14;
                temp_a0_2 = M2C_FIELD((temp_s0 + ynw), s32 *, 0x254);
                if (temp_a0_2 < 0) {
                    return -3;
                }
                if (yn_hard_select_set(temp_a0_2) < 0) {
                    return -3;
                }
                yn_backup_allwork(M2C_FIELD((temp_s0 + ynw), s32 *, 0x260));
                yn_setup_allwork(M2C_FIELD((temp_s0 + ynw), s32 *, 0x260));
                M2C_FIELD(ynw, s8 *, 0x18) = 5;
                M2C_FIELD(ynw, s8 *, 0x46) = 0x34;
                yn_log_sd(5);
                goto block_41;
            }
        default:                                    /* switch 2 */
            temp_v1_2 = ynw;
            temp_a0_3 = M2C_FIELD(temp_v1_2, u8 *, 0x25);
            if (temp_a0_3 & 0x80) {
                if (temp_a0_3 & (1 << M2C_FIELD(temp_v1_2, u8 *, 0x1E))) {
                    return -1;
                }
                goto block_27;
            }
            M2C_FIELD(temp_v1_2, u8 *, 0x25) = (u8) (temp_a0_3 | 0x80);
block_27:
            temp_a1_2 = ynw;
            M2C_FIELD(temp_a1_2, u8 *, 0x25) = (u8) (M2C_FIELD(temp_a1_2, u8 *, 0x25) | ((1 << M2C_FIELD(temp_a1_2, u8 *, 0x1E)) & 0xFF));
            if (yn_netcnf_magicno_check(ynw + 0x1180, temp_a1_2) != 0) {
                M2C_FIELD(ynw, s8 *, 0x18) = 4;
                M2C_FIELD(ynw, s8 *, 0x46) = 0x1D;
                yn_log_sd(4);
                yn_mc_init(ynw + 0x10D0);
            } else {
                M2C_FIELD(ynw, s8 *, 0x18) = 3;
            }
            goto block_41;
        case -2:                                    /* switch 2 */
            return -2;
        }
        break;
    case 3:                                         /* switch 1 */
        M2C_FIELD(temp_v0, s8 *, 0x18) = 2;
        M2C_FIELD(ynw, s8 *, 0x24) = 0;
        temp_v1_3 = ynw;
        M2C_FIELD(temp_v1_3, u8 *, 0x1E) = (u8) (M2C_FIELD(temp_v1_3, u8 *, 0x1E) + 1);
        temp_v1_4 = ynw;
        M2C_FIELD(temp_v1_4, u8 *, 0x1E) = (u8) (M2C_FIELD(temp_v1_4, u8 *, 0x1E) & 1);
        goto block_41;
    case 4:                                         /* switch 1 */
        if (yn_common_memcard_out(temp_a0, temp_a1) != 0) {
            M2C_FIELD(ynw, s8 *, 0x18) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            return -6;
        }
        if (*(u16 *)0x3F3714 & 0x20) {
            M2C_FIELD(ynw, s8 *, 0x18) = 3;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            yn_dec_sd();
        }
        goto block_41;
    case 5:                                         /* switch 1 */
        if (*(u8 *)0x3F3714 & 0x20) {
            M2C_FIELD(temp_v0, s8 *, 0x18) = 0;
            M2C_FIELD(ynw, s8 *, 0x46) = 0;
            yn_dec_sd(temp_a0, temp_a1);
            return 1;
        }
        goto block_41;
    }
}
#endif

s32 yn_select_provider(void) {
    u8 *temp_a0_17;
    u8 *temp_a0_18;
    u8 *temp_a0_2;
    u8 *temp_a0_3;
    u8 *temp_a0_7;
    u8 *temp_a1;
    u8 *temp_a1_13;
    u8 *temp_a1_14;
    u8 *temp_a1_2;
    u8 *temp_a1_3;
    u8 *temp_a1_5;
    u8 *temp_a1_6;
    u8 *temp_a2_3;
    u8 *temp_v0;
    u8 *temp_v0_10;
    u8 *temp_v0_11;
    u8 *temp_v0_13;
    u8 *temp_v0_16;
    u8 *temp_v0_17;
    u8 *temp_v0_19;
    u8 *temp_v0_2;
    u8 *temp_v0_3;
    u8 *temp_v0_4;
    u8 *temp_v0_5;
    u8 *temp_v0_6;
    u8 *temp_v0_9;
    u8 *temp_v1_14;
    u8 *temp_v1_16;
    u8 *temp_v1_17;
    u8 *temp_v1_18;
    u8 *temp_v1_19;
    u8 *temp_v1_22;
    u8 *temp_v1_23;
    u8 *temp_v1_24;
    u8 *temp_v1_25;
    u8 *temp_v1_26;
    u8 *temp_v1_27;
    u8 *temp_v1_28;
    u8 *temp_v1_29;
    u8 *temp_v1_2;
    u8 *temp_v1_31;
    u8 *temp_v1_32;
    u8 *temp_v1_33;
    u8 *temp_v1_34;
    u8 *temp_v1_35;
    u8 *temp_v1_36;
    u8 *temp_v1_37;
    u8 *temp_v1_3;
    u8 *temp_v1_5;
    u8 *temp_v1_6;
    u8 *temp_v1_7;
    s32 temp_a0_10;
    s32 temp_a0_16;
    s32 temp_a1_9;
    s32 temp_a3;
    s32 temp_a3_3;
    s32 temp_v0_12;
    s32 temp_v0_14;
    s32 temp_v0_18;
    s32 temp_v0_7;
    s32 temp_v0_8;
    s32 var_a1_2;
    s32 var_t2;
    s32 var_v0_2;
    s32 var_v1;
    s8 temp_a0_13;
    s8 temp_a0_6;
    s8 temp_a2;
    s8 temp_v1;
    s8 temp_v1_10;
    s8 temp_v1_11;
    s8 temp_v1_12;
    s8 temp_v1_13;
    s8 temp_v1_21;
    s8 temp_v1_4;
    s8 temp_v1_8;
    s8 temp_v1_9;
    s8 var_a0_2;
    s8 var_a0_3;
    s8 var_s0;
    s8 var_v0;
    u16 *temp_t0;
    u16 temp_a0;
    u16 temp_a0_11;
    u16 temp_a0_12;
    u16 temp_a0_14;
    u16 temp_a0_15;
    u16 temp_a0_19;
    u16 temp_a0_20;
    u16 temp_a0_5;
    u16 temp_a0_8;
    u16 temp_a0_9;
    u16 temp_a1_10;
    u16 temp_a1_11;
    u16 temp_a1_12;
    u16 temp_a1_15;
    u16 temp_a1_4;
    u16 temp_a1_7;
    u16 temp_a1_8;
    u16 temp_a2_4;
    u16 temp_a3_2;
    u16 temp_t1;
    u16 temp_v0_15;
    u16 temp_v1_15;
    u16 temp_v1_20;
    u16 temp_v1_30;
    u8 temp_a0_4;
    u8 temp_a2_2;
    u8 *var_a0;
    u8 *var_a1;

    temp_v1 = M2C_FIELD(ynw, s8 *, 0x18);
    if ((temp_v1 < 6) || (temp_v1 >= 9)) {
        if ((temp_v1 >= 0xC) && (temp_v1 < 0xE)) {
            goto block_5;
        }
    } else {
block_5:
        if (yn_common_memcard_out() != 0) {
            M2C_FIELD(ynw, s8 *, 0x18) = 0xF;
            M2C_FIELD(ynw, s8 *, 0x46) = 7;
            yn_log_sd(0xFU);
        }
    }
    temp_v0 = ynw;
    temp_a2 = M2C_FIELD(temp_v0, s8 *, 0x18);
    if ((u32) temp_a2 < 0x14U) {
        switch (temp_a2) {                          /* switch 1 */
        case 0:                                     /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) (temp_a2 + 1);
            var_v1 = 1;
            do {
                M2C_FIELD((ynw + var_v1), s8 *, 8) = 0;
                M2C_FIELD((ynw + var_v1), s8 *, 9) = 0;
                M2C_FIELD((ynw + var_v1), s8 *, 0xA) = 0;
                M2C_FIELD((ynw + var_v1), s8 *, 0xB) = 0;
                M2C_FIELD((ynw + var_v1), s8 *, 0xC) = 0;
                var_v1 += 5;
            } while (var_v1 < 0x10);
            yn_mc_init(ynw + 0x10D0);
            yn_proxy_wk_load();
            /* fallthrough */
        case 1:                                     /* switch 1 */
            M2C_FIELD(ynw, s8 *, 0x42) = 1;
            temp_v1_2 = ynw;
            var_v0 = 2;
            if (M2C_FIELD(temp_v1_2, s8 *, 8) >= 2) {
                var_v0 = 4;
            }
            M2C_FIELD(temp_v1_2, s8 *, 0x43) = var_v0;
            M2C_FIELD(ynw, s8 *, 0x44) = 1;
            M2C_FIELD(ynw, s8 *, 0x45) = 1;
            M2C_FIELD(ynw, s8 *, 0x47) = 1;
            temp_v1_3 = ynw;
            var_a0_2 = M2C_FIELD(temp_v1_3, s8 *, 8);
            if (var_a0_2 >= 2) {
                var_a0_2 = 2;
            }
            M2C_FIELD(temp_v1_3, s8 *, 0x48) = var_a0_2;
            if (yn_common_memcard_out(var_a0_2) != 0) {
                return -2;
            }
            temp_a0 = *(u16 *)0x3F3714;
            if (temp_a0 & 0x40) {
                return -1;
            }
            if (temp_a0 & 0x20) {
                yn_dec_sd(temp_a0);
                temp_a0_2 = ynw;
                temp_v1_4 = M2C_FIELD(temp_a0_2, s8 *, 8);
                switch (temp_v1_4) {                /* switch 2; irregular */
                case 0:                             /* switch 2 */
                    M2C_FIELD(temp_a0_2, s8 *, 0x18) = 0x13;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x37;
                    M2C_FIELD(ynw, s8 *, 0x17) = 0;
                    break;
                case 1:                             /* switch 2 */
                    M2C_FIELD(temp_a0_2, s8 *, 0x18) = 2;
                    break;
                default:                            /* switch 2 */
                    M2C_FIELD(temp_a0_2, s8 *, 0x18) = 0x12;
                    break;
                }
                goto block_293;
            }
            if (temp_a0 & 0x100) {
                temp_a1 = ynw;
                if (M2C_FIELD(temp_a1, s8 *, 8) >= 2) {
                    M2C_FIELD(temp_a1, s8 *, 0x19) = (s8) M2C_FIELD(temp_a1, s8 *, 0x18);
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x19;
                    yn_dec_sd(0xDU, temp_a1);
                }
                goto block_293;
            }
            if (temp_a0 & 8) {
                temp_v1_5 = ynw;
                M2C_FIELD(temp_v1_5, u8 *, 0x1E) = (u8) (M2C_FIELD(temp_v1_5, u8 *, 0x1E) + 1);
                temp_v1_6 = ynw;
                M2C_FIELD(temp_v1_6, u8 *, 0x1E) = (u8) (M2C_FIELD(temp_v1_6, u8 *, 0x1E) & 1);
                yn_cur1_sd(temp_a0);
                return -2;
            }
            if (temp_a0 & 0x3000) {
                temp_v1_7 = ynw;
                var_a1 = temp_v1_7 + 0xB;
                if (M2C_FIELD(temp_v1_7, s8 *, 8) >= 2) {
                    temp_v1_8 = M2C_FIELD(temp_v1_7, s8 *, 0xB);
                    if ((temp_v1_8 > 0) && (temp_a0 & 0x2000)) {
                        M2C_FIELD(temp_v1_7, s8 *, 0xB) = (s8) (temp_v1_8 - 1);
                    }
                    temp_v0_2 = ynw;
                    temp_v1_9 = M2C_FIELD(temp_v0_2, s8 *, 0xB);
                    if ((temp_v1_9 < (M2C_FIELD(temp_v0_2, s8 *, 0x1C) - 1)) && (*(u8 *)0x3F3714 & 0x1000)) {
                        M2C_FIELD(temp_v0_2, s8 *, 0xB) = (s8) (temp_v1_9 + 1);
                    }
                    temp_v0_3 = ynw;
                    temp_v1_10 = M2C_FIELD(temp_v0_3, s8 *, 0xC);
                    if (((M2C_FIELD(temp_v0_3, s8 *, 0xB) - temp_v1_10) < 0) && (temp_v1_10 > 0) && (*(u8 *)0x3F3714 & 0x2000)) {
                        M2C_FIELD(temp_v0_3, s8 *, 0xC) = (s8) (temp_v1_10 - 1);
                    }
                    temp_a0_3 = ynw;
                    if (M2C_FIELD(temp_a0_3, s8 *, 0xB) >= 2) {
                        temp_v1_11 = M2C_FIELD(temp_a0_3, s8 *, 0xC);
                        var_a1 = temp_a0_3 + 0xC;
                        if ((temp_v1_11 < (M2C_FIELD(temp_a0_3, s8 *, 0x1C) - 2)) && (*(u8 *)0x3F3714 & 0x1000)) {
                            M2C_FIELD(temp_a0_3, s8 *, 0xC) = (s8) (temp_v1_11 + 1);
                        }
                    }
                }
                temp_v0_4 = ynw;
                temp_v1_12 = M2C_FIELD(temp_v0_4, s8 *, 8);
                if ((temp_v1_12 > 0) && (*(u8 *)0x3F3714 & 0x2000)) {
                    M2C_FIELD(temp_v0_4, s8 *, 8) = (s8) (temp_v1_12 - 1);
                    yn_cur2_sd(temp_v0_4 + 8, var_a1);
                }
                temp_v0_5 = ynw;
                temp_v1_13 = M2C_FIELD(temp_v0_5, s8 *, 8);
                if ((temp_v1_13 < (M2C_FIELD(temp_v0_5, s8 *, 0x1C) + 1)) && (*(u8 *)0x3F3714 & 0x1000)) {
                    M2C_FIELD(temp_v0_5, s8 *, 8) = (s8) (temp_v1_13 + 1);
                    yn_cur2_sd(temp_v0_5 + 8);
                }
            }
            goto block_293;
        case 2:                                     /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) (temp_a2 + 1);
            var_a1_2 = 0;
            do {
                if ((var_a1_2 != 0) && (var_a1_2 != 3) && (var_a1_2 != 4)) {
                    M2C_FIELD((ynw + var_a1_2), s8 *, 8) = 0;
                }
                var_a1_2 += 1;
            } while (var_a1_2 < 0x10);
            M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
            M2C_FIELD(ynw, s8 *, 0x19) = 6;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x17;
            yn_proxy_wk_load(6, 0xD, temp_a2);
            goto block_293;
        case 3:                                     /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x42) = 3;
            M2C_FIELD(ynw, s8 *, 0x43) = 2;
            M2C_FIELD(ynw, s8 *, 0x44) = 0x13;
            M2C_FIELD(ynw, s8 *, 0x45) = 0x15;
            M2C_FIELD(ynw, s8 *, 0x47) = 0x1E;
            M2C_FIELD(ynw, s8 *, 0x48) = 0;
            if (yn_mc_device_check_all(ynw + 0x10D0, 0x13, 2) >= 0) {
                temp_a1_2 = ynw;
                temp_a0_4 = M2C_FIELD(temp_a1_2, u8 *, 0x10D2);
                M2C_FIELD(temp_a1_2, u8 *, 0x1D) = (u8) (M2C_FIELD(temp_a1_2, u8 *, 0x1D) | (((s32) (temp_a0_4 | M2C_FIELD(temp_a1_2, u8 *, 0x10D3)) >> 1) & 3));
                temp_v1_14 = ynw;
                if (M2C_FIELD(temp_v1_14, u8 *, 0x1D) != 0) {
                    var_a0_3 = 0;
                    M2C_FIELD(temp_v1_14, s8 *, 0x18) = (s8) (M2C_FIELD(temp_v1_14, s8 *, 0x18) + 1);
                    temp_a1_3 = ynw;
loop_69:
                    if (!(M2C_FIELD(temp_a1_3, u8 *, 0x1D) & (1 << var_a0_3))) {
                        var_a0_3 += 1;
                        if (var_a0_3 < 2) {
                            goto loop_69;
                        }
                    }
                    if (var_a0_3 == 2) {
                        var_a0_3 = 0;
                    }
                    M2C_FIELD(temp_a1_3, s8 *, 9) = var_a0_3;
                } else {
                    M2C_FIELD(temp_v1_14, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 6;
                    yn_log_sd(temp_a0_4, temp_a1_2);
                }
            }
            goto block_293;
        case 4:                                     /* switch 1 */
            temp_a1_4 = *(u8 *)0x3F3714;
            if (temp_a1_4 & 0x40) {
                yn_common_shot_cancel(0xE, temp_a1_4, temp_a2);
            } else {
                temp_a0_5 = temp_a1_4 & 0x20;
                if (temp_a0_5 != 0) {
                    M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) (temp_a2 + 1);
                    yn_dec_sd(temp_a0_5, (int *) temp_a1_4, temp_a2);
                    temp_v0_6 = ynw;
                    yn_mc_set_current(temp_v0_6 + 0x10D0, M2C_FIELD(temp_v0_6, s8 *, 9));
                    yn_mc_gmfile_current_set(ynw + 0x10D0);
                } else if (temp_a1_4 & 0x3000) {
                    temp_a0_6 = M2C_FIELD(temp_v0, s8 *, 9);
                    temp_a2_2 = M2C_FIELD(temp_v0, u8 *, 0x1D);
                    temp_a3 = temp_a1_4 & 0x1000;
                    var_s0 = temp_a0_6;
loop_83:
                    if (temp_a1_4 & 0x2000) {
                        var_s0 -= 1;
                    }
                    if (temp_a3 != 0) {
                        var_s0 += 1;
                    }
                    temp_v0_7 = var_s0 + 2;
                    var_s0 = temp_v0_7 & 1;
                    if (temp_v0_7 < 0) {
                        var_v0_2 = 1 << var_s0;
                        if (var_s0 != 0) {
                            var_s0 -= 2;
                            goto block_90;
                        }
                    } else {
block_90:
                        var_v0_2 = 1 << var_s0;
                    }
                    if (!(temp_a2_2 & var_v0_2)) {
                        if (var_s0 == M2C_FIELD(temp_v0, s8 *, 9)) {

                        } else {
                            goto loop_83;
                        }
                    }
                    if (((s64) ((s64) temp_a0_6 << 0x38) >> 0x38) != var_s0) {
                        yn_cur2_sd((u8 *) temp_a0_6, temp_v0 + 9, temp_a2_2, temp_a3);
                    }
                    M2C_FIELD(ynw, s8 *, 9) = var_s0;
                }
            }
            goto block_293;
        case 5:                                     /* switch 1 */
            temp_v0_8 = yn_mc_gmfile_check(temp_v0 + 0x10D0);
            if (temp_v0_8 != -2) {
                yn_log_sd();
                switch (temp_v0_8) {                /* switch 3; irregular */
                case -1:                            /* switch 3 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x19) = 6;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x17;
                    break;
                case -7:                            /* switch 3 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x2C;
                    break;
                case -5:                            /* switch 3 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0x10;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0xA;
                    M2C_FIELD(ynw, s8 *, 0x17) = 0;
                    yn_log_sd(0x10U);
                    break;
                default:                            /* switch 3 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x22;
                    break;
                }
            }
            goto block_293;
        case 6:                                     /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x42) = 0xF;
            M2C_FIELD(ynw, s8 *, 0x43) = 2;
            M2C_FIELD(ynw, s8 *, 0x44) = 0x13;
            M2C_FIELD(ynw, s8 *, 0x45) = 0x16;
            M2C_FIELD(ynw, s8 *, 0x47) = 0x1F;
            M2C_FIELD(ynw, s8 *, 0x48) = 0;
            temp_v1_15 = *(u8 *)0x3F3714;
            if (temp_v1_15 & 0x40) {
                yn_common_shot_cancel(0xE, 0x13U, 2);
            } else if (temp_v1_15 & 0x20) {
                temp_a0_7 = ynw;
                M2C_FIELD(temp_a0_7, s32 *, 0xEC8) = (s32) (1 - M2C_FIELD(temp_a0_7, s8 *, 0xD));
                yn_dec_sd((u16) temp_a0_7, (int *)0x13, 2);
            } else if (temp_v1_15 & 0x400) {
                yn_cur1_sd(0xEU, 0x13, 2);
                temp_a1_5 = ynw;
                if (M2C_FIELD(temp_a1_5, s32 *, 0xEC8) != 0) {
                    M2C_FIELD(temp_a1_5, s8 *, 0x18) = 7;
                    temp_v1_16 = ynw;
                    M2C_FIELD(temp_v1_16, s8 *, 0x19) = (s8) M2C_FIELD(temp_v1_16, s8 *, 0x18);
                } else {
                    M2C_FIELD(temp_a1_5, s8 *, 0x19) = (s8) M2C_FIELD(temp_a1_5, s8 *, 0x18);
                    M2C_FIELD(ynw, s8 *, 0x18) = 8;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x18;
                }
            } else if (temp_v1_15 & 0x3000) {
                if (temp_v1_15 & 0x2000) {
                    temp_v1_17 = ynw;
                    M2C_FIELD(temp_v1_17, s8 *, 0xD) = (s8) (M2C_FIELD(temp_v1_17, s8 *, 0xD) - 1);
                }
                if (*(u8 *)0x3F3714 & 0x1000) {
                    temp_v1_18 = ynw;
                    M2C_FIELD(temp_v1_18, s8 *, 0xD) = (s8) (M2C_FIELD(temp_v1_18, s8 *, 0xD) + 1);
                }
                temp_v0_9 = ynw;
                M2C_FIELD(temp_v0_9, s8 *, 0xD) = (s8) ((s32) (M2C_FIELD(temp_v0_9, s8 *, 0xD) + 2) % 2);
                yn_cur2_sd(temp_v0_9 + 0xD, (u8 *)0x13, 2U);
            }
            goto block_293;
        case 7:                                     /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x42) = 0x10;
            M2C_FIELD(ynw, s8 *, 0x43) = 2;
            M2C_FIELD(ynw, s8 *, 0x44) = 0x13;
            M2C_FIELD(ynw, s8 *, 0x45) = 0x17;
            M2C_FIELD(ynw, s8 *, 0x47) = 0x20;
            temp_v1_19 = ynw;
            M2C_FIELD(temp_v1_19, s8 *, 0x48) = (s8) M2C_FIELD(temp_v1_19, s8 *, 0xE);
            temp_v1_20 = *(u8 *)0x3F3714;
            if (temp_v1_20 & 0x40) {
                yn_common_shot_cancel(0xE, 0x13U, 2);
            } else if (temp_v1_20 & 0x20) {
                yn_dec_sd(0xEU, (int *)0x13, 2);
                temp_a1_6 = ynw;
                temp_v1_21 = M2C_FIELD(temp_a1_6, s8 *, 0xE);
                switch (temp_v1_21) {               /* switch 4; irregular */
                case 0:                             /* switch 4 */
                    M2C_FIELD(temp_a1_6, s8 *, 0x18) = 0xB;
                    yn_keyboard_init(1, ynw + 0xED0);
                    break;
                case 1:                             /* switch 4 */
                    M2C_FIELD(temp_a1_6, s8 *, 0x18) = 0xC;
                    yn_port_init(ynw + 0xECC, temp_a1_6);
                    break;
                case 2:                             /* switch 4 */
                    M2C_FIELD(temp_a1_6, s8 *, 0x18) = 0xB;
                    yn_keyboard_init(1, ynw + 0xFD0);
                    break;
                case 3:                             /* switch 4 */
                    M2C_FIELD(temp_a1_6, s8 *, 0x18) = 0xC;
                    yn_port_init(ynw + 0xECE, temp_a1_6);
                    break;
                }
            } else if (temp_v1_20 & 0x800) {
                M2C_FIELD(ynw, s8 *, 0x18) = 6;
                yn_cur1_sd(0xEU, 0x13, 2);
            } else if (temp_v1_20 & 0x400) {
                temp_v1_22 = ynw;
                if ((M2C_FIELD(temp_v1_22, u8 *, 0xED0) == 0) || (M2C_FIELD(temp_v1_22, u16 *, 0xECC) == 0)) {
                    yn_ng_sd(0xE, 0x13, 2);
                } else {
                    M2C_FIELD(temp_v1_22, s8 *, 0x18) = 8;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x18;
                    yn_cur1_sd(0xEU, 0x13, 2);
                }
            } else if (temp_v1_20 & 0x3000) {
                if (temp_v1_20 & 0x2000) {
                    temp_v1_23 = ynw;
                    M2C_FIELD(temp_v1_23, s8 *, 0xE) = (s8) (M2C_FIELD(temp_v1_23, s8 *, 0xE) - 1);
                }
                if (*(u8 *)0x3F3714 & 0x1000) {
                    temp_v1_24 = ynw;
                    M2C_FIELD(temp_v1_24, s8 *, 0xE) = (s8) (M2C_FIELD(temp_v1_24, s8 *, 0xE) + 1);
                }
                temp_v0_10 = ynw;
                M2C_FIELD(temp_v0_10, s8 *, 0xE) = (s8) ((s32) (M2C_FIELD(temp_v0_10, s8 *, 0xE) + 4) % 4);
                yn_cur2_sd(temp_v0_10 + 0xE, (u8 *)0x13, 2U);
            }
            goto block_293;
        case 8:                                     /* switch 1 */
            temp_a1_7 = *(u8 *)0x3F3714;
            temp_a0_8 = temp_a1_7 & 0x40;
            if (temp_a0_8 != 0) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = 6;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd(temp_a0_8, temp_a1_7, temp_a2);
            } else {
                temp_a0_9 = temp_a1_7 & 0x20;
                if (temp_a0_9 != 0) {
                    if (M2C_FIELD(temp_v0, s8 *, 0x17) != 0) {
                        M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) (temp_a2 + 1);
                        yn_dec_sd(temp_a0_9, (int *) temp_a1_7, temp_a2);
                        M2C_FIELD(ynw, s8 *, 0x18) = 0xA;
                        M2C_FIELD(ynw, s8 *, 0x46) = 0x32;
                        yn_proxy_wk_save(0xA);
                    } else {
                        M2C_FIELD(temp_v0, s8 *, 0x18) = 6;
                        M2C_FIELD(ynw, s8 *, 0x46) = 0;
                        yn_can_sd(temp_a0_9, temp_a1_7, temp_a2);
                    }
                } else if (temp_a1_7 & 0x3000) {
                    if (temp_a1_7 & 0x2000) {
                        M2C_FIELD(temp_v0, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v0, s8 *, 0x17) - 1);
                    }
                    if (*(u8 *)0x3F3714 & 0x1000) {
                        temp_v1_25 = ynw;
                        M2C_FIELD(temp_v1_25, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v1_25, s8 *, 0x17) + 1);
                    }
                    temp_v0_11 = ynw;
                    M2C_FIELD(temp_v0_11, s8 *, 0x17) = (s8) ((s32) (M2C_FIELD(temp_v0_11, s8 *, 0x17) + 2) % 2);
                    yn_cur2_sd(temp_v0_11 + 0x17, (u8 *) temp_a1_7, (u8) temp_a2);
                }
            }
            goto block_293;
        case 9:                                     /* switch 1 */
            temp_v0_12 = yn_mc_gmfile_save(temp_v0 + 0x10D0);
            if (temp_v0_12 != -2) {
                yn_log_sd();
                switch (temp_v0_12) {               /* switch 5; irregular */
                case -1:                            /* switch 5 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xA;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x13;
                    break;
                case -7:                            /* switch 5 */
                case -3:                            /* switch 5 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x14;
                    break;
                case -6:                            /* switch 5 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x1F;
                    break;
                case -5:                            /* switch 5 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x46) = 9;
                    break;
                default:                            /* switch 5 */
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x22;
                    break;
                }
            }
            goto block_293;
        case 10:                                    /* switch 1 */
            if (*(u8 *)0x3F3714 & 0x20) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = 0;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_dec_sd((u16) var_a0);
                return -2;
            }
            goto block_293;
        case 11:                                    /* switch 1 */
            if (yn_keyboard_sub(var_a0) != 0) {
                temp_v1_26 = ynw;
                M2C_FIELD(temp_v1_26, s8 *, 0x18) = (s8) M2C_FIELD(temp_v1_26, s8 *, 0x19);
            }
            goto block_293;
        case 12:                                    /* switch 1 */
            M2C_FIELD(temp_v0, s8 *, 0x39) = 2;
            temp_a1_8 = *(u8 *)0x3F3714;
            if (temp_a1_8 & 0x40) {
                temp_v1_27 = ynw;
                M2C_FIELD(temp_v1_27, s8 *, 0x18) = (s8) M2C_FIELD(temp_v1_27, s8 *, 0x19);
                temp_v0_13 = ynw;
                *M2C_FIELD(temp_v0_13, u16 **, 0x3C) = M2C_FIELD(temp_v0_13, u16 *, 0x3A);
                M2C_FIELD(ynw, s8 *, 0x38) = 0;
                yn_can_sd((u16) var_a0, temp_a1_8, temp_a2);
            } else if (temp_a1_8 & 0x20) {
                temp_v1_28 = ynw;
                M2C_FIELD(temp_v1_28, s8 *, 0x18) = (s8) M2C_FIELD(temp_v1_28, s8 *, 0x19);
                M2C_FIELD(ynw, s8 *, 0x38) = 0;
                yn_dec_sd((u16) var_a0, (int *) temp_a1_8, temp_a2);
            } else if (temp_a1_8 & 0xC00) {
                if (temp_a1_8 & 0x800) {
                    temp_v1_29 = ynw;
                    var_a0 = temp_v1_29 + 0x40;
                    temp_v1_30 = M2C_FIELD(temp_v1_29, u16 *, 0x40);
                    if (temp_v1_30 != 0x2710) {
                        M2C_FIELD(temp_v1_29, u16 *, 0x40) = (u16) (temp_v1_30 * 0xA);
                        temp_v1_31 = ynw;
                        M2C_FIELD(temp_v1_31, s8 *, 0x38) = (s8) (M2C_FIELD(temp_v1_31, s8 *, 0x38) + 1);
                    }
                }
                if (*(u8 *)0x3F3714 & 0x400) {
                    temp_v1_32 = ynw;
                    var_a0 = temp_v1_32 + 0x40;
                    if (M2C_FIELD(temp_v1_32, u16 *, 0x40) != 1) {
                        M2C_FIELD(temp_v1_32, u16 *, 0x40) = (u16) (M2C_FIELD(temp_v1_32, u16 *, 0x40) / 10);
                        temp_v1_33 = ynw;
                        M2C_FIELD(temp_v1_33, s8 *, 0x38) = (s8) (M2C_FIELD(temp_v1_33, s8 *, 0x38) - 1);
                    }
                }
                yn_cur2_sd(var_a0, (u8 *) temp_a1_8, (u8) temp_a2);
            } else {
                temp_a2_3 = ynw;
                if ((temp_a1_8 | M2C_FIELD(temp_a2_3, s32 *, 0x28)) & 0x3000) {
                    temp_t0 = M2C_FIELD(temp_a2_3, u16 **, 0x3C);
                    temp_t1 = M2C_FIELD(temp_a2_3, u16 *, 0x40);
                    temp_a3_2 = *temp_t0;
                    if (temp_t1 == 0) {
                        M2C_BREAK(0);
                    }
                    temp_v0_14 = temp_a1_8 | M2C_FIELD(temp_a2_3, s32 *, 0x28);
                    temp_a2_4 = M2C_FIELD(temp_a2_3, u16 *, 0x40);
                    temp_a1_9 = temp_v0_14 & 0x2000;
                    var_t2 = (s32) ((s32) temp_a3_2 / (s32) temp_t1) % 10;
                    temp_a0_10 = temp_v0_14 & 0x1000;
                    temp_a3_3 = temp_a3_2 - (temp_t1 * var_t2);
                    do {
                        if (temp_a1_9 != 0) {
                            var_t2 = (s32) ((u32) (var_t2 + 9) % 10U);
                        }
                        if (temp_a0_10 != 0) {
                            var_t2 = (s32) ((u32) (var_t2 + 0xB) % 10U);
                        }
                        temp_v0_15 = temp_a3_3 + (var_t2 * temp_a2_4);
                    } while (temp_v0_15 >= 0x10000U);
                    *temp_t0 = temp_v0_15;
                    yn_cur2_sd((u8 *) temp_a0_10, (u8 *) temp_a1_9, (u8) temp_a2_4, temp_a3_3);
                }
            }
            goto block_293;
        case 13:                                    /* switch 1 */
            temp_a1_10 = *(u8 *)0x3F3714;
            temp_a0_11 = temp_a1_10 & 0x40;
            if (!(temp_a1_10 & 0x20)) {
                if (temp_a0_11 != 0) {
                    goto block_222;
                }
            } else {
block_222:
                M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) M2C_FIELD(temp_v0, s8 *, 0x19);
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_dec_sd(temp_a0_11, (int *) temp_a1_10, temp_a2);
            }
            goto block_293;
        case 14:                                    /* switch 1 */
            temp_a1_11 = *(u8 *)0x3F3714;
            temp_a0_12 = temp_a1_11 & 0x40;
            if (temp_a0_12 != 0) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) M2C_FIELD(temp_v0, s8 *, 0x19);
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd(temp_a0_12, temp_a1_11, temp_a2);
                goto block_293;
            }
            if (temp_a1_11 & 0x20) {
                temp_a0_13 = M2C_FIELD(temp_v0, s8 *, 0x17);
                if (temp_a0_13 != 0) {
                    M2C_FIELD(temp_v0, s8 *, 0x18) = 0;
                    yn_dec_sd((u16) temp_a0_13, (int *) temp_a1_11, temp_a2);
                    M2C_FIELD(ynw, s8 *, 0x46) = 0;
                    return -2;
                }
                M2C_FIELD(temp_v0, s8 *, 0x18) = (s8) M2C_FIELD(temp_v0, s8 *, 0x19);
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd((u16) temp_a0_13, temp_a1_11, temp_a2);
                goto block_293;
            }
            if (temp_a1_11 & 0x3000) {
                if (temp_a1_11 & 0x2000) {
                    M2C_FIELD(temp_v0, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v0, s8 *, 0x17) - 1);
                }
                if (*(u8 *)0x3F3714 & 0x1000) {
                    temp_v1_34 = ynw;
                    M2C_FIELD(temp_v1_34, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v1_34, s8 *, 0x17) + 1);
                }
                temp_v0_16 = ynw;
                M2C_FIELD(temp_v0_16, s8 *, 0x17) = (s8) ((s32) (M2C_FIELD(temp_v0_16, s8 *, 0x17) + 2) % 2);
                yn_cur2_sd(temp_v0_16 + 0x17, (u8 *) temp_a1_11, (u8) temp_a2);
            }
            goto block_293;
        case 15:                                    /* switch 1 */
            if (*(u8 *)0x3F3714 & 0x20) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = 0;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_dec_sd((u16) var_a0);
                return -2;
            }
            goto block_293;
        case 16:                                    /* switch 1 */
            temp_a1_12 = *(u8 *)0x3F3714;
            temp_a0_14 = temp_a1_12 & 0x40;
            if (temp_a0_14 != 0) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = 2;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd(temp_a0_14, temp_a1_12, temp_a2);
            } else {
                temp_a0_15 = temp_a1_12 & 0x20;
                if (temp_a0_15 != 0) {
                    if (M2C_FIELD(temp_v0, s8 *, 0x17) != 0) {
                        M2C_FIELD(temp_v0, s8 *, 0x18) = 0x11;
                        M2C_FIELD(ynw, s8 *, 0x46) = 0xB;
                        yn_dec_sd(0xBU, (int *) temp_a1_12, temp_a2);
                        yn_mc_init(ynw + 0x10D0);
                    } else {
                        M2C_FIELD(temp_v0, s8 *, 0x18) = 2;
                        M2C_FIELD(ynw, s8 *, 0x46) = 0;
                        yn_can_sd(temp_a0_15, temp_a1_12, temp_a2);
                    }
                } else if (temp_a1_12 & 0x3000) {
                    if (temp_a1_12 & 0x2000) {
                        M2C_FIELD(temp_v0, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v0, s8 *, 0x17) - 1);
                    }
                    if (*(u8 *)0x3F3714 & 0x1000) {
                        temp_v1_35 = ynw;
                        M2C_FIELD(temp_v1_35, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v1_35, s8 *, 0x17) + 1);
                    }
                    temp_v0_17 = ynw;
                    M2C_FIELD(temp_v0_17, s8 *, 0x17) = (s8) ((s32) (M2C_FIELD(temp_v0_17, s8 *, 0x17) + 2) % 2);
                    yn_cur2_sd(temp_v0_17 + 0x17, (u8 *) temp_a1_12, (u8) temp_a2);
                }
            }
            goto block_293;
        case 17:                                    /* switch 1 */
            temp_v0_18 = yn_mc_format(temp_v0 + 0x10D0);
            switch (temp_v0_18) {                   /* switch 6; irregular */
            case -2:                                /* switch 6 */
                break;
            case -1:                                /* switch 6 */
                M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                M2C_FIELD(ynw, s8 *, 0x19) = 5;
                M2C_FIELD(ynw, s8 *, 0x46) = 0xC;
                yn_mc_init(ynw + 0x10D0, (int *)0xD);
                yn_log_sd();
                break;
            default:                                /* switch 6 */
                M2C_FIELD(ynw, s8 *, 0x18) = 0xD;
                M2C_FIELD(ynw, s8 *, 0x19) = 2;
                M2C_FIELD(ynw, s8 *, 0x46) = 0xD;
                yn_mc_init(ynw + 0x10D0);
                yn_log_sd();
                break;
            }
            goto block_293;
        case 18:                                    /* switch 1 */
            yn_strcpy(ynw + 0x1ACB4, yn_netcnf_search_usr_name(temp_v0 + 0x1180, temp_v0 + (M2C_FIELD(temp_v0, s8 *, 0xB) * 0x1340) + 0xAF00, temp_a2));
            temp_v1_36 = ynw;
            if ((temp_v1_36 + 0x1ACB4) != NULL) {
                if (M2C_FIELD(temp_v1_36, s8 *, 0x1ACB4) == 0) {
                    goto block_266;
                }
                if (yn_netcnf_magicno_check(temp_v1_36 + 0x1180) != 0) {
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0x1D;
                    yn_log_sd(0xFU);
                    goto block_293;
                }
                temp_a1_13 = ynw;
                temp_a0_16 = M2C_FIELD(((M2C_FIELD(temp_a1_13, s8 *, 0xB) * 0x14) + temp_a1_13), s32 *, 0x254);
                if (temp_a0_16 < 0) {
                    M2C_FIELD(temp_a1_13, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 5;
                    yn_log_sd((u8) temp_a0_16, temp_a1_13);
                    goto block_293;
                }
                if (yn_hard_select_set(temp_a0_16, temp_a1_13) < 0) {
                    M2C_FIELD(ynw, s8 *, 0x18) = 0xF;
                    M2C_FIELD(ynw, s8 *, 0x46) = 5;
                    yn_log_sd(0xFU);
                    goto block_293;
                }
                if (yn_netcnf_pastproxy_check(ynw + 0xEC8, D_5310D0) < 0) {
                    M2C_FIELD(ynw, s8 *, 0x26) = 1;
                }
                temp_a1_14 = ynw;
                if (yn_netcnf_pastdata_check(D_5306B0, temp_a1_14 + (M2C_FIELD(temp_a1_14, s8 *, 0xB) * 0x14) + 0x250, 1) < 0) {
                    M2C_FIELD(ynw, s8 *, 0x26) = 1;
                }
                temp_a0_17 = ynw;
                yn_backup_allwork(M2C_FIELD(((M2C_FIELD(temp_a0_17, s8 *, 0xB) * 0x14) + temp_a0_17), s32 *, 0x260));
                temp_a0_18 = ynw;
                yn_setup_allwork(M2C_FIELD(((M2C_FIELD(temp_a0_18, s8 *, 0xB) * 0x14) + temp_a0_18), s32 *, 0x260));
                return 1;
            }
block_266:
            M2C_FIELD(temp_v1_36, s8 *, 0x18) = 0xF;
            M2C_FIELD(ynw, s8 *, 0x46) = 0x33;
            yn_log_sd();
            goto block_293;
        case 19:                                    /* switch 1 */
            temp_a1_15 = *(u8 *)0x3F3714;
            temp_a0_19 = temp_a1_15 & 0x40;
            if (temp_a0_19 != 0) {
                M2C_FIELD(temp_v0, s8 *, 0x18) = 1;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd(temp_a0_19, temp_a1_15, temp_a2);
                goto block_293;
            }
            temp_a0_20 = temp_a1_15 & 0x20;
            if (temp_a0_20 != 0) {
                if (M2C_FIELD(temp_v0, s8 *, 0x17) != 0) {
                    M2C_FIELD(temp_v0, s8 *, 0x18) = 0;
                    M2C_FIELD(ynw, s8 *, 0x46) = 0;
                    yn_dec_sd(temp_a0_20, (int *) temp_a1_15, temp_a2);
                    return 2;
                }
                M2C_FIELD(temp_v0, s8 *, 0x18) = 1;
                M2C_FIELD(ynw, s8 *, 0x46) = 0;
                yn_can_sd(temp_a0_20, temp_a1_15, temp_a2);
                goto block_293;
            }
            if (temp_a1_15 & 0x3000) {
                if (temp_a1_15 & 0x2000) {
                    M2C_FIELD(temp_v0, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v0, s8 *, 0x17) - 1);
                }
                if (*(u8 *)0x3F3714 & 0x1000) {
                    temp_v1_37 = ynw;
                    M2C_FIELD(temp_v1_37, s8 *, 0x17) = (s8) (M2C_FIELD(temp_v1_37, s8 *, 0x17) + 1);
                }
                temp_v0_19 = ynw;
                M2C_FIELD(temp_v0_19, s8 *, 0x17) = (s8) ((s32) (M2C_FIELD(temp_v0_19, s8 *, 0x17) + 2) % 2);
                yn_cur2_sd(temp_v0_19 + 0x17, (u8 *) temp_a1_15, (u8) temp_a2);
            }
            goto block_293;
        }
    } else {
block_293:
        return 0;
    }
}

#if 0 /* yn_common_shot_cancel: m2c draft, does not compile yet */
void yn_common_shot_cancel(s8 arg0) {
    s8 temp_v1;
    s8 var_a0;
    u8 *temp_a1;

    var_a0 = arg0;
    temp_a1 = ynw;
    M2C_FIELD(temp_a1, s8 *, 0x19) = (s8) M2C_FIELD(temp_a1, s8 *, 0x18);
    M2C_FIELD(ynw, s8 *, 0x18) = var_a0;
    M2C_FIELD(ynw, s8 *, 0x17) = 0;
    if ((yn_r_no == 6) && ((var_a0 = (s8) ynw, temp_v1 = M2C_FIELD(var_a0, s8 *, 0x19), (temp_v1 == 6)) || (temp_v1 == 7))) {
        M2C_FIELD(var_a0, s8 *, 0x46) = 0x38;
    } else {
        M2C_FIELD(ynw, s8 *, 0x46) = 1;
    }
    yn_can_sd((u8 *) var_a0, temp_a1);
}
#endif

s32 yn_common_memcard_out(void) {
    s32 temp_s0;
    u8 *temp_v0;

    temp_s0 = 0;
    if (yn_mc_device_check_all(ynw + 0x10D0) >= 0) {
        temp_v0 = ynw;
        temp_s0 |= ((M2C_FIELD(temp_v0, u8 *, 0x10D2) | M2C_FIELD(temp_v0, u8 *, 0x10D3)) >> 1) & 3;
        if (!(temp_s0 & (1 << yn_mc_get_current(temp_v0 + 0x10D0)))) {
            return 1;
        }
    }
    return 0;
}

/*
Decompilation failure in function yn_sprite_draw:

Unable to determine jump table for jr instruction at tmpgya281qg.s line 18.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

/*
Decompilation failure in function yn_button_draw:

Unable to determine jump table for jr instruction at tmpfh_ao2x3.s line 18.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

/*
Decompilation failure in function yn_button_font:

Unable to determine jump table for jr instruction at tmpqoo3mo3s.s line 21.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

void yn_title_font(void) {
    char *temp_s0;

    temp_s0 = yn_title_mes_tbl[M2C_FIELD(ynw, s8 *, 0x44)];
    yn_printf(yn_center_x(temp_s0, 0x16), 0x20, temp_s0);
}

/*
Decompilation failure in function yn_message_font:

Unable to determine jump table for jr instruction at tmpwqzzu240.s line 21.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

#if 0 /* yn_message_font_sub: m2c draft, does not compile yet */
void yn_message_font_sub(void) {
    s16 var_a0;
    s64 var_s0;
    s8 temp_a1;
    s8 temp_s1;
    u8 *var_s2;

    temp_a1 = M2C_FIELD(ynw, s8 *, 0x45);
    temp_s1 = *(yn_mess_cnt_tbl + temp_a1);
    var_s2 = yn_mess_mes_tbl[temp_a1];
    var_s0 = 0;
    if (temp_s1 > 0) {
        do {
            var_a0 = M2C_FIELD(var_s2, s16 *, 0);
            if (var_a0 == -1) {
                var_a0 = (s16) ((s64) (yn_center_x(M2C_FIELD(var_s2, s32 *, 4), 0x16) << 0x30) >> 0x30);
            }
            yn_printf((s64) var_a0, M2C_FIELD(var_s2, s16 *, 2), M2C_FIELD(var_s2, s32 *, 4));
            var_s0 = (s64) ((var_s0 + 1) << 0x38) >> 0x38;
            var_s2 += 8;
        } while (var_s0 < temp_s1);
    }
}
#endif

void yn_connect_font_sub(void) {
    u8 sp130[0x100];
    u8 sp30[0x100];
    int i;
    int y;
    u8 *p;
    u8 *r;
    u8 *q;

    yn_set_pal(0);
    yn_printf(0x2C, 0x53, yn_memcard_mes_tbl[1 + yn_mc_get_current(ynw + 0x10D0)]);
    i = 0;
    y = 0xCB;
    for (; i < 2; i++, y += 0x1C) {
        if (M2C_FIELD(ynw, s8 *, 0x16) + i >= M2C_FIELD(ynw, s8 *, 0x1C)) {
            break;
        }
        p = ynw + (M2C_FIELD(ynw, s8 *, 0xC) + i) * 0x14;
        if (M2C_FIELD(p, s32 *, 0x254) == -1) {
            yn_set_pal(2);
        } else if (M2C_FIELD(p, s32 *, 0x250) == 2) {
            yn_set_pal(9);
        }
        r = (u8 *)yn_netcnf_search_usr_name(ynw + 0x1180, ynw + (M2C_FIELD(ynw, s8 *, 0xC) + i) * 0x1340 + 0xAF00);
        if (r == 0 || M2C_FIELD(ynw + (M2C_FIELD(ynw, s8 *, 0xC) + i) * 0x14, s32 *, 0x250) == 2) {
            yn_set_pal(2);
            strcpy(sp130, lit_4084);
        } else {
            yn_strconv2(sp30, r, 0x2C);
            yn_utf8_to_sjis(sp130, sp30);
        }
        sprintf(sp30, lit_4085, M2C_FIELD(ynw, s8 *, 0xC) + (i + 1), sp130);
        yn_printf(0x2C, (s16)y, sp30);
        yn_set_pal(0);
    }
    q = ynw;
    if (M2C_FIELD(q, s8 *, 8) >= 2) {
        p = M2C_FIELD(q, s8 *, 0xB) * 0x14 + q;
        if (M2C_FIELD(p, s32 *, 0x250) == 0) {
            strcpy(sp130, lit_4086);
        } else {
            sprintf(sp130, lit_4087, M2C_FIELD(p, s32 *, 0x258), M2C_FIELD(p, s32 *, 0x25C));
        }
        yn_printf(0x2C, 0x108, sp130);
    }
}

#if 0 /* yn_hard_font_sub: m2c draft, does not compile yet */
void yn_hard_font_sub(void) {
    int sp50;
    int *var_s1;
    s32 temp_v1;
    s32 var_s2;
    s32 var_s3;
    s64 var_s0;

    var_s2 = 0;
    yn_set_pal(0);
    var_s3 = 0;
    var_s1 = DeviceWork;
    var_s0 = 0xC4;
    do {
        temp_v1 = M2C_FIELD(var_s1, s32 *, 0);
        if (temp_v1 != -1) {
            if (temp_v1 == 1) {
                yn_set_pal(0);
            } else {
                yn_set_pal(9);
            }
            if ((M2C_FIELD(var_s1, s32 *, 0) == 1) && (var_s2 >= M2C_FIELD(ynw, s8 *, 0x15))) {
                sprintf((u8 *)&sp50, lit_4118, M2C_FIELD(var_s1, s32 *, 0x14), M2C_FIELD(var_s1, s32 *, 0x18));
                yn_printf(0x65, (s64) (var_s0 << 0x30) >> 0x30, (u8 *)&sp50);
                var_s0 += 0x1C;
            }
            var_s2 += 1;
        }
        var_s3 += 1;
        var_s1 += 0x1C;
    } while (var_s3 < 0x23);
    yn_set_pal(0);
}
#endif

void yn_hard_more_font_sub(void) {
    int i;
    int y;

    i = 0;
    y = 0xC4;
    do {
        yn_printf(0x65, (s16)y, yn_hard_more_mes_tbl[M2C_FIELD(ynw, s8 *, 0x14) + (s8)i]);
        i = (s8)(i + 1);
        y += 0x1C;
    } while (i < 3);
}

#if 0 /* yn_memcard_font_sub: m2c draft, does not compile yet */
void yn_memcard_font_sub(void) {
    int *var_s1;
    s64 var_s0;
    s64 var_s2;

    var_s2 = 0;
    var_s1 = yn_memcard_mes_tbl;
    var_s0 = 0xC4;
    do {
        if (M2C_FIELD(ynw, u8 *, 0x1D) & (1 << ((s64) (var_s2 << 0x38) >> 0x38))) {
            yn_set_pal(0);
        } else {
            yn_set_pal(9);
        }
        yn_printf(0xCF, (s64) (var_s0 << 0x30) >> 0x30, M2C_FIELD(var_s1, s32 *, 4));
        var_s1 += 4;
        var_s2 = (s64) ((var_s2 + 1) << 0x38) >> 0x38;
        var_s0 += 0x38;
    } while (var_s2 < 2);
    yn_set_pal(0);
}
#endif

#if 0 /* yn_id_pw_font_sub: m2c draft, does not compile yet */
void yn_id_pw_font_sub(void) {
    int sp50;
    int sp10;
    int *var_a0;
    int *var_a2;
    s32 temp_v0_3;
    s32 var_a1;
    s32 var_a1_2;
    s8 *var_a2_2;
    u8 *temp_v0;
    u8 *temp_v0_2;
    u8 *var_v0;

    temp_v0 = ynw;
    if (M2C_FIELD(temp_v0, u8 *, 0x4B4) == 0) {
        yn_printf(0x115, 0xC4, lit_4217);
    } else {
        sceNetcnfifConvAuthname(temp_v0 + 0x4B4, (u8 *)&sp10, 0x20);
        yn_strconv((u8 *)&sp50, (u8 *)&sp10, 0x18);
        yn_printf(0x115, 0xC4, (u8 *)&sp50);
    }
    temp_v0_2 = ynw;
    if (M2C_FIELD(temp_v0_2, u8 *, 0x6B4) == 0) {
        yn_printf(0x115, 0xFC, lit_4218);
        return;
    }
    temp_v0_3 = yn_strlen(temp_v0_2 + 0x6B4);
    var_a1 = 0;
    if (temp_v0_3 >= 0x19) {
        var_a0 = (u8 *)&sp50;
        do {
            M2C_FIELD(var_a0, s8 *, 0) = 0x2A;
            M2C_FIELD(var_a0, s8 *, 1) = 0x2A;
            var_a1 += 7;
            M2C_FIELD(var_a0, s8 *, 2) = 0x2A;
            M2C_FIELD(var_a0, s8 *, 3) = 0x2A;
            M2C_FIELD(var_a0, s8 *, 4) = 0x2A;
            M2C_FIELD(var_a0, s8 *, 5) = 0x2A;
            M2C_FIELD(var_a0, s8 *, 6) = 0x2A;
            var_a0 += 7;
        } while (var_a1 < 0xF);
        M2C_FIELD((var_a1 + sp), s8 *, 0x50) = 0x2A;
        M2C_FIELD((var_a1 + 1 + sp), s8 *, 0x50) = 0x2E;
        M2C_FIELD((var_a1 + 2 + sp), s8 *, 0x50) = 0x2E;
        var_v0 = var_a1 + 3 + sp;
    } else {
        var_a1_2 = 0;
        if (temp_v0_3 > 0) {
            if (temp_v0_3 >= 9) {
                var_a2 = (u8 *)&sp50;
                do {
                    M2C_FIELD(var_a2, s8 *, 0) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 1) = 0x2A;
                    var_a1_2 += 8;
                    M2C_FIELD(var_a2, s8 *, 2) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 3) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 4) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 5) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 6) = 0x2A;
                    M2C_FIELD(var_a2, s8 *, 7) = 0x2A;
                    var_a2 += 8;
                } while (var_a1_2 < (temp_v0_3 - 8));
            }
            if (var_a1_2 < temp_v0_3) {
                var_a2_2 = var_a1_2 + sp + 0x50;
                do {
                    var_a1_2 += 1;
                    *var_a2_2 = 0x2A;
                    var_a2_2 += 1;
                } while (var_a1_2 < temp_v0_3);
            }
        }
        var_v0 = var_a1_2 + sp;
    }
    M2C_FIELD(var_v0, s8 *, 0x50) = 0;
    yn_printf(0x115, 0xFC, (u8 *)&sp50);
}
#endif

#if 0 /* yn_ipadrs_font_sub: m2c draft, does not compile yet */
void yn_ipadrs_font_sub(u8 *arg0, int arg1, int arg2) {
    int sp10;
    int *var_a3;
    s32 temp_t1;
    s32 temp_t1_2;
    s32 temp_t5;
    s32 temp_t7_2;
    s32 var_t0;
    u32 temp_t6;
    u8 *var_a0;
    u8 temp_t7;
    u8 *temp_a3;

    var_a0 = arg0;
    var_t0 = 0;
    var_a3 = (u8 *)&sp10;
    do {
        temp_t7 = *var_a0;
        temp_t6 = temp_t7 >> 0x1F;
        temp_t5 = ((s32) ((*var_a0 / 10) + temp_t6) % 10) & 0xFF;
        temp_t7_2 = ((s32) temp_t7 % 10) & 0xFF;
        temp_t1 = ((*var_a0 / 100) + temp_t6) & 0xFF;
        var_a0 += 1;
        if (temp_t1 == 0) {
            temp_t1_2 = temp_t5 & 0xFF;
            M2C_FIELD(var_a3, s8 *, 0) = 0x20;
            if (temp_t1_2 == 0) {
                M2C_FIELD(var_a3, s8 *, 1) = 0x20;
            } else {
                M2C_FIELD(var_a3, s8 *, 1) = (s8) (temp_t1_2 + 0x30);
            }
        } else {
            M2C_FIELD(var_a3, s8 *, 0) = (s8) (temp_t1 + 0x30);
            M2C_FIELD(var_a3, s8 *, 1) = (s8) ((temp_t5 & 0xFF) + 0x30);
        }
        temp_a3 = var_a3 + 2;
        var_t0 += 1;
        M2C_FIELD(var_a3, s8 *, 2) = (s8) ((temp_t7_2 & 0xFF) + 0x30);
        M2C_FIELD(temp_a3, s8 *, 1) = 0x2E;
        M2C_FIELD(temp_a3, s8 *, 2) = 0x20;
        var_a3 = temp_a3 + 2 + 1;
    } while (var_t0 < 4);
    M2C_FIELD(var_a3, s8 *, -2) = 0;
    yn_printf(arg1, arg2, (u8 *)&sp10, var_a3);
}
#endif

#if 0 /* yn_port_font_sub: m2c draft, does not compile yet */
void yn_port_font_sub(u16 *arg0, int arg1, int arg2) {
    s8 sp78;
    int sp30;
    int *var_a0;
    int *var_a2;
    s32 temp_a3;
    s32 var_a1;
    s32 var_a1_2;
    s32 var_t1;
    s32 var_t3;
    s32 var_t4;
    s32 var_t5;
    s8 *var_a2_2;
    s8 *var_t2;
    u8 *temp_a1;

    var_t4 = 0;
    var_t3 = 0;
    var_a1 = 0x2710;
    var_t5 = 0;
    var_t2 = (u8 *)&sp78;
    do {
        if (var_a1 == 0) {
            M2C_BREAK(0);
        }
        *var_t2 = (s8) ((s32) ((s32) *arg0 / var_a1) % 10);
        var_a1 = (var_a1 / 10) + ((u32) var_a1 >> 0x1F);
        if (*var_t2 != 0) {
            var_t4 = 1;
        }
        if (var_t4 != 0) {
            var_t3 += 1;
        }
        var_t5 += 1;
        var_t2 += 1;
    } while (var_t5 < 5);
    if (var_t3 == 0) {
        var_t3 += 1;
    }
    temp_a1 = ynw;
    if (M2C_FIELD(temp_a1, s8 *, 0x39) != 0) {
        if (M2C_FIELD(temp_a1, s32 *, 0x3C) != arg0) {
            goto block_13;
        }
        var_t1 = 0;
        var_a0 = (u8 *)&sp30;
        do {
            M2C_FIELD(var_a0, s8 *, 0) = 0x20;
            M2C_FIELD(var_a0, s8 *, 1) = 0x20;
            var_t1 += 6;
            M2C_FIELD(var_a0, s8 *, 2) = 0x20;
            M2C_FIELD(var_a0, s8 *, 3) = 0x20;
            M2C_FIELD(var_a0, s8 *, 4) = 0x20;
            M2C_FIELD(var_a0, s8 *, 5) = 0x20;
            var_a0 += 6;
        } while (var_t1 < 7);
        M2C_FIELD((var_t1 + sp), s8 *, 0x30) = 0x20;
        M2C_FIELD((var_t1 + 1 + sp), s8 *, 0x30) = (s8) (sp78 + 0x30);
        M2C_FIELD((var_t1 + 2 + sp), s8 *, 0x30) = (s8) (sp79 + 0x30);
        M2C_FIELD((var_t1 + 3 + sp), s8 *, 0x30) = (s8) (sp7A + 0x30);
        M2C_FIELD((var_t1 + 4 + sp), s8 *, 0x30) = (s8) (sp7B + 0x30);
        M2C_FIELD((var_t1 + 5 + sp), s8 *, 0x30) = (s8) (sp7C + 0x30);
        M2C_FIELD((var_t1 + 6 + sp), s8 *, 0x30) = 0;
    } else {
block_13:
        temp_a3 = 0x12 - var_t3;
        var_a1_2 = 0;
        if (temp_a3 > 0) {
            if (temp_a3 >= 9) {
                var_a2 = (u8 *)&sp30;
                do {
                    M2C_FIELD(var_a2, s8 *, 0) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 1) = 0x20;
                    var_a1_2 += 8;
                    M2C_FIELD(var_a2, s8 *, 2) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 3) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 4) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 5) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 6) = 0x20;
                    M2C_FIELD(var_a2, s8 *, 7) = 0x20;
                    var_a2 += 8;
                } while (var_a1_2 < (temp_a3 - 8));
            }
            if (var_a1_2 < temp_a3) {
                var_a2_2 = var_a1_2 + sp + 0x30;
                do {
                    var_a1_2 += 1;
                    *var_a2_2 = 0x20;
                    var_a2_2 += 1;
                } while (var_a1_2 < temp_a3);
            }
        }
        sprintf(temp_a3 + sp + 0x30, lit_4358, *arg0, temp_a3);
    }
    yn_printf(arg1, arg2, (u8 *)&sp30);
}
#endif

void yn_prname_font_sub(u8 *arg0, s32 arg1, int arg2, int arg3, int arg4) {
    u8 sp140[0x100];
    u8 sp40[0x100];

    if (arg0 == 0) {
        yn_set_pal(2);
        strcpy(sp140, lit_4372);
        sprintf(sp40, lit_4085, arg1 + 1, sp140);
        yn_printf(arg2, arg3, sp40);
        yn_set_pal(0);
        return;
    }
    yn_strconv(sp40, arg0, arg4);
    yn_utf8_to_sjis(sp140, sp40);
    sprintf(sp40, lit_4085, arg1 + 1, sp140);
    yn_printf(arg2, arg3, sp40);
}

void yn_adname_font_sub(u8 *arg0, u8 *arg1, int arg2, int arg3, int arg4) {
    u8 buf[0x40];

    if (*arg0 == 0) {
        yn_printf(arg2, arg3, arg1);
        return;
    }
    yn_strconv(buf, arg0, arg4);
    yn_printf(arg2, arg3, buf);
}

void yn_dialog_draw(void) {
    u8 temp_v1;
    u8 *temp_a1;

    temp_v1 = M2C_FIELD(ynw, u8 *, 0x46);
    switch (temp_v1) {
    case 0x2:
    case 0x5:
    case 0x6:
    case 0x7:
    case 0x8:
    case 0x9:
    case 0xB:
    case 0xC:
    case 0xD:
    case 0xE:
    case 0xF:
    case 0x13:
    case 0x14:
    case 0x15:
    case 0x16:
    case 0x17:
    case 0x19:
    case 0x1B:
    case 0x1C:
    case 0x1D:
    case 0x1E:
    case 0x1F:
    case 0x20:
    case 0x21:
    case 0x22:
    case 0x24:
    case 0x2A:
    case 0x2B:
    case 0x2C:
    case 0x2D:
    case 0x2E:
    case 0x2F:
    case 0x32:
    case 0x33:
    case 0x34:
    case 0x36:
    case 0x39:
        yn_sprite_draw_sub(0x1B, 0, 2);
        return;
    case 0x1:
    case 0x3:
    case 0x4:
    case 0xA:
    case 0x18:
    case 0x1A:
    case 0x30:
    case 0x31:
    case 0x35:
    case 0x37:
    case 0x38:
        yn_sprite_draw_sub(0x1B, 0, 2);
        yn_sprite_draw_sub(0x1A, 0, (s16)(-M2C_FIELD(ynw, s8 *, 0x17) * 0x1E));
        return;
    case 0x10:
    case 0x11:
    case 0x12:
    case 0x25:
    case 0x26:
    case 0x27:
    case 0x28:
    case 0x29:
        yn_sprite_draw_sub(0x1B, 0, 2);
        temp_a1 = ynw;
        if (M2C_FIELD(temp_a1, s8 *, 0x1B) != 3) {
            yn_sprite_draw_sub(0x1A, 0, (s16)(-M2C_FIELD(temp_a1, s8 *, 0x17) * 0x1E));
            return;
        }
    default:
        break;
    case 0x23:
        yn_sprite_draw_sub(0x1B, 0, 2);
        yn_sprite_draw_sub(0x1E, 0, 0x24);
        break;
    }
}

/*
Decompilation failure in function yn_dialog_font:

Unable to determine jump table for jr instruction at tmpujrimknu.s line 23.

There must be a read of a variable before the instruction
which has a name starting with with "jtbl"/"jpt_"/"lbl_"/"jumptable_".
*/

#if 0 /* yn_dialog_font_sub: m2c draft, does not compile yet */
void yn_dialog_font_sub(void) {
    s16 var_a0;
    s64 var_s0;
    s8 temp_s1;
    u8 temp_a1;
    u8 *var_s2;

    temp_a1 = M2C_FIELD(ynw, u8 *, 0x46);
    temp_s1 = *(yn_dialog_cnt_tbl + temp_a1);
    var_s2 = yn_dialog_mes_tbl[temp_a1];
    var_s0 = 0;
    if (temp_s1 > 0) {
        do {
            var_a0 = M2C_FIELD(var_s2, s16 *, 0);
            if (var_a0 == -1) {
                var_a0 = (s16) ((s64) (yn_center_x(M2C_FIELD(var_s2, s32 *, 4), 0x16) << 0x30) >> 0x30);
            }
            yn_printf((s64) var_a0, M2C_FIELD(var_s2, s16 *, 2), M2C_FIELD(var_s2, s32 *, 4));
            var_s0 = (s64) ((var_s0 + 1) << 0x38) >> 0x38;
            var_s2 += 8;
        } while (var_s0 < temp_s1);
    }
}
#endif

#if 0 /* yn_dialog_font_without_yesno: m2c draft, does not compile yet */
void yn_dialog_font_without_yesno(void) {
    s16 var_a0;
    s64 temp_s2;
    s64 var_s0;
    u8 temp_a1;
    u8 *var_s1;

    temp_a1 = M2C_FIELD(ynw, u8 *, 0x46);
    var_s1 = yn_dialog_mes_tbl[temp_a1];
    temp_s2 = (s64) ((*(yn_dialog_cnt_tbl + temp_a1) - 3) << 0x38) >> 0x38;
    var_s0 = 0;
    if (temp_s2 > 0) {
        do {
            var_a0 = M2C_FIELD(var_s1, s16 *, 0);
            if (var_a0 == -1) {
                var_a0 = (s16) ((s64) (yn_center_x(M2C_FIELD(var_s1, s32 *, 4), 0x16) << 0x30) >> 0x30);
            }
            yn_printf((s64) var_a0, M2C_FIELD(var_s1, s16 *, 2), M2C_FIELD(var_s1, s32 *, 4));
            var_s0 = (s64) ((var_s0 + 1) << 0x38) >> 0x38;
            var_s1 += 8;
        } while (var_s0 < temp_s2);
    }
}
#endif

#if 0 /* yn_dialog_font_once: m2c draft, does not compile yet */
void yn_dialog_font_once(s32 arg0) {
    s16 var_a0;
    u8 *temp_a2;
    u8 *temp_s0;

    temp_a2 = ynw;
    temp_s0 = yn_dialog_mes_tbl[M2C_FIELD(temp_a2, u8 *, 0x46)] + (arg0 * 8);
    var_a0 = M2C_FIELD(temp_s0, s16 *, 0);
    if (var_a0 == -1) {
        var_a0 = (s16) ((s64) (yn_center_x(M2C_FIELD(temp_s0, s32 *, 4), 0x16, temp_a2) << 0x30) >> 0x30);
    }
    yn_printf((s64) var_a0, M2C_FIELD(temp_s0, s16 *, 2), M2C_FIELD(temp_s0, s32 *, 4));
}
#endif

#if 0 /* yn_dialog_font_memcard: m2c draft, does not compile yet */
void yn_dialog_font_memcard(s32 arg0) {
    int sp60;
    s16 var_s1;
    s64 var_s2;
    s8 temp_s0;
    u8 temp_a1;
    u8 *var_s3;

    temp_a1 = M2C_FIELD(ynw, u8 *, 0x46);
    temp_s0 = *(yn_dialog_cnt_tbl + temp_a1);
    var_s3 = yn_dialog_mes_tbl[temp_a1];
    var_s2 = 0;
    if (temp_s0 > 0) {
        do {
            var_s1 = M2C_FIELD(var_s3, s16 *, 0);
            if (var_s1 == -1) {
                var_s1 = (s16) ((s64) (yn_center_x(M2C_FIELD(var_s3, int **, 4), 0x16) << 0x30) >> 0x30);
            }
            if (((s64) (var_s2 << 0x38) >> 0x38) == arg0) {
                sprintf((u8 *)&sp60, M2C_FIELD(var_s3, int **, 4), yn_mc_get_current(ynw + 0x10D0) + 1);
                yn_printf((s64) var_s1, M2C_FIELD(var_s3, s16 *, 2), (u8 *)&sp60);
            } else {
                yn_printf((s64) var_s1, M2C_FIELD(var_s3, s16 *, 2), M2C_FIELD(var_s3, int **, 4));
            }
            var_s2 = (s64) ((var_s2 + 1) << 0x38) >> 0x38;
            var_s3 += 8;
        } while (var_s2 < temp_s0);
    }
}
#endif

#if 0 /* yn_dialog_font_setting: m2c draft, does not compile yet */
void yn_dialog_font_setting(void) {
    int sp250;
    int sp50;
    s32 temp_v1_2;
    s32 var_s1;
    s64 var_s0;
    u8 *temp_a1;
    u8 *temp_s2;
    u8 *temp_s3;
    u8 *temp_v1;

    var_s1 = saved_reg_s1;
    temp_a1 = ynw;
    temp_v1 = temp_a1 + (M2C_FIELD(temp_a1, s8 *, 0xB) * 0x14);
    temp_s2 = M2C_FIELD(temp_v1, u8 **, 0x260);
    temp_s3 = temp_v1 + 0x250;
    if (M2C_FIELD(temp_v1, s32 *, 0x250) == 1) {
        sprintf((u8 *)&sp250, lit_4679, M2C_FIELD(temp_s3, int **, 8), M2C_FIELD(temp_s3, s32 *, 0xC));
        yn_strconv((u8 *)&sp50, (u8 *)&sp250, 0x2E);
    } else {
        yn_set_pal(2, temp_a1);
        strcpy((u8 *)&sp50, lit_4680);
    }
    yn_set_pal(0);
    yn_printf(0x44, 0x82, (u8 *)&sp50);
    if ((temp_s2 != NULL) && (M2C_FIELD(temp_v1, s32 *, 0x250) == 1)) {
        temp_v1_2 = M2C_FIELD(temp_s2, s32 *, 0x1310);
        switch (temp_v1_2) {                        /* irregular */
        case 1:
            var_s1 = 0;
            break;
        case 2:
            var_s1 = 1;
            break;
        case 3:
            var_s1 = 2;
            break;
        case 5:
            var_s1 = 3;
            break;
        case 6:
            var_s1 = 4;
            break;
        }
        sprintf((u8 *)&sp250, lit_4681, yn_hard_more_mes_tbl[var_s1]);
        yn_strconv((u8 *)&sp50, (u8 *)&sp250, 0x2C);
        yn_printf(0x44, 0x9B, (u8 *)&sp50);
        var_s0 = 0xB4;
        if (M2C_FIELD(temp_s2, u8 *, 0x1325) == 1) {
            yn_strconv((u8 *)&sp250, temp_s2 + 0xB00, 0x1C);
            sceNetcnfifConvAuthname((u8 *)&sp250, (u8 *)&sp50, 0x100);
            sprintf((u8 *)&sp250, lit_4682, (u8 *)&sp50);
            yn_printf(0x44, (s64) (0xB4 << 0x30) >> 0x30, (u8 *)&sp250);
            var_s0 = 0xCD;
        } else if (M2C_FIELD(temp_s2, u8 *, 0x1320) == 1) {
            if (M2C_FIELD(temp_s2, s8 *, 0x200) == 0) {
                strcpy((u8 *)&sp250, lit_160_0053EA40);
            } else {
                yn_strconv((u8 *)&sp250, temp_s2 + 0x200, 0x1C);
            }
            sprintf((u8 *)&sp50, lit_4683, (u8 *)&sp250);
            yn_printf(0x44, (s64) (0xB4 << 0x30) >> 0x30, (u8 *)&sp50);
            var_s0 = 0xCD;
        } else if (M2C_FIELD(temp_s2, s8 *, 0x300) != 0) {
            yn_dialog_font_ip_sub((u8 *)&sp50, temp_s2 + 0x300);
            sprintf((u8 *)&sp250, lit_4684, (u8 *)&sp50);
            yn_printf(0x44, (s64) (0xB4 << 0x30) >> 0x30, (u8 *)&sp250);
            yn_dialog_font_ip_sub((u8 *)&sp50, temp_s2 + 0x400);
            sprintf((u8 *)&sp250, lit_4685, (u8 *)&sp50);
            yn_printf(0x44, (s64) (0xCD << 0x30) >> 0x30, (u8 *)&sp250);
            yn_dialog_font_ip_sub((u8 *)&sp50, temp_s2 + 0x500);
            sprintf((u8 *)&sp250, lit_4686, (u8 *)&sp50);
            yn_printf(0x44, (s64) (0xE6 << 0x30) >> 0x30, (u8 *)&sp250);
            var_s0 = 0xFF;
        }
        if (M2C_FIELD(temp_s2, s8 *, 0x600) == 0) {
            strcpy((u8 *)&sp250, lit_160_0053EA40);
        } else {
            yn_dialog_font_ip_sub((u8 *)&sp250, temp_s2 + 0x600);
        }
        sprintf((u8 *)&sp50, lit_4687, (u8 *)&sp250);
        yn_printf(0x44, (s64) (var_s0 << 0x30) >> 0x30, (u8 *)&sp50);
        if (M2C_FIELD(temp_s2, s8 *, 0x700) == 0) {
            if (M2C_FIELD(temp_s2, s8 *, 0x600) == 0) {
                strcpy((u8 *)&sp250, lit_160_0053EA40);
            } else {
                strcpy((u8 *)&sp250, lit_4372);
            }
        } else {
            yn_dialog_font_ip_sub((u8 *)&sp250, temp_s2 + 0x700);
        }
        sprintf((u8 *)&sp50, lit_4688, (u8 *)&sp250);
        yn_printf(0x44, (s64) ((var_s0 + 0x19) << 0x30) >> 0x30, (u8 *)&sp50);
    }
}
#endif

#if 0 /* yn_dialog_font_ip_sub: m2c draft, does not compile yet */
void yn_dialog_font_ip_sub(u8 *arg0, u8 *arg1) {
    u8 spC;
    s32 var_a2;
    s32 var_t0_2;
    s32 var_t3;
    s32 var_v1;
    u8 *var_a0;
    u8 *var_a1;
    u8 *var_t0;
    u8 *var_t4;
    u8 *var_t4_2;
    u8 temp_a3;
    u8 *temp_a0;
    u8 *temp_a0_2;
    u8 *temp_a0_3;

    var_a0 = arg0;
    var_a1 = arg1;
    var_a2 = 0;
    do {
        var_t4 = (u8 *)&spC;
        var_v1 = 0;
        var_t0 = var_t4;
loop_3:
        temp_a3 = *var_a1;
        if (temp_a3 != 0x2E) {
            if (temp_a3 == 0) {

            } else {
                *var_t0 = temp_a3;
                var_a1 += 1;
                var_t0 += 1;
                var_v1 += 1;
                goto loop_3;
            }
        }
        var_t0_2 = var_v1;
        if (var_v1 < 3) {
            do {
                var_t0_2 += 1;
                *var_a0 = 0x20;
                var_a0 += 1;
            } while (var_t0_2 < 3);
        }
        var_t3 = 0;
        if (var_v1 > 0) {
            if (var_v1 >= 9) {
                do {
                    var_t3 += 8;
                    M2C_FIELD(var_a0, u8 *, 0) = M2C_FIELD(var_t4, u8 *, 0);
                    M2C_FIELD(var_a0, u8 *, 1) = (u8) M2C_FIELD(var_t4, u8 *, 1);
                    temp_a0 = var_a0 + 2;
                    M2C_FIELD(var_a0, u8 *, 2) = (u8) M2C_FIELD(var_t4, u8 *, 2);
                    M2C_FIELD(temp_a0, u8 *, 1) = (u8) M2C_FIELD(var_t4, u8 *, 3);
                    temp_a0_2 = temp_a0 + 2;
                    M2C_FIELD(temp_a0, u8 *, 2) = (u8) M2C_FIELD(var_t4, u8 *, 4);
                    M2C_FIELD(temp_a0_2, u8 *, 1) = (u8) M2C_FIELD(var_t4, u8 *, 5);
                    temp_a0_3 = temp_a0_2 + 2;
                    M2C_FIELD(temp_a0_2, u8 *, 2) = (u8) M2C_FIELD(var_t4, u8 *, 6);
                    M2C_FIELD(temp_a0_3, u8 *, 1) = (u8) M2C_FIELD(var_t4, u8 *, 7);
                    var_t4 += 8;
                    var_a0 = temp_a0_3 + 2;
                } while (var_t3 < (var_v1 - 8));
            }
            if (var_t3 < var_v1) {
                var_t4_2 = var_t3 + sp + 0xC;
                do {
                    var_t3 += 1;
                    *var_a0 = *var_t4_2;
                    var_t4_2 += 1;
                    var_a0 += 1;
                } while (var_t3 < var_v1);
            }
        }
        var_a2 += 1;
        *var_a0 = *var_a1;
        var_a1 += 1;
        var_a0 += 1;
    } while (var_a2 < 4);
    *var_a0 = 0;
}
#endif

#if 0 /* yn_help_font: m2c draft, does not compile yet */
void yn_help_font(void) {
    s16 var_a0;
    s64 var_s0;
    s8 temp_a1_2;
    s8 temp_a2;
    s8 temp_s1;
    u8 *temp_a1;
    u8 *var_s2;

    temp_a1 = ynw;
    temp_a2 = M2C_FIELD(temp_a1, s8 *, 0x48);
    temp_a1_2 = M2C_FIELD(temp_a1, s8 *, 0x47);
    temp_s1 = *(temp_a2 + (yn_help_cnt_tbl + temp_a1_2));
    var_s2 = yn_help_mes_tbl[(temp_a1_2 + temp_a2)];
    var_s0 = 0;
    if (temp_s1 > 0) {
        do {
            var_a0 = M2C_FIELD(var_s2, s16 *, 0);
            if (var_a0 == -1) {
                var_a0 = (s16) ((s64) (yn_center_x(M2C_FIELD(var_s2, s32 *, 4), 0x16) << 0x30) >> 0x30);
            }
            yn_printf((s64) var_a0, M2C_FIELD(var_s2, s16 *, 2), M2C_FIELD(var_s2, s32 *, 4));
            var_s0 = (s64) ((var_s0 + 1) << 0x38) >> 0x38;
            var_s2 += 8;
        } while (var_s0 < temp_s1);
    }
}
#endif

void yn_printf(x, y, str)
int x;
int y;
char *str;
{
    flfntLocate(x, y);
    flfntPrintf(str);
}

void yn_set_pal(pal)
s8 pal;
{
    flfntSetPalette(pal);
}

void yn_set_size(w, h)
u8 w;
u8 h;
{
    flfntSetSize(w, h);
}

void yn_set_z(f32 z) {
    flfntSetZ(z);
}

void yn_set_halftype(void) {
    flfntSetHalftype();
}

s32 yn_get_halftype(void) {
    return 1;
}

/* matched as s16 in uc00.c */
int yn_center_x(u8 *str, int w) {
    int i;
    int half = 0;
    int full = 0;
    int total;

    i = 0;
    do {
        if (*str == 0) {
            break;
        }
        if (*str >= 0x80) {
            str++;
            full++;
        } else {
            half++;
        }
        i++;
        str++;
    } while (i < 0x100);
    total = 0x280 - w * full - w * half / 2;
    return total / 2;
}

int yn_strlen(char *s) {
    return strlen(s);
}

void yn_strconv(u8 *arg0, u8 *arg1, int arg2) {
    s32 n;
    s32 trunc;
    u8 c;

    if (arg1 != NULL) {
        trunc = 0;
        if ((u32)arg2 < strlen(arg1)) {
            trunc = 1;
        }
        c = *arg1;
        n = 0;
        if (c != 0) {
            do {
                if (c >= 0x80) {
                    arg0[0] = c;
                    n += 2;
                    arg0[1] = arg1[1];
                    arg1 += 2;
                    arg0 += 2;
                } else {
                    if (c == 0x25) {
                        arg0[0] = 0x25;
                        arg0++;
                    }
                    n++;
                    *arg0 = arg1[0];
                    arg1++;
                    arg0++;
                }
                if (trunc != 0 && arg2 - 3 < n) {
                    if (n < arg2) {
                        do {
                            n++;
                            *arg0 = 0x2E;
                            arg0++;
                        } while (n < arg2);
                    }
                    break;
                }
                c = *arg1;
            } while (c != 0);
        }
    }
    *arg0 = 0;
}

void yn_strconv2(u8 *arg0, u8 *arg1, u32 arg2) {
    s32 var_a3;
    s32 var_s0;
    u8 *var_s2;
    u8 *var_s3;
    u8 var_a2;

    var_s3 = arg0;
    var_s2 = arg1;
    if (var_s2 != NULL) {
        var_s0 = 0;
        if (arg2 < strlen(var_s2)) {
            var_s0 = 1;
        }
        var_a2 = *var_s2;
        var_a3 = 0;
        if (var_a2 != 0) {
loop_5:
            if ((s32) var_a2 >= 0x80) {
                M2C_FIELD(var_s3, u8 *, 0) = var_a2;
                var_a3 += 2;
                M2C_FIELD(var_s3, u8 *, 1) = (u8) M2C_FIELD(var_s2, u8 *, 1);
                M2C_FIELD(var_s3, u8 *, 2) = (u8) M2C_FIELD(var_s2, u8 *, 2);
                var_s2 = var_s2 + 2 + 1;
                var_s3 = var_s3 + 2 + 1;
            } else {
                if (var_a2 == 0x25) {
                    M2C_FIELD(var_s3, u8 *, 0) = 0x25;
                    var_s3 += 1;
                }
                var_a3 += 1;
                *var_s3 = M2C_FIELD(var_s2, u8 *, 0);
                var_s2 += 1;
                var_s3 += 1;
            }
            if ((var_s0 != 0) && ((arg2 - 3) < var_a3)) {
                if (var_a3 < (s32) arg2) {
                    do {
                        var_a3 += 1;
                        *var_s3 = 0x2E;
                        var_s3 += 1;
                    } while (var_a3 < (s32) arg2);
                }
            } else {
                var_a2 = *var_s2;
                if (var_a2 == 0) {

                } else {
                    goto loop_5;
                }
            }
        }
    }
    *var_s3 = 0;
}

void yn_strcpy(s8 *arg0, s32 arg1) {
    if (arg1 == 0) {
        *arg0 = 0;
        return;
    }
    strcpy();
}

void yn_port_init(u16 *arg0) {
    M2C_FIELD(ynw, u16 **, 0x3C) = arg0;
    M2C_FIELD(ynw, u16 *, 0x3A) = (u16) *arg0;
    M2C_FIELD(ynw, s16 *, 0x40) = 1;
    M2C_FIELD(ynw, s8 *, 0x38) = 0;
}

typedef struct { s32 a; s32 b; } PR8;
typedef struct { s32 w[130]; } PR520;

/* Copy the 0x41 pairs of proxy settings (0x208 bytes) in the work area. */
#define PROXY_COPY(dst, src) \
    do { \
        PR8 *d_ = (PR8 *)(dst); \
        PR8 *s_ = (PR8 *)(src); \
        int n_ = 0x41; \
        s32 t_; \
        do { \
            n_--; \
            t_ = s_->b; \
            d_->a = s_->a; \
            s_++; \
            d_->b = t_; \
            d_++; \
        } while (n_ > 0); \
    } while (0)

typedef struct YNW_K { u8 _p[0x28]; s32 x28; u32 rep; } YNW_K;

/* Key repeat: x28 = pad bits to act on this frame, rep = frames held. */
void yn_key_repeat(u8 *pad) {
    ((YNW_K *)ynw)->x28 = 0;
    if (M2C_FIELD(pad, u16 *, 2) == M2C_FIELD(pad, u16 *, 0)) {
        ((YNW_K *)ynw)->rep++;
        if (((YNW_K *)ynw)->rep > 20 && ((YNW_K *)ynw)->rep > 22) {
            ((YNW_K *)ynw)->rep = 0x14;
            ((YNW_K *)ynw)->x28 = M2C_FIELD(pad, u16 *, 0);
        }
    } else {
        ((YNW_K *)ynw)->rep = 0;
    }
}

#if 0 /* yn_keyboard_init: m2c draft, does not compile yet */
void yn_keyboard_init(s32 arg0, s32 arg1) {
    s32 temp_s1;

    flfntInit();
    temp_s1 = ynw + 0x50;
    memset(temp_s1, 0, 0x200);
    M2C_FIELD(ynw, s32 *, 0x4C) = arg1;
    strcpy(temp_s1, arg1);
    printf(lit_4994, strlen(arg1), arg1);
    printf(lit_4994, strlen(temp_s1), temp_s1);
    SoftKey_onoff(1);
    switch (arg0) {                                 /* irregular */
    case 0:
        Net_kb_input_init2(0x60, 0x12A, temp_s1, 0xFF);
        return;
    case 1:
        Net_kb_input_init2(0x60, 0x12A, temp_s1, 0xFF);
        return;
    case 2:
        Net_kb_input_init2(0x60, 0x12A, temp_s1, 0xFF);
        return;
    }
}
#endif

s32 yn_keyboard_sub(void) {
    u8 *temp_v0;

    if (Net_kb_input_sub() != 0) {
        SoftKey_onoff(0);
        strcpy(ynw + 0x50, SoftKey_Getstr());
        temp_v0 = ynw;
        strcpy(M2C_FIELD(temp_v0, s32 *, 0x4C), temp_v0 + 0x50);
        return 1;
    }
    return 0;
}

void yn_keyboard_server(void) {

}

void yn_draw(void) {
    flSetRenderState(0x61, 0x01000000);
    flSetRenderState(0x5E, 0x32);
    flSetRenderState(0x5F, 5);
    flSetRenderState(0x60, 0);
    flSetRenderState(0x6C, 0);
    SetFilterMode(0);
    yn_view_set();
    flSetRenderState(4, M2C_FIELD(ynw, s32 *, 4));
    yn_sprite_draw_sub(0x20, 0, -0x20);
    flSetRenderState(4, M2C_FIELD(ynw, s32 *, 0));
    yn_sprite_draw();
    yn_button_draw();
    flfntDraw(4);
    flSetRenderState(0x6C, 0);
    flSetRenderState(4, M2C_FIELD(ynw, s32 *, 0));
    yn_dialog_draw();
    flfntDraw(3);
    flSetRenderState(0x6C, 0);
    yn_set_z(250.0f);
    SoftKey_trans();
    flfntDraw(1);
    flSetRenderState(0x6C, 1);
}

void yn_view_set(void) {

}

void yn_sprite_draw_sub(s32 arg0, int arg1, int arg2) {
    f32 var_f2;
    s32 temp_s1;
    u8 temp_a1;
    u8 temp_s0;
    u8 temp_v0;

    temp_s1 = arg0 * 4;
    yn_sprite_draw_each(yn_spr_data + (*(yn_parts_data + temp_s1) * 0xC), *(yn_parts_data + 1 + temp_s1), arg1, arg2);
    temp_s0 = *(yn_parts_data + 3 + temp_s1);
    if (temp_s0 != 0) {
        flSetRenderState(0x5E, 0x12);
        temp_a1 = *(yn_parts_data + 2 + temp_s1);
        temp_v0 = M2C_FIELD(ynw, u8 *, 0x21);
        if ((s32) temp_v0 >= 0) {
            var_f2 = (f32) temp_v0;
        } else {
            var_f2 = 2.0f * (f32) ((temp_v0 >> 1) | (temp_v0 & 1));
        }
        if (!((128.0f + (127.0f * flSin(((3.1415927f * var_f2) / 2.0f) / 16.0f, 0x40490FDB, temp_a1))) >= 2.1474836e9f)) {

        }
        yn_sprite_draw_each(yn_spr_data + (temp_a1 * 0xC), temp_s0, arg1, arg2);
        flSetRenderState(0x5E, 0x32);
    }
}

#if 0 /* yn_sprite_draw_each: m2c draft, does not compile yet */
void yn_sprite_draw_each(u8 *arg0, s32 arg1, s64 arg2, s64 arg3) {
    s16 spB2;
    s16 spB0;
    s16 spAE;
    s16 spAC;
    s32 spA8;
    s16 spA6;
    s16 spA4;
    s16 spA2;
    s16 spA0;
    s16 temp_a1;
    s16 temp_a2_2;
    s16 temp_a2_3;
    s16 temp_a3;
    s16 var_v0;
    s16 var_v1;
    s32 var_s2;
    s64 var_s0;
    s64 var_s1;
    s64 var_v0_2;
    u8 *temp_a2;
    u8 *var_s5;

    var_s0 = saved_reg_s0;
    var_s1 = saved_reg_s1;
    var_s5 = arg0;
    var_s2 = 0;
    if (arg1 > 0) {
        do {
            temp_a1 = M2C_FIELD(var_s5, s16 *, 0xA);
            temp_a2 = yn_uv_data + (((s64) ((M2C_FIELD(var_s5, s16 *, 8) * 4) << 0x30) >> 0x30) * 2);
            var_v1 = M2C_FIELD(temp_a2, s16 *, 0);
            var_v0 = M2C_FIELD(temp_a2, s16 *, 2);
            temp_a3 = M2C_FIELD(temp_a2, s16 *, 4);
            temp_a2_2 = M2C_FIELD(temp_a2, s16 *, 6);
            switch (temp_a1) {                      /* irregular */
            case 0:
                var_s1 = (s64) ((((s64) ((s64) var_v1 << 0x30) >> 0x30) + ((s64) ((s64) temp_a3 << 0x30) >> 0x30)) << 0x30) >> 0x30;
                var_s0 = (s64) ((((s64) ((s64) var_v0 << 0x30) >> 0x30) + ((s64) ((s64) temp_a2_2 << 0x30) >> 0x30)) << 0x30) >> 0x30;
                break;
            case 1:
                var_s1 = (s64) ((s64) var_v1 << 0x30) >> 0x30;
                var_v1 = (s16) ((s64) ((var_s1 + ((s64) ((s64) temp_a3 << 0x30) >> 0x30)) << 0x30) >> 0x30);
                var_s0 = (s64) ((((s64) ((s64) var_v0 << 0x30) >> 0x30) + ((s64) ((s64) temp_a2_2 << 0x30) >> 0x30)) << 0x30) >> 0x30;
                break;
            case 2:
                var_s0 = (s64) ((s64) var_v0 << 0x30) >> 0x30;
                var_v0_2 = (var_s0 + ((s64) ((s64) temp_a2_2 << 0x30) >> 0x30)) << 0x30;
                var_s1 = (s64) ((((s64) ((s64) var_v1 << 0x30) >> 0x30) + ((s64) ((s64) temp_a3 << 0x30) >> 0x30)) << 0x30) >> 0x30;
block_14:
                var_v0 = (s16) (var_v0_2 >> 0x30);
                break;
            case 3:
                var_s1 = (s64) ((s64) var_v1 << 0x30) >> 0x30;
                var_s0 = (s64) ((s64) var_v0 << 0x30) >> 0x30;
                var_v0_2 = (var_s0 + ((s64) ((s64) temp_a2_2 << 0x30) >> 0x30)) << 0x30;
                var_v1 = (s16) ((s64) ((var_s1 + ((s64) ((s64) temp_a3 << 0x30) >> 0x30)) << 0x30) >> 0x30);
                goto block_14;
            }
            spA0 = M2C_FIELD(var_s5, s16 *, 0) + ((s64) (arg2 << 0x30) >> 0x30);
            spA2 = M2C_FIELD(var_s5, s16 *, 2) + ((s64) (arg3 << 0x30) >> 0x30);
            spA4 = M2C_FIELD(var_s5, s16 *, 4);
            temp_a2_3 = M2C_FIELD(var_s5, s16 *, 6);
            spA6 = temp_a2_3;
            spAC = var_v1;
            spAE = var_v0;
            spB0 = (s16) var_s1;
            spB2 = (s16) var_s0;
            spA8 = M2C_ERROR(/* Read from unset register $t0 */);
            net_flps0008((u8 *)&spA0, (u8 *)&spAC, temp_a2_3, temp_a3);
            var_s2 += 1;
            var_s5 += 0xC;
        } while (var_s2 < arg1);
    }
}
#endif

void yn_setup_allwork(u8 *arg0) {
    s32 temp_v1;
    s8 var_v0;
    u8 *temp_s0;

    SrvType = 0;
    temp_s0 = ynw + 0xEC8;
    memset(SrvDomain, 0, 0x100);
    SrvIPAddress = 0;
    SrvPort = 0;
    memset(MyDomain, 0, 0x100);
    memset(MyUserName, 0, 0x100);
    memset(MyPassword, 0, 0x100);
    MyIPAddr = 0;
    MyNetmask = 0;
    MyGateway = 0;
    MyDns1 = 0;
    MyDns2 = 0;
    memset(MyDialNumber, 0, 0xF0);
    memset(MyDialOutline, 0, 0x10);
    MyDialType = 0;
    PppRecognize = 3;
    if (M2C_FIELD(arg0, u8 *, 0x1320) == 1) {
        MyEtherInitMode = 1;
        strcpy(MyDomain, arg0 + 0x200);
    } else if (M2C_FIELD(arg0, u8 *, 0x1325) == 1) {
        MyEtherInitMode = 2;
        strcpy(MyUserName, arg0 + 0xB00);
        strcpy(MyPassword, arg0 + 0xC00);
    } else {
        MyEtherInitMode = 0;
        MyIPAddr = InetIPAddrFromString(arg0 + 0x300);
        MyNetmask = InetIPAddrFromString(arg0 + 0x400);
        MyGateway = InetIPAddrFromString(arg0 + 0x500);
    }
    if (M2C_FIELD(arg0, s8 *, 0x600) != 0) {
        MyDns1 = InetIPAddrFromString(arg0 + 0x600);
    }
    if (M2C_FIELD(arg0, s8 *, 0x700) != 0) {
        MyDns2 = InetIPAddrFromString(arg0 + 0x700);
    }
    switch (M2C_FIELD(arg0, s32 *, 0x1310)) {
    case 1:
    default:
        NdgNegoMode = 0;
        break;
    case 2:
        NdgNegoMode = 1;
        break;
    case 3:
        NdgNegoMode = 0;
        break;
    case 5:
        NdgNegoMode = 3;
        break;
    case 6:
        NdgNegoMode = 4;
        break;
    }
    BsProxyUseFlag = 0;
    memset(BsProxyUrlstr, 0, 0x100);
    memset(BsProxyUrlstr_S, 0, 0x100);
    if (M2C_FIELD(temp_s0, s32 *, 0) == 1) {
        BsProxyUseFlag = 1;
        sprintf(BsProxyUrlstr, lit_5208, temp_s0 + 8, M2C_FIELD(temp_s0, u16 *, 4));
        if (M2C_FIELD(temp_s0, u8 *, 0x108) != 0) {
            BsProxyUseFlag = (s8) (BsProxyUseFlag | 2);
            sprintf(BsProxyUrlstr_S, lit_5209, temp_s0 + 0x108, M2C_FIELD(temp_s0, u16 *, 6));
        }
    }
}

void yn_backup_allwork(u8 *ifc) {
    u8 name[4];

    name[0] = 0;
    yn_netcnf_ifc_to_work(D_5306B0, ifc, name);
    yn_netcnf_dev_to_work(D_5306B0, ifc);
    *(PR520 *)D_5310D0 = *(PR520 *)(ynw + 0xEC8);
}

void yn_proxy_wk_load(void) {
    *(PR520 *)(ynw + 0xEC8) = *(PR520 *)D_530394;
}

void yn_proxy_wk_save(void) {
    *(PR520 *)D_530394 = *(PR520 *)(ynw + 0xEC8);
}

int yn_load_texfile(int file, int size) {
    YnFile_Data_load(file, Yn_temp);
    return flCreateTextureFromTim2_mem(Yn_temp, 3);
}

extern s32 flPs2VIF1Control[];
extern char *args[2];

void yn_scecom_reboot(void) {
    str_stop_all();
    ADXPS2_LoadFcacheDvd(0);
    flPS2DmaWait();
    sceGsSyncPath(0, 0);
    flPADDestroy();
    DIntr();
    DisableDmac(flPs2VIF1Control[0]);
    RemoveDmacHandler(flPs2VIF1Control[0], flPs2VIF1Control[2]);
    DisableIntc(0);
    RemoveIntcHandler(0, flPs2GsHandler);
    EIntr();
    ADXM_ShutdownThrd();
    ADXT_Finish();
    sceGsSyncVCallback(0);
    sceCdInit(5);
    sceSifExitCmd();
    LoadExecPS2(lit_5387, 2, args);
}

